### ISSUE TITLE
GLError

### ISSUE THREAD

**Issue by ufoDziner** [jneilliii/OctoPrint-BedLevelVisualizer#100]
I'm getting an error when attempting to view the map on an android tablet.

![img_20181206_075938](https://user-images.githubusercontent.com/7434287/49622499-b6a0ff00-f97e-11e8-9590-38af21ab84f7.jpg)

**Comment by jneilliii** [comment]
Doubt I'll be able to do anything to fix that. GL Errors are graphic related which could be driver related or unsupported altogether.
