### ISSUE TITLE
Bed is shown mirrored?

### ISSUE THREAD

**Issue by justinotherguy** [jneilliii/OctoPrint-BedLevelVisualizer#105]
Hello,

love this plugin - thank you!
Alas, it seems the display shows mirrored - at least for my setup.
the right side of the bed is shown on the right side - perfect, so :)
the front side seems to be shown in the back of the visualization, though.

I kept trying to correct the bed by adjusting the four screws in the corners of the bed. Somehow things appeared to be getting worse: the more I raised the left corner on the back (was shown in blue and as being set too low), the worse things got, somehow. So, I intentionally held a flat piece below the sensor (BLTouch) during a single probe on the very right side of the bed - that showed up on the right side as expected. I did the same on the front side - but the bump showed up on the back side in the visualization.

Do you have an explanation for this?

My setup:
OctoPrint 1.3.10
Bed Visualizer 0.1.7
Tevo Tarantula (FWIT)

Do you need any more details?

Regards, J.

**Comment by jneilliii** [comment]
Use the flip options to account for this. It sounds like you want to use flip y.

**Comment by justinotherguy** [comment]
excellent - thank you! (also for the very quick and precise response!)
