### ISSUE TITLE
UBL output supported?

### ISSUE THREAD

**Issue by jeremykoerber** [jneilliii/OctoPrint-BedLevelVisualizer#107]
Hi, I just switched from Bilinear to UBL and now it looks like the plugin is collecting a ton of measurements while the probing is being done, as opposed to just the final output. My `G29 T1` looks like this:
```Send: G29 T1
Recv: 
Recv: Bed Topography Report for CSV:
Recv:
Recv: NAN	-0.087	-0.327	-0.487	-0.501
Recv: NAN	-0.151	-0.352	-0.464	-0.522
Recv: NAN	-0.378	-0.491	-0.474	-0.567
Recv: NAN	-0.366	-0.584	-0.642	-0.646
Recv: NAN	-0.605	-0.780	-0.768	-0.688
```
Not sure what GCODE commands I should provide to the plugin. Perhaps I need to turn verbosity down? In any case, my collected data is shown in the attachment. Thanks for any assistance. Love this plugin.
![image](https://user-images.githubusercontent.com/2133982/51423582-5d301080-1b77-11e9-9611-77d23153de10.png)

**Comment by jneilliii** [comment]
What do you have as your gcode settings in the plugin? This is what I use with ubl and it works fine. Maybe some issue with your report because of the NAN values. 

```
M155 S30	
@BEDLEVELVISUALIZER	
G29 T	
M155 S3
```
