### ISSUE TITLE
Let users customise "Data Collector Flag"

### ISSUE THREAD

**Issue by ysoldak** [jneilliii/OctoPrint-BedLevelVisualizer#11]
Many printers, many flags.
Just let people define totally custom flag message instead of pre-defined drop-down.

I can workaround this limitation by manually injecting one more option via dev tools in my browser, but that's a hassle. And supporting all the flags that exist out there in the plugin is not an option, i guess (pardon the pun).

Example of the flag, for Monoprice Mini Delta:
`G29 Auto Bed Leveling`

Plugin version installed: 0.0.3

Thank you for the plugin.

**Comment by jneilliii** [comment]
I agree, that's what I was about to do.

**Comment by jneilliii** [comment]
New version released.

**Comment by ysoldak** [comment]
It works, thank you. Installed 0.0.4 and verified.

**Comment by joelhuebner** [comment]
0.0.4 is for a Mini Delta, how about the Mini IIIp?  Thank you very much!!!

**Comment by jneilliii** [comment]
I don't know how that device reports. If it's a marlin variant it should work.
