### ISSUE TITLE
TypeError: t.glplot is undefined

### ISSUE THREAD

**Issue by rebeltaz** [jneilliii/OctoPrint-BedLevelVisualizer#115]
When I went to the BedAnalyzer tab the first time, I clicked on "Update Mesh". It went through the leveling procedure, but then reported back with this error when it was through:

`TypeError: t.glplot is undefined`

This is what I am using for gcode:

`G28
M155 S30
@BEDLEVELVISUALIZER
G29 T
M155 S3`

**Comment by jneilliii** [comment]
What browser are you using?

**Comment by rebeltaz** [comment]
Firefox 65.0.1 (64-bit) under Ubuntu 18.04 LTS

**Comment by rebeltaz** [comment]
Not to be a bug, but any ideas yet?

**Comment by jneilliii** [comment]
Sorry, didn't see your reply before. The only thing I can think of is that your machines video card is not open gl compatible. If you go to the plotly js examples for surface charts does it load there? 

https://plot.ly/javascript/3d-surface-plots/

**Comment by rebeltaz** [comment]
gl... the bane of my existence! OK.. yeah. That would be the issue. I need a new computer. Ill try that on a different system. Thank you for your help.
