### ISSUE TITLE
Version 1.8 no longer working.

### ISSUE THREAD

**Issue by DotNetRob** [jneilliii/OctoPrint-BedLevelVisualizer#116]
Updated to version 1.8 on my Ender 3, bed visualizer keeps saying it timed out, I increased timeout and it still says it timed out.  Probing finishes and bed visualizer just keeps spinning and then times out.  Can't get new mesh data.

**Comment by barko33** [comment]
I'm having the same issue.  Was working like a champ before with my Ender 3.  After upgrade to 1.8 I get a timeout and error.  Changing the timeout value has not effect.

**Comment by DotNetRob** [comment]
I can see in the terminal the probe is returning the data, I am guessing the visualizer is not detecting it anymore.  Can manually get the values and put into plot.ly for now.

**Comment by jneilliii** [comment]
I will revert the version for now.  Could you guys please post the results of running the commands manually in the terminal tab? And check your octoprint.log for errors. You can install the previous version using the following url in the plugin manager.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.1.7.zip

**Comment by DotNetRob** [comment]
The only error I see in the octoprint.log is attached.  I see if a few times in the log today, but i don't think they are related to bed visualizer, but I could be wrong.

Also attached my terminal output from running a probing.  I am running 5x5 on an Ender 3 with a EZABL with the lastest TH3D firmware.  

[Error.txt](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/2981347/Error.txt)
[Terminal.txt](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/2981348/Terminal.txt)

**Comment by jneilliii** [comment]
Thanks, the error is unrelated. If you haven't already reinstalled the old version do you mind checking in the plugin's settings and ser if checking the box for bilinear fixes the issue.

**Comment by DotNetRob** [comment]
Still running 1.8, will test as soon as current print job is done.

**Comment by DotNetRob** [comment]
Yep, turning on Bilinear Mesh Leveling works on 1.8.

**Comment by barko33** [comment]
I'm running and Ender3 with a BLTouch and the latest Marlin firmware.  I haven't reverted to 1.7 yet so I'll test the Bilinear Mesh tonight.

**Comment by barko33** [comment]
So 1.8 with a BLtouch and the latest Marlin firmware works with the Bilinear Mesh.

**Comment by barko33** [comment]
Oops..... Works!
