### ISSUE TITLE
Visualizer does not update the values

### ISSUE THREAD

**Issue by Brainc0re** [jneilliii/OctoPrint-BedLevelVisualizer#119]
I dont know how long this problem exist. But the today in installed a mirror on my bed. So i pressed the "update" button, it measures the bed, but the graphic does not update. Under the graphic is to read "Using saved mesh data from 6.3.2019, 00:21:27."

I also did a G28 -> G29 -> M500

The visualizer does not update and i dont know if the printer uses these old values or the new ones when i do a G29....

How can i delete these values from 6.3.2019 to force an update?

https://imgur.com/a/JTAEPG3

**Comment by jneilliii** [comment]
The printer itself will always use the real information that was calculated by the last leveling process.  The plugin only displays either the stored data or the live data based on the settings you pick.  What do your settings look like?

**Comment by Brainc0re** [comment]
G29 T
G81
M420 V

Are the command in the visualizer settings

But when i do G28-G29-M500 via the terminal. The values in the visualizer do not update.

**Comment by jneilliii** [comment]
Change your settings to this and let me know what happens when you press the update button. 

```
@BEDLEVELVISUALIZER
G29 T
```

**Comment by Brainc0re** [comment]
It sill show "Using saved mesh data from 6.3.2019, 00:21:27." and the same graphic :/

And that is from the terminal
```
Recv: echo:Auto Bed Leveling:
Recv: echo:  M420 S0 Z0.00
Recv: echo:  G29 W I0 J0 Z-0.21700
Recv: echo:  G29 W I1 J0 Z-0.10650
Recv: echo:  G29 W I2 J0 Z-0.04250
Recv: echo:  G29 W I3 J0 Z-0.02350
Recv: echo:  G29 W I4 J0 Z0.03000
Recv: echo:  G29 W I0 J1 Z-0.10600
Recv: echo:  G29 W I1 J1 Z-0.01800
Recv: echo:  G29 W I2 J1 Z-0.01000
Recv: echo:  G29 W I3 J1 Z0.00000
Recv: echo:  G29 W I4 J1 Z0.03050
Recv: echo:  G29 W I0 J2 Z-0.09500
Recv: echo:  G29 W I1 J2 Z-0.02550
Recv: echo:  G29 W I2 J2 Z0.00400
Recv: echo:  G29 W I3 J2 Z0.03800
Recv: echo:  G29 W I4 J2 Z0.06550
Recv: echo:  G29 W I0 J3 Z-0.16700
Recv: echo:  G29 W I1 J3 Z-0.09200
Recv: echo:  G29 W I2 J3 Z-0.05100
Recv: echo:  G29 W I3 J3 Z-0.04050
Recv: echo:  G29 W I4 J3 Z-0.00900
Recv: echo:  G29 W I0 J4 Z-0.17950
Recv: echo:  G29 W I1 J4 Z-0.11050
Recv: echo:  G29 W I2 J4 Z-0.08400
Recv: echo:  G29 W I3 J4 Z-0.04300
Recv: echo:  G29 W I4 J4 Z-0.04900
Recv: echo:Material heatup parameters:
Recv: echo:  M145 S0 H205 B50 F0
Recv: echo:  M145 S1 H225 B60 F0
Recv: echo:PID settings:
Recv: echo:  M301 P33.86 I3.94 D72.80
Recv: echo:Z-Probe Offset (mm):
Recv: echo:  M851 Z-1.45
Recv: echo:Filament load/unload lengths:
Recv: echo:  M603 L0.00 U100.00
Recv: ok
```

**Comment by jneilliii** [comment]
What firmware are you using? That response is one I've never seen from the G29 command before.

**Comment by Brainc0re** [comment]
Marlin 1.1.9 Creality CR10-Pro

I only changed a few settings to use a 12864 Display instead of that useless touchscreen

**Comment by jneilliii** [comment]
Please screenshot the plugin's settings for me.

**Comment by Brainc0re** [comment]
https://imgur.com/a/8z27Wlc

**Comment by Brainc0re** [comment]
Strange. I uninstalled the plug -> reboot (power off) -> reboot -> reinstalled -> reboot (regular) and the plugin showed the same picture. 

But i added the following from your github site 

`G28	
M155 S30	
@BEDLEVELVISUALIZER	
G29 T	
M155 S3`

And its working now... why? I don't know

**Comment by jneilliii** [comment]
I'm not sure.  Glad it's working for you now.
