### ISSUE TITLE
How do I setup the plugin?

### ISSUE THREAD

**Issue by NovaViper** [jneilliii/OctoPrint-BedLevelVisualizer#121]
Hey, I'm trying to get the plugin to function with my printer connection established gcode script in Octoprint. I can't run the commands directly in the bed visualizer plugin it seems timeout or never finish processing the data. I normally heat up the bed first then I run the ABL homing. The printer's connection script looks like this:
```
M190 S75
G28 ; home nozzle
G28 Z ; get more accurate Z axis 
G29 ; Generate mesh for BL-Touch
G1 X117.50 Y117.50 Z3.0 F4000.0 
M500 ; Save mesh to EEPROM
M117 Bed Leveling Mesh Complete...
M140 S0 ; turn off bed uncomment to turn off bed
M84 ; disable motors
```

But it never seems to display the data in the plugin.. am I doing something wrong here?

**Comment by jneilliii** [comment]
If you want it to automatically update with the above "printer connection" script you just need to add the `@BEDLEVELVISUALIZER` flag to instruct the plugin to collect data. 
```
M190 S75
G28 ; home nozzle
G28 Z ; get more accurate Z axis 
@BEDLEVELVISUALIZER
G29 ; Generate mesh for BL-Touch
G1 X117.50 Y117.50 Z3.0 F4000.0 
M500 ; Save mesh to EEPROM
M117 Bed Leveling Mesh Complete...
M140 S0 ; turn off bed uncomment to turn off bed
M84 ; disable motors
```

**Comment by NovaViper** [comment]
Thanks for the info! I got it working :D
