### ISSUE TITLE
Failure to install on Raspbi Zero W...

### ISSUE THREAD

**Issue by WriteCodeEveryday** [jneilliii/OctoPrint-BedLevelVisualizer#124]
The setup just times out and locks up the raspberry bi hard...

Requires a full reboot to get octoprint to come back :(

**Comment by jneilliii** [comment]
Pi Zero W takes forever to compile Numpy.  You can try doing this ahead of time by running the following commands in a terminal session.

```
cd ~/oprint/bin/
./pip install numpy
```

Once that is completed and successful the plugin should install without issue.

**Comment by Kiron21** [comment]
If you have only 512MB of RAM you can try my solution:

1)stop Octoprint: /etc/init.d/octoprint stop
2)stop other services like mjpeg-streamer in the same way.
3)install numpy (example): /home/octoprint/OctoPrint/venv/bin/python -m pip install numpy -v
