### ISSUE TITLE
It's unclear where 0,0 is (or supposed to be)

### ISSUE THREAD

**Issue by timur-tabi** [jneilliii/OctoPrint-BedLevelVisualizer#125]
I can't tell what corner of my printer the 0,0 position is supposed to be.  Is it on the left side, closest to the front of the printer?  If so, then why when I press Home the graph puts 0,0 in the opposite corner.

There needs to be an option where I press a button, and the plugin moves the print head to 0,0 so that the user can tell where that's supposed to be.

**Comment by jneilliii** [comment]
Trial and error.  Once you figure out the orientation of your bed based on adjusting a single corner you can use the flip options to orient the graph properly. There's also an option in the graph to move the nozzle to that point, it's the diretional arrow button in the graph's navigation bar, enable the option and then click on points in the graph and it will move the nozzle to that point.
