### ISSUE TITLE
The settings are not properly documented

### ISSUE THREAD

**Issue by timur-tabi** [jneilliii/OctoPrint-BedLevelVisualizer#126]
The pop-up help window that appears over each settings option just repeats what the setting is.  The README needs to have detailed documentation on each setting.  For example, I have no idea what "Bilinear Mesh Leveling" means, or whether I should turn it on, or even if it applies to my printer.

**Comment by jneilliii** [comment]
Proper is a relative term.

**Comment by timur-tabi** [comment]
Many of the options are not documented at all.

**Comment by LMS0815** [comment]
Consider asking Dr. Google:

http://marlinfw.org/meta/search/?q=Bed%20leveling

**Comment by jneilliii** [comment]
With the latest release all the options have been enhanced with better pop-over descriptions, closing issue for now. Will work on better documentation on the readme in the future.
