### ISSUE TITLE
A wiki of options for known printers would be very helpful

### ISSUE THREAD

**Issue by timur-tabi** [jneilliii/OctoPrint-BedLevelVisualizer#127]
If you look through the closed issues, you can get some hints as to how to configure this plugin for your specific printer, but that shouldn't be necessary.  Instead, there should be a wiki, or some other user-contributable document, that contains settings for various printers.

**Comment by jneilliii** [comment]
I don't have time, I believe the wiki is public, you want to help?

**Comment by timur-tabi** [comment]
I think you need to enable the Wiki, because I can't access it.

**Comment by jneilliii** [comment]
Does it show up at all?

**Comment by timur-tabi** [comment]
I see on the top of the page where it shows "Wiki", but if I click on it, all it does is bring me to the main page.  So https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/wiki just redirects to https://github.com/jneilliii/OctoPrint-BedLevelVisualizer.

**Comment by jneilliii** [comment]
Thanks, had to create the first page I think.  I added a page specifically for examples and put up the first one.

**Comment by timur-tabi** [comment]
Thanks.  I was thinking about augmenting it with settings as well.  Is that okay?

**Comment by jneilliii** [comment]
Sure.
