### ISSUE TITLE
[BUG] "First usage"(?) Setup Wizard appears EVERY refresh/load OctoPrint web page.

### ISSUE THREAD

**Issue by gruvin** [jneilliii/OctoPrint-BedLevelVisualizer#133]
Hi

Every time I load or reload the OctoPrint web interface, Bed Visualizer's (presumably intended first usage only) _Setup Wizard_ dialog appears. I have to click _Finish_ every time,  before I get to use OctoPrint.

Plugin version: 0.1.8

I do have quite a few other plugins installed. That may be part of the cause but shouldn't be, of course.,

Thanks for your work. As a no probe manual mesh editor, this plugin is SUPER useful to me. 😄 

Screen cap of what I see, for clarity ...

![Capture](https://user-images.githubusercontent.com/7283745/59219524-cd1e6080-8c16-11e9-9cc7-7d9253c8c03b.PNG)

**Comment by jneilliii** [comment]
Haven't seen that issue before. Try opening settings after you get into the interface and go to the bed visualizer area and verify your settings and save there. Then it might not show next time.

**Comment by gruvin** [comment]
I did that, actually. No change.

Can you let me know the mechanism / yaml entry or whatever it is that should be getting set to stop the first time dialog? I could set it manually, perhaps?

Thanks.

**Comment by jneilliii** [comment]
The wizard hooks are tied to the following section in config.yaml
```
plugins:
  bedlevelvisualizer:
    command:
```
So based on the functions [here](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/blob/a604b1dc3b1aeb8b21fd128428a256b62c8f1f4b/octoprint_bedlevelvisualizer/__init__.py#L50) if that is blank it will trigger the wizard to show.

**Comment by gruvin** [comment]
Thanks for the link to the code in question, which made it crystal clear that this couldn't be a bug with bedlevelvisualizer code at all. It's a pretty concise test, after all. 

So, I figured it out in the end. It was the freakin browser cache. Unbelievable! Way to go Chrome. 😖 

Thanks for your time.

**Comment by nielsjl** [comment]
Thanks gruvin. I was experiencing the exact same problem. Restarting Chrome fixed it. 👍
