### ISSUE TITLE
Two issues, I think are related.- Self resolved.

### ISSUE THREAD

**Issue by Kotawolf** [jneilliii/OctoPrint-BedLevelVisualizer#138]
I have it run the code:
G28	
@BEDLEVELVISUALIZER	
G29 T	

At the end of the sequence I'm getting the following error:
TypeError: t._fullLayout._defs is undefined

CR-10s

The second issue, is that the picture it gives, is very narrow, it isn't taking up the full width of the tab.   So, something going on with the layout, but I can' find a layout option.   Trying to attach a screen shot.
![Capture33](https://user-images.githubusercontent.com/4009622/59968672-f4243e80-9502-11e9-975a-369648d66899.PNG)

**Comment by Kotawolf** [comment]
Nevermind, dug into history and found the fix for the first one, and the second one may just be browser is being dumb.

**Comment by jneilliii** [comment]
Could also be themeify...
