### ISSUE TITLE
Please wait, retrieving current mesh.  You must be logged in.

### ISSUE THREAD

**Issue by jkiejr** [jneilliii/OctoPrint-BedLevelVisualizer#139]
Just recently updated to octoprint Version 1.3.11 and whenever i launch octoprint i get title message in bed visualizer. I believe i have put in the proper commands to level the bed, a G28 followed by a G29. I click update and it does nothing.
![d6d1e66e91fec404a28470132c016e4d](https://user-images.githubusercontent.com/1340567/60389023-3f50cb00-9a88-11e9-9c73-2600afbedca8.png)

**Comment by jneilliii** [comment]
Verify the settings are correct in the plugin's settings and save, I recommend you look at the wiki for examples...then make sure to do a [full browser refresh](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache).

**Comment by jkiejr** [comment]
So not sure what settings need to be checked or not but this is what i have
![9469d87debee86dfd18f284e6b8b4fde](https://user-images.githubusercontent.com/1340567/60390374-5224c900-9aa3-11e9-9405-64bbd40b2fc5.png)

I have delete the cached files and tried the refresh commands
Tried on IE as well

**Comment by jneilliii** [comment]
That will depend on your firmware...there are multiple examples [here](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/wiki/Firmware-Specific-GCODE-Examples).

**Comment by jkiejr** [comment]
I tried it on Internet explorer and Edge, still same issue

**Comment by jneilliii** [comment]
Make your GCODE commands the following, check the box to save mesh and restart octoprint and force a refresh on your browser.

```
M155 S30
@BEDLEVELVISUALIZER
G29 T
M155 S3
```

**Comment by jkiejr** [comment]
it doesn't appear to be saving anything when i restart octoprint, even after i hit save in the settings

**Comment by jneilliii** [comment]
Then there could be a javascript error.  If you open your developers console (F12 key on your keyboard typically) to see any errors on initial page load?

**Comment by jkiejr** [comment]
There is a connection issue
![01d82a692be7d37bf70aa1c05cf85ce1](https://user-images.githubusercontent.com/1340567/60397295-6d322000-9b19-11e9-8d98-adecf6ea5857.png)

**Comment by jneilliii** [comment]
Need you to click on the packed_plugins part on the first error. Also, upload your octoprint.log.

**Comment by jkiejr** [comment]
It appears it might have been an issue with octoprint, just installed new update today and it's fixed
