### ISSUE TITLE
G29 T problem

### ISSUE THREAD

**Issue by Fernando-Checa** [jneilliii/OctoPrint-BedLevelVisualizer#143]
I just installed the plugin on my Ender 3 with inductive sensor.
I have activated 'safe home' because the sensor is outside the bed when X is home.
The printer homes OK to the center of the bed.
I can run G29 no problem, but if I issue G29 T to get the report, the printer tries to home as before, when X is in the MIN position, so it crashes into the bed because the inductive sensor does not detect the bed at that position.

Anyone know what the problem could be?
Thanks in advance

**Comment by jneilliii** [comment]
Try M420 V.

**Comment by Fernando-Checa** [comment]
Yes, now it works. Thanks!
