### ISSUE TITLE
Not Mesh Data Output (Tronxy x5sa [400])

### ISSUE THREAD

**Issue by ChrisVonFrosta** [jneilliii/OctoPrint-BedLevelVisualizer#145]
G29 start autoleveling on machine.
After finish, no error, no output of mesh data.
G29 + parameter result in error:

````
Recv: Resend:64

Recv: //last:63 curr:65 rcv:N65 M105*20

Send: N64 G29 T*84

Recv:

Recv: //callback_pf error

Recv: //sd cmd error cnt:50839 len:13 :N64 G29 T*84

Recv:

Recv: ok
````

how gould i get the meshdata?
i would be happy with the stored data. i am ok with start autolevel over the touchdisplay.

**Comment by ChrisVonFrosta** [comment]
M420 V result in same error/output. 
the pid calibration ( M303 E0 S200 C8) do output.

**Comment by jneilliii** [comment]
What do you have in the plugin's settings? What firmware and version?

**Comment by ChrisVonFrosta** [comment]
Currently nothing. But i tried "all":
G29 or G29 T or M420 or M420 V.

Currently to check which command give mesh data output, i use the terminal.
I think if i find a command on which one my printer spitt data out, i could use it in the plugin.

EDIT:
Don't know which Firmware and Version.
M115 returns:
````
Send: N200899 M115*28
Recv: ok CBD make it.Date:Mar  5 2019 Time:18:50:13
`````
As this site ( [Chitu G code Explained](http://www.customize-3d.com/chitu-g-code-explained.html) ) tells, i have a Chitu F mini control board.

**Comment by jneilliii** [comment]
You are right, the plugin will only work if you figure out the command necessary to spit out the offset data.  Without that report there's nothing I can do to resolve this.  The firmware on your printer may just not have that option available.
