### ISSUE TITLE
Not ignoring "Bed Level Correction Matrix"

### ISSUE THREAD

**Issue by AlbatrosHurleur** [jneilliii/OctoPrint-BedLevelVisualizer#147]
Hello,

My printer's Marlin G29 reports always ends with a "Bed Level Correction Matrix" (I tried several combination of parameters and was not able to suppress it). This matrix is then added to "stored data", thus is being plotted.

![Data](https://user-images.githubusercontent.com/48366457/63224092-a56fe980-c1bf-11e9-9164-29c746006990.PNG)
![Visu](https://user-images.githubusercontent.com/48366457/63224095-a86ada00-c1bf-11e9-8d4c-da83df424f41.PNG)

Would it be possible to ignore this matrix to support my printer?

G29 P7 T output:
```
Recv: Eqn coefficients: a: 0.00011618 b: 0.00014890 d: 1.50255799
Recv: Recv: Bed Height Topography:
Recv:    +--- BACK --+
Recv:    |           |
Recv:  L |    (+)    | R
Recv:  E |           | I
Recv:  F | (-) N (+) | G
Recv:  T |           | H
Recv:    |    (-)    | T
Recv:    |           |
Recv:    O-- FRONT --+
Recv:  (0,0)
Recv:  -0.02505 -0.01255 -0.00380 +0.00245 +0.00620 +0.00995 +0.01745
Recv:  -0.01005 -0.00380 +0.00495 +0.01370 +0.01870 +0.01995 +0.02870
Recv:  -0.00130 +0.00370 +0.00120 +0.00120 -0.00130 +0.00120 -0.00255
Recv:  +0.01620 +0.01745 +0.01620 +0.01495 +0.00620 +0.00620 +0.01370
Recv:  +0.00995 +0.00870 +0.00870 +0.00745 +0.00620 +0.00995 +0.01745
Recv:  -0.01380 -0.01630 -0.01380 -0.01380 -0.01130 -0.00880 +0.00245
Recv:  -0.03255 -0.03130 -0.02880 -0.02255 -0.01880 -0.01255 -0.00630
Recv: 
Recv: 
Recv: 
Recv: Bed Level Correction Matrix:
Recv: +1.000000 +0.000000 +0.000116
Recv: -0.000000 +1.000000 +0.000149
Recv: -0.000116 -0.000149 +1.000000
```

Thanks a lot!

**Comment by jneilliii** [comment]
Do you happen to know which version of Marlin and which type of leveling your printer is using?  Have you tried using the `M420 V` command instead or `G29 T1`?

**Comment by AlbatrosHurleur** [comment]
The printer sends Marlin 1.1.0-RC6 at startup, I know the manufacturer has made customizations, I can ask if they changed something on bed leveling. I think it's using linear leveling.

I had not tried M420 V; but it seems it's not supported, nothing is displayed:
```
Send: N56 M420*22
Recv: ok
```

**Comment by jneilliii** [comment]
I'll revisit.  I thought that the code already stopped gathering points once it received that line `Bed Level Correction Matrix:` but I'll check again tonight when I get home from work.

**Comment by AlbatrosHurleur** [comment]
That would be great, we're several owning the same brand to be interested in using Bed Level Visualizer.

**Comment by jneilliii** [comment]
Try this version and let me know how it works for you.  Just use the following URL in plugin manager.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.1.10.zip

**Comment by AlbatrosHurleur** [comment]
It's working great, many thanks! 

![Options](https://user-images.githubusercontent.com/48366457/63595791-11849000-c5ba-11e9-9a29-158d34261fa2.PNG)
![Data](https://user-images.githubusercontent.com/48366457/63595622-b0f55300-c5b9-11e9-80aa-d467d656b651.PNG)
![Working](https://user-images.githubusercontent.com/48366457/63595626-b488da00-c5b9-11e9-8a25-29bb67bf34e8.PNG)

I'll notify the other people I know that were interested in this option. Nice plugin!

**Comment by jneilliii** [comment]
Thanks for testing.  I've merged the changes to the master branch and release an official 0.1.10 version with the changes.  They should be able to install directly from the plugin manager list.
