### ISSUE TITLE
 Please wait, retrieving current mesh.

### ISSUE THREAD

**Issue by HuegelMensch** [jneilliii/OctoPrint-BedLevelVisualizer#151]
" Please wait, retrieving current mesh."
is showing since 15mins.
Any Idea how to fix this ?

Im using klipper und did a 9x9 Matrix.

**Comment by jneilliii** [comment]
Need more details as to your firmware type and version as well as what you have put into the plugin's settings fur obtaining the bed topography report.

**Comment by HuegelMensch** [comment]
Iam pretty sure its my fault for using BED_MESH_CALIBRATE instead of BED_MESH_MAP.
Ill validate this tomorrow but iam pretty sure.
Sorry
