### ISSUE TITLE
Reset Camera to defaults - Customizing 

### ISSUE THREAD

**Issue by LMS0815** [jneilliii/OctoPrint-BedLevelVisualizer#152]
The _Reset Camera to defaults_ button seems to reset the view to the current maximum.
e.g. 300/300 if the bed is 300x300
![Anmerkung 2019-08-29 171954](https://user-images.githubusercontent.com/8235214/63953235-447ac800-ca81-11e9-86d6-83a1f6465718.png)

I would prefer a view, which is more or less the same as the default view which is shown when you open the tab. This would ease fine tuning and prevent me adjusting the wrong screw.
![Anmerkung 2019-08-29 172433](https://user-images.githubusercontent.com/8235214/63953602-f1554500-ca81-11e9-89d6-645253771f8e.png)

If possible synchronize the default view which is presented after opening and the  _Reset Camera to defaults_ button to the same view. I would even prefer an option to define my own coordinates for both (x/y/z).

**Comment by jneilliii** [comment]
Thanks for the detailed report.  I'll see what needs to be done to get plotly's default Reset Camera to defaults button to not mess with the orientation.

**Comment by LMS0815** [comment]
Removed HOME button in push to avoid confusion.
