### ISSUE TITLE
Feature Request: Use/capture bed leveling events not triggered by the plugin 

### ISSUE THREAD

**Issue by faithhack** [jneilliii/OctoPrint-BedLevelVisualizer#155]
It would useful if BLV could watch terminal output and use bedleveling data without the need to trigger the event or read the EEPROM.
For example, I usually do a G28 + G29 in my start GCODE which sets the bedleveling and out puts it to the terminal. It would be helpful to just switch to the Bed Level Visualizer tab and see the results without requesting an update during a active print.

**Comment by jneilliii** [comment]
If you just add the @BEDLEVELVISUALIZER tag to your start gcode it will do this.

**Comment by faithhack** [comment]
Awesome! That worked. The docs made it seem like @BEDLEVELVISUALIZER was for the settings in the plugin. Maybe update the docs to mention this is a feature for any gcode - unless I missed it and need a remedial reading class.
