### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by cluc-dev** [jneilliii/OctoPrint-BedLevelVisualizer#157]
Unlike #109 a reboot did not help me.

**Comment by jneilliii** [comment]
They also upgraded their firmware...

**Comment by cluc-dev** [comment]
Thanks for the quick response!

Is there a minimum required Marlin version? I don't see one in the readme or anything. 

I know my firmware is old so I will update it. If that fixes the problem, I will submit a PR to catch this exception and at the very least log it to the console.

**Comment by jneilliii** [comment]
I've tried accommodating as many firmwares as possible and as many versions.  Obviously this is  not always possible. I'm not sure what version of Marlin introduced the correct formatting that I'm currently able to parse. It would be helpful to know what is returned by the G29 T command.
