### ISSUE TITLE
Graph size too small on large monitors

### ISSUE THREAD

**Issue by tinkertornado** [jneilliii/OctoPrint-BedLevelVisualizer#158]
I have a very large/ high resolution monitor and have set the rest of Octoprint to use the full width of the monitor using themeify. This plug in is hard coded to use only 450px in height, which makes the graph very small on a large screen. 

Suggested solution:
class="svg-container" height: 70vh;
class="main-svg" height: 100%;
id="scene" height: 100%

**Comment by jneilliii** [comment]
Someone figured out how to modify themify to account for this.  You may want to hit them up and see what they used.

https://community.octoprint.org/t/pimp-my-web-interface/3349/11?u=jneilliii

**Comment by jneilliii** [comment]
And also, #93
