### ISSUE TITLE
Docs/Readme

### ISSUE THREAD

**Issue by BarnumD** [jneilliii/OctoPrint-BedLevelVisualizer#16]
I must be missing something, but I can't get this to do anything on my Prusa i3 mk3.  I installed the plugin, but on the plugin's page it's just blank.  On the configuration screen I changed the codes from default to G80 and G81.  I selected the Prusa Firmware Mode.  I still get nothing.  I entered those codes on the terminal and don't see a visualization.  Is there a gap in the documentation on what to do to get a visualization or am I just missing it?

Thanks

**Comment by jneilliii** [comment]
Change your Collector Data Flag to `Measured points:` there is still an issue that I'm working on that I'm about to release a fix for the display issue.

**Comment by jneilliii** [comment]
Settings screenshot updated with some more detail.
