### ISSUE TITLE
Usage instructions anywhere, please?

### ISSUE THREAD

**Issue by skypuppy** [jneilliii/OctoPrint-BedLevelVisualizer#163]
After quite a bit of searching, I can't find out how to use the apparently excellent information gatherer and presenter.  When I run the plugin, from octoprint, the window changes and says "gathering mesh" or somesuch.  Then the CR-10 S5 printer, with a 500x500 bed, starts the BL Touch sampling.  It isn't long until 'visualizer' times out and the BL Touch is still sampling.  

For the first few times, I want a very dense display and I have the mesh set at 7x7 points (it is a BIG piece of glass and the manual sampling I've done indicate several crests and troughs while trying to level (tram?) the bed)  So with this many points, I can see just where to add "stuffing."  :)  

Also, the sampled mesh doesn't seem to be stored anywhere because later, after the BL Touch has finished it's work, I tried to run 'visualizer' again and it started the entire 11 minute sampling process yet again.  There was something on the printer screen about "mesh not found" but it went by so fast I'm not sure what was happening.  The microcontroller on the printer is a 32-bit unit with tons of memory so that can't be the problem.  Help, please, or please point me to where I can find it.

Thanks.

**Comment by jneilliii** [comment]
The plugin relies on your printer's firmware and its capability of reporting the bed mesh in a way it's able to interpret. Creality runs a custom marlin build so I'm not sure if it's possible or not to work with your printer. What do you get when you type the command `M420 V` and `G29 T` in the terminal tab?
