### ISSUE TITLE
BedLevel Visualizer - Reset/Restart

### ISSUE THREAD

**Issue by Thisismydigitalself** [jneilliii/OctoPrint-BedLevelVisualizer#165]
It takes few runs to level a bed.
if between runs BLTouch needs to be reset, this means one must refresh octoprint page in order to see the update button as when BLV is waiting for printer to start it only shows "Please wait, Retrieving current mesh" message and no way to do anything other than to reload the page.

Bottom line is: UPDATE button needs to be available at all times, or a REFRESH page button.

Thank you for a great tool!

**Comment by jneilliii** [comment]
There is a timeout value that should stop that processing part and return the interface back to normal.

**Comment by Thisismydigitalself** [comment]
Oh, now i see. it was set to 100sec..
I will check if 5sec will suffice.
