### ISSUE TITLE
Plugin not working on delta with Marlin version 1.1.9

### ISSUE THREAD

**Issue by Jochefo** [jneilliii/OctoPrint-BedLevelVisualizer#172]
Plugin is not working on delta flsun with new delta calibration on Marlin 1.1.9. THe command M29 is disable on this version by default and the plugin doesn't give any bed information as the old software versions. Im going to try with the new 2.0 Marlin to see if I got any luck.

**Comment by jneilliii** [comment]
I suppose you mean G29, not M29? If mesh reporting isn't enabled in the firmware there's nothing I can do to fix that from the plugin.
