### ISSUE TITLE
Correct data collection, but no visualization

### ISSUE THREAD

**Issue by sstickel** [jneilliii/OctoPrint-BedLevelVisualizer#173]
Hello everybody,
i recently installed this plugin as it is much more flexible than my own console based python script.
Retrieving data seems to work as it should. (CATMULL is active)
<img width="554" alt="grafik" src="https://user-images.githubusercontent.com/6478954/71572628-50829f00-2ae0-11ea-898c-59962e04d95d.png">

But there is no visualization being plotted. It seems to do "something" as the scale is correct with 3mm in the middle, but no graph is displayed. Is there a way to debug this? Or is this a known issue? 
<img width="478" alt="grafik" src="https://user-images.githubusercontent.com/6478954/71572696-a5261a00-2ae0-11ea-9060-f92030e89509.png">

System is Marlin 2 based, octoprint running on a Pi 3.

The gcode the plugin is executing is:
`M155 S0`
`@BEDLEVELVISUALIZER`
`M420 V`
`M155 S3`

If you need more infos just tell me.

**Comment by jneilliii** [comment]
It's because the points measured are outside the default range. Enable the option for use relative z offsets.

**Comment by sstickel** [comment]
aha, that worked.
Why are these values out of range? To be honest I never understood till today what the absolute values here mean.

My Z-Offset is fixed at -1,95mm, this is what i get then. Bed distance is quite accurate.

**Comment by jneilliii** [comment]
The surface graph has a fixed +/-2mm on the z because of the way I programmed it. I'm not quite sure why the report from your firmware comes out that way, maybe it includes the offset in the reading.
