### ISSUE TITLE
Firmware Specific GCODE Example for Prusa Mini

### ISSUE THREAD

**Issue by bbbenji** [jneilliii/OctoPrint-BedLevelVisualizer#174]
```
M104 S170 ; set extruder temp for bed leveling
M140 S60 ; set bed temp
M109 R170 ; wait for bed leveling temp
M190 S60 ; wait for bed temp
G28 ; home all without mesh bed level
@BEDLEVELVISUALIZER ; instruct plugin to start recording responses from printer.
G29 ; mesh bed leveling 
```

**Comment by led42** [comment]
Is the mini supported?

**Comment by bbbenji** [comment]
It works, just use the gcode I posted.

**Comment by jneilliii** [comment]
Sorry, @bbbenji, not sure why I closed this issue, that was unintentional. I updated the WIKI with this information, thank you.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/wiki/Firmware-Specific-GCODE-Examples#prusa-mini
