### ISSUE TITLE
Install stuck

### ISSUE THREAD

**Issue by geirrosset** [jneilliii/OctoPrint-BedLevelVisualizer#175]
Installation on latest Octoprint is stuck at:

Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...

Never finishes. Force reboot required.

**Comment by jneilliii** [comment]
There are several other closed issues about this. It doesn't get stuck, you just have to wait forever for numpy to compile, depending on which pi you have. The best recommendation is to install numpy ahead of time.
