### ISSUE TITLE
Regular expression fails for grid with big numbers

### ISSUE THREAD

**Issue by Uinden** [jneilliii/OctoPrint-BedLevelVisualizer#177]
I am trying to setup autolevel for my printer so my report for `G29 T` has big numbers.
```
Recv: Bilinear Leveling Grid:
Recv:       0      1      2
Recv:  0 +35.993 +36.038 +36.075
Recv:  1 +35.953 +36.077 +36.198
Recv:  2 +35.999 +36.047 +36.129
Recv: 
```
Probably I'm doing something wrong but its my first time.
And I tried to see mesh in BedLevelVisualizer but it just waits for response forever.
Looks like problem in `processGCODE()`
```python
if self.processing and "ok" not in line and re.match(r"^((G33.+)|(Bed.+)|(\d+\s)|(\|\s*)|(\[?\s?\+?\-?\d?\.\d+\]?\s*\,?)|(\s?\.\s*)|(NAN\,?))+$", line.strip()):
```
Looks like it can't process those numbers
![mesh](https://user-images.githubusercontent.com/25625733/72115806-ecb66c80-3350-11ea-9b6d-63ab4c7aa20a.png)

After I got lower numbers it showed my mesh in BedLevelVisualizer and `.match` works.
![mesh2](https://user-images.githubusercontent.com/25625733/72115878-2a1afa00-3351-11ea-8ea3-f855624cb062.png)

Can we have fix for it or maybe some warning like "Your numbers are too big, check your leveling settings".

**Comment by jneilliii** [comment]
The match probably worked fine the first time, the surface mesh was just out of view on the display because it only shows +/- 2mm from 0. Enabling the option to use relative offsets would fix that.

**Comment by Uinden** [comment]
@jneilliii 
Tested again. Small numbers works without problem, but 30+ just waits forever (or until timeout)
![load](https://user-images.githubusercontent.com/25625733/72145795-e6051500-33a3-11ea-8f5c-6e65f1afeb21.png)
