### ISSUE TITLE
My Delta smashed into the bed

### ISSUE THREAD

**Issue by nikscha** [jneilliii/OctoPrint-BedLevelVisualizer#18]
hey i am new to 3d printing, if this is a stupid question which i should figure out on my own just ignore this^^

I have a Tevo Little Monster Delta printer with a BL-Touch module. When i tried to use your plugin, my printhead smashed into the bed. How can i prevent this?

**Comment by jneilliii** [comment]
This is unrelated to the plugin itself, you need to look into what the commands are for performing an auto-bed leveling routine and adjust the plugin settings GCODE script accordingly.
