### ISSUE TITLE
[Feature Request] Themes support

### ISSUE THREAD

**Issue by NovaViper** [jneilliii/OctoPrint-BedLevelVisualizer#181]
Hey, I just got Themify and made everything on there dark for my eyes, but this plugin remains to be unaffected, and I can't find a working css code for changing all of the elements of the plugin. Is it possible for you to add a dark theme like how the [TempsGraph plugin](https://plugins.octoprint.org/plugins/tempsgraph/) has an option for themes? Thanks

**Comment by jneilliii** [comment]
Pretty sure others have gotten this to work with Themify.  What specific part of the graph are you not able to adjust?

**Comment by NovaViper** [comment]
The background and the grid
![image](https://user-images.githubusercontent.com/7191115/72773712-986f8000-3bcd-11ea-9959-48d6dc021a9b.png)

**Comment by jneilliii** [comment]
I can actually make those transparent and it will work based on the Themify settings.  I'll add this to the next version update. To test it on your end, try running this in the developer console of your browser and verify it works for you.  I just tested and it seems to work as expected with a dark background.

```
Plotly.relayout('bedlevelvisualizergraph',{'plot_bgcolor': 'rgba(0, 0, 0, 0)','paper_bgcolor': 'rgba(0, 0, 0, 0)'});
```

![image](https://user-images.githubusercontent.com/5249455/72775594-02dbec80-3bdd-11ea-8f73-42774190d25d.png)

**Comment by NovaViper** [comment]
This works! Though the numbers are a tad bit hard to see

**Comment by jneilliii** [comment]
I agree.  I'll look into updating the text color based on the rest of the text on the page versus making it an option.  I did just push an update to my current dev branch.  With the transparency option set. You can install and test by using the URL in plugin manager.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.1.12.zip

**Comment by jneilliii** [comment]
Just pushed another update to that same branch that should dynamically pull these colors from other elements on the page. You should be good to go with that one.

**Comment by NovaViper** [comment]
It looks perfect in the dark theme, but is really hard to see in the white theme 
![image](https://user-images.githubusercontent.com/7191115/72780956-c365ce00-3be5-11ea-9b7e-daa486dce6c1.png)
![image](https://user-images.githubusercontent.com/7191115/72781013-de384280-3be5-11ea-8981-098d089d7d6b.png)

**Comment by jneilliii** [comment]
Did you switch tabs after changing themes?

**Comment by NovaViper** [comment]
No, I didn't.

**Comment by jneilliii** [comment]
That should reload the mesh area and the text will then be black, unless you have set overrides in themify.

**Comment by NovaViper** [comment]
Ah, switching tabs fixed the coloring
