### ISSUE TITLE
Constantly scanning printer output?

### ISSUE THREAD

**Issue by lmcbmai** [jneilliii/OctoPrint-BedLevelVisualizer#183]
I am under the impression that the plugin scans printer output all the time, i.e. not only while doing update of the chart. The reason I am saying this is because I have had several cases when the chart was successfully updated few minutes after timing out. Again, this is just an impression, I did not look into the code and cannot be positive that that is actually what is happening by design.

One of the main features of any plugin should be to be as lightweight as possible and do not take extra resources (CPU, memory, etc.) when it is not doing anything. Thus, if BedLevelVisualizer is really looking into the content of serial communication all the time, parsing the strings and searching for recognizable patterns, I'd suggest to limit all this only to the period of time from when user clicks Update button until the update is completed or timed out.

Thanks

**Comment by jneilliii** [comment]
You are correct, the plugin utilizes the gcode.received hook which passes the received serial communication through a function.  The plugin doesn't do any extensive manipulation/gathering however until the command `@BEDLEVELVISUALIZER` is sent and I've never seen any performance degradation caused, but I'm not a professional programmer and wouldn't even know where to begin to profile that. It may be possible to not register the gcode.received hook until after that command is sent, but I would have to do some research to see if that is even possible.  Have you experienced an issue with performance with the plugin enabled versus disabled?  This plugin is one of the top 3 installed globally and you're the first to mention this.

**Comment by lmcbmai** [comment]
That's fine. That's why I posted this as a suggestion and not as feature request or bug report :) 

Thanks for the great work!

**Comment by lmcbmai** [comment]
I checked the code and actually you are doing everything right. You have **self.processing** flag that disables parsing of serial input when you are not collecting new data. I think you just need to add **self.processing(false)** to **setTimeout** function in javascript file. When timeout happens you will stop looking into further input.

Also, from code optimization point of view, I'd suggest replacing all **if self.processing** in **def processGCODE** with single **if self.processing** at the very top of **processGCODE**.  Basically, if you are not in update mode, you want to get out of **processGCODE** right away. 

Thanks

**Comment by lmcbmai** [comment]
> I think you just need to add self.processing(false) to setTimeout function in javascript file.

Sorry, I just mentioned that you do have self.processing(false)  in timeout handler. Not sure why the data is still collected after timeout occurs.

**Comment by jneilliii** [comment]
Yeah, just realized that when I was looking at the cancel button implementation.  The self.process(true) only handles the front end and doesn't instruct the backend to change its self.processing to false.  I'll definitely fix that.

**Comment by jneilliii** [comment]
So actually looking at the code again, the processing should have automatically stopped upon receiving the next `ok` from the printer, but I'm still incorporating forcing the processing flag on the server side to be set to false on timeout since I had to do that for the cancel button anyway.

**Comment by jneilliii** [comment]
Added simplapiplugin mixin implementation in latest development branch to flag server side processing to false on timeout and cancel.
