### ISSUE TITLE
[Feature Request] Combine Babystep Z and BLV 

### ISSUE THREAD

**Issue by docmalc** [jneilliii/OctoPrint-BedLevelVisualizer#188]
I was thinking it would be great to be able to somehow combine BLV (great job btw!) with on-the-go bedleveling by babystepping z and using the adjusted z offset combined with your algo to re-mesh.
Sorry if terms and coherence is off =)

**Comment by jneilliii** [comment]
Not sure I understand your request, maybe you can elaborate some?  The next release will allow for custom buttons, which would allow for adding a babystepping button on the interface to send gcode commands to the printer, but not sure if that is possible while performing a bed probe process.  There is also a slightly hidden feature, that if you click on the arrows icon in the graph's toolbar it will allow you to click within the mesh and move to that position on the bed to do fine adjustments of the mesh, assuming your firmware supports that.
