### ISSUE TITLE
Octopi crashes when number of mesh point changes and update mesh is performed.

### ISSUE THREAD

**Issue by ogland** [jneilliii/OctoPrint-BedLevelVisualizer#189]
Like in title. I changed number of mesh grid points from 5 to 7 and after that my octopi web interface becomes unresponsive as soon as bilinear bed leveling grid is gonna show the output.

**Comment by jneilliii** [comment]
Are there any errors in the logs or the browser's developer console when this happens?  Haven't heard of this one.  Would also be good to know what your settings are configured like and the response from the terminal tab when you do the process.
