### ISSUE TITLE
Force loading of mesh not stored by BV

### ISSUE THREAD

**Issue by KenLucke** [jneilliii/OctoPrint-BedLevelVisualizer#190]
Bed Visualizer always seems to show only the last mesh it stored from its own probe, despite having done probes at the beginning of a print (and store them) via my gcode header.  I also sometimes do bed level tests with other plugins or via the console or terminal, saving it with M500.  Can you add a button (or a toggle option) to force it to load the current mesh stored in EEPROM rather than going through an entire probe sequence, so if I just want to look at the data from the last probe, regardless of source?

Or am I missing something that enables that already>?

**Comment by jneilliii** [comment]
Have you tried switching the gcode commands to `M420 V` instead of G29 and disable thre stored option?

**Comment by KenLucke** [comment]
Yes, that is a workaround for me, but I'd rather just have a button there so I can load the stored profile from other sources if I choose, or do the entire probe sequence over again directly in BV if I choose to do that.

**Comment by jneilliii** [comment]
Next release actually will add custom button options, per #166 discussion.
