### ISSUE TITLE
Feature Request: Add webcam view to Bed Visualiser tab

### ISSUE THREAD

**Issue by camplightsatnight** [jneilliii/OctoPrint-BedLevelVisualizer#191]
I think it would be cool to see my bed probing via the webcam inside the same tab instead of having to switch back and forth between tabs. Maybe make it an option to turn on/off for those who don't want it.

**Comment by jneilliii** [comment]
Just pushed updates to my current development branch that incorporates this feature.  If you want to beta test it, you can use the URL below in Plugin Manager.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.1.12.zip

**Comment by camplightsatnight** [comment]
Very nice!!! Thank you!!
