### ISSUE TITLE
Delta Printer Not Displaying At All - In Progress

### ISSUE THREAD

**Issue by mylife4aiurr** [jneilliii/OctoPrint-BedLevelVisualizer#20]
just tried your pluggin. I think its a cool idea to show the data visually. 
Got everything working but I dont see my data represented. 

I have a delta printer. The visualization graphic shown on the "bed visualizer" model 
tab for me shows an empty x/y/z grid. 
That seems like only for Cartesian printers. idk if delta was not considered or not supported?

If u do plan to support Delta's here is my ubl info:
```
Send: M420 V
Recv: 
Recv: Bed Topography Report:
Recv: 
Recv: (0,9)                                                                   (9,9)
Recv: (-98,98)                                                                (98,98)
Recv:      .          .          .          .       0.100    0.100       .          .          .          .
Recv: 
Recv:      .          .       0.155    0.205    0.245    0.235    0.225    0.225       .          .
Recv: 
Recv:      .       0.140    0.190    0.195    0.265    0.300    0.295    0.275    0.325       .
Recv: 
Recv:      .       0.140    0.150    0.200    0.285    0.310    0.305    0.300    0.320       .
Recv: 
Recv:   0.050    0.110    0.165    0.190    0.280    0.295    0.325    0.345    0.345    0.150
Recv: 
Recv:      .       0.074    0.250    0.275  [ 0.325]   0.310    0.300    0.385    0.395    0.150
Recv: 
Recv:      .       0.050    0.154    0.231    0.229    0.206    0.330    0.400    0.450       .
Recv: 
Recv:      .       0.200    0.128    0.159    0.186    0.305    0.370    0.440    0.525       .
Recv: 
Recv:      .          .       0.201    0.186    0.221    0.255    0.311    0.538       .          .
Recv: 
Recv:      .          .          .          .       0.200    0.245       .          .          .          .
Recv: (-98,-98)                                                                    (98,-98)
Recv: (0,0)                                                                     (9,0)
Recv: ubl.mesh_is_valid = 0
Recv: ubl.storage_slot = 1
Recv: echo:Bed Leveling On
Recv: ok P15 B3
```

**Comment by jneilliii** [comment]
Did you set the Data Collector Flag in settings?  In your case it would need to be set to `Bed Topography Report:`

**Comment by mylife4aiurr** [comment]
ok thank you for your response. Yes I set the Data collector flag. I see the blank graph with no data when I goto bed visualizer tab.
But your pluggin is able to home all axis and then poll data from my printer. Says please wait, retrieving current mesh, wait animation - then blank graph.

im using the following-
Data Collector Flag
Bed Topography Report:

GCODE Commands
G28
M420 V

I'm using bugfix 1.1.x (downloaded in march2018) with unified bed leveling. then mesh bed leveling to farther level bed.

**Comment by jneilliii** [comment]
I'll have to look to see if there is a way to plot the surface with those missing points, relative to the cartesian grid.

**Comment by mylife4aiurr** [comment]
I was mistaken B4. The map isn't blank. It is however only pulling the middle line of data points from my topography report:
 0.050    0.110    0.165    0.190    0.280    0.295    0.325    0.345    0.345    0.150
All other data points above and below middle line are not rendered and or disreguarded and not graphed.

In your example pic. Under saved mesh points, I see many lines of point data. For my Delta printer in saved mesh I only see one line of data points. 

So yea have to get interpretor to understand circle of data points not only rectangle/square

**Comment by mylife4aiurr** [comment]
If I use:
G29 T1 instead of M420 V
output looks like this:
```
Recv: Bed Topography Report for CSV:
Recv: 
Recv: NAN,NAN,NAN,NAN,0.100,0.100,NAN,NAN,NAN,NAN
Recv: NAN,NAN,0.155,0.205,0.245,0.235,0.225,0.225,NAN,NAN
Recv: NAN,0.140,0.190,0.195,0.265,0.300,0.295,0.275,0.325,NAN
Recv: NAN,0.140,0.150,0.200,0.285,0.310,0.305,0.300,0.320,NAN
Recv: 0.050,0.110,0.165,0.190,0.280,0.295,0.325,0.345,0.345,0.150
Recv: NAN,0.074,0.250,0.275,0.325,0.310,0.300,0.385,0.395,0.150
Recv: NAN,0.050,0.154,0.231,0.229,0.206,0.330,0.400,0.450,NAN
Recv: NAN,0.200,0.128,0.159,0.186,0.305,0.370,0.440,0.525,NAN
Recv: NAN,NAN,0.201,0.186,0.221,0.255,0.311,0.538,NAN,NAN
Recv: NAN,NAN,NAN,NAN,0.200,0.245,NAN,NAN,NAN,NAN

```
When I use G29 T1 i change data collector flag to 

> Bed Topography Report for CSV:

but still wont get graphed by your pluggin.

**Comment by mylife4aiurr** [comment]
Follow up: 
if I manually enter my data points at https://plot.ly/create/, the site your using its able to graph the points.

**Comment by jneilliii** [comment]
I think I could get this report to work, but have to account for the NAN text.  When you are entering it on the plotly website, how are you entering the points in the grid?  I tried and got some skewed results.

![image](https://user-images.githubusercontent.com/5249455/39089463-937d6c72-4595-11e8-8619-f32a427d77c2.png)

**Comment by mylife4aiurr** [comment]
Since I was manually entering the data, I only entered actual data. example 1st line with M420: 
  .          .          .          .       0.100    0.100       .          .          .          .
@ website I left empty cells with a "." -> blank in spreadsheet
if I had used G29 T1 with csv output "NAN", -> blank, in spreadsheet
NAN,NAN,NAN,NAN,0.100,0.100,NAN,NAN,NAN,NAN

Then I just kept entering the data
![bed data points](https://user-images.githubusercontent.com/31583073/39089812-257807ac-459d-11e8-8991-29992aa768d3.jpg)

**Comment by jneilliii** [comment]
Try installing the plugin from the link below and let me know if that works for you or not.  After install make sure the web interface reloads, otherwise press ctrl+f5.  Theoretically it should work.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.0.8.zip

**Comment by mylife4aiurr** [comment]
version 0.0.8
![settings m420 v](https://user-images.githubusercontent.com/31583073/39091392-06e41104-45c1-11e8-9e7b-d0ab299f174f.jpg)
![graph m420 v](https://user-images.githubusercontent.com/31583073/39091393-092d8dd2-45c1-11e8-892a-b1cda904e7fa.jpg)

Notice stored mesh data..... its only pulling middle line of data points

**Comment by jneilliii** [comment]
Thanks, that helps.  It's only getting the line that has data in all the cells.

**Comment by jneilliii** [comment]
I've made some adjustments to the same branch linked before.  Give it another try and let me know.

**Comment by mylife4aiurr** [comment]
Working success using- 
data collector flag>
Bed Topography Report:

GCODE Commands>
G28
M420 V or G29 T

![sucess m420](https://user-images.githubusercontent.com/31583073/39095662-06758c7e-4612-11e8-8896-be5ed66a8513.jpg)
Graph was rendered like website :) 

However the "saved mesh data" field still only shows 1 line of data NOT whole data set like picture from your example.
![settings g29 t](https://user-images.githubusercontent.com/31583073/39095699-a5ef7a26-4612-11e8-9bf4-0f19d13fb620.jpg)

-------------------------------------------------------
Not working
data collector flag>
Bed Topography Report for CSV:

GCODE Commands>
G28
G29 T1
```
Send: G29 T1
Recv: 
Recv: Bed Topography Report for CSV:
Recv: 
Recv: NAN,NAN,NAN,NAN,0.100,0.100,NAN,NAN,NAN,NAN
Recv: NAN,NAN,0.155,0.205,0.245,0.235,0.225,0.225,NAN,NAN
Recv: NAN,0.140,0.190,0.195,0.265,0.300,0.295,0.275,0.325,NAN
Recv: NAN,0.140,0.150,0.200,0.285,0.310,0.305,0.300,0.320,NAN
Recv: 0.050,0.110,0.165,0.190,0.280,0.295,0.325,0.345,0.345,0.150
Recv: NAN,0.074,0.250,0.275,0.325,0.310,0.300,0.385,0.395,0.150
Recv: NAN,0.050,0.154,0.231,0.229,0.206,0.330,0.400,0.450,NAN
Recv: NAN,0.200,0.128,0.159,0.186,0.305,0.370,0.440,0.525,NAN
Recv: NAN,NAN,0.201,0.186,0.221,0.255,0.311,0.538,NAN,NAN
Recv: NAN,NAN,NAN,NAN,0.200,0.245,NAN,NAN,NAN,NAN
```
![graph fail g29 t1](https://user-images.githubusercontent.com/31583073/39095644-d765d5ba-4611-11e8-9f33-bf71300e859c.jpg)

-------------------------------------------------------
The rendering of the graph has worked using gcode that doesn't output a csv format (M420 V or G29 T). 

If i use G29 T1, which outputs csv format - graph not rendered.

Whole data set not shown if csv format or human readable, for delta style in saved meshed data field

**Comment by mylife4aiurr** [comment]
From config.yaml
```
    camera: true
  bedlevelvisualizer:
    command: 'G28

      G29 T



      '
    mesh_timestamp: 4/21/2018, 11:44:16 PM
    report_flag: 'Bed Topography Report:'
    save_mesh: false
    stored_mesh:
    - - '0.050'
      - '0.110'
      - '0.165'
      - '0.190'
      - '0.280'
      - '0.295'
      - '0.325'
      - '0.345'
      - '0.345'
      - '0.150'
```

**Comment by jneilliii** [comment]
Thanks for all the testing.  I didn't take into account the CSV mode, will have to merge that back in.  As for the stored mesh, the reason it's not showing the correct data is because you don't have saving enabled, so it's still showing the last data that it got when that option was enabled.  Re-enable saving mesh in settings and press the update button on the visualizer tab and the data will get updated in config.yaml.

**Comment by mylife4aiurr** [comment]
Correct I just verified checking the saved mesh data does show all data points, but if you dont check it - it only shows the one line. confused me

**Comment by jneilliii** [comment]
Ok, I think I've got all use cases working now baesd on all the different reports that I was seeing posted in the issues.  Should now work with the CSV export as well. In theory, should work with all variations.  If you don't mind giving it some testing for me that would be greatly appreciated prior to me releasing an updated version.

**Comment by jneilliii** [comment]
Hold off on that, csv still isn't working correct.

**Comment by mylife4aiurr** [comment]
I dont mind testing..... but leave open issue unless fixed?

Dont u wanna separate issues?
One if data is being displayed, if human readable or csv for i3 style and delta

One for changing how data is displayed to user if delta (hoping for a circle bed representation) #28 
0,0 as center of data points (see pic)
x/y scale should reflect delta radius or printable area (see pic)
z scale lowest to highest probed points (see pic)

![b699d0309431d21056f97824ac_800x400](https://user-images.githubusercontent.com/31583073/39098553-9068f0ec-463a-11e8-85fb-b1fc2ed7c82b.jpg)

Current implementation for deltas not representative
ranging doesn't relate to delta users bed.
current
x is 1-9
y is 0-8

my Delta's :
-50 x(0) +50
-50 y(0) +50 
so radius 50 or diameter 100, then 0,0 is center of graph and bed

**Comment by mylife4aiurr** [comment]
General for delta, not just mine.
Pull data from Topography Report
(0,9)        (9,9)
(-98,98) **_min_**    (98,98)  **_max_**
that will have actual ranges
-(1/2min)  x(0)  +(1/2max)
-(1/2min)  y(0)  +(1/2max)

what do you think?

**Comment by jneilliii** [comment]
I just updated the 0.0.8 branch for final testing.  I tested with CSV and normal G29 T and both seem to be working for me.  Once this is released I'll close this issue and we'll continue on the other one for the graphing side.

**Comment by mylife4aiurr** [comment]
ok i'll try it now

**Comment by mylife4aiurr** [comment]
Confirmed regular and csv output confirmed displaying to user for me as well

**Comment by jneilliii** [comment]
Resolved with release of version 0.0.8

**Comment by jneilliii** [comment]
Would you guys be willing to test the 0.0.9 branch from the url below on your deltas?  I'm looking into simplifying the data collector and I think it might break it for you, but wanted to double check.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.0.9.zip

**Comment by mylife4aiurr** [comment]
I can do some testing tomorrow night and this weekend. Was planning on updating to lastest bugfix 1.1.x anyway.

**Comment by mylife4aiurr** [comment]
Finished updating to newer marlin bugfix 1.1.x commit (b4ddee8bebead400142fe45edc3bc41bea4ecb16), only for a newer commit (3ca3268241b9ce6040ccf413556aa2cbb0fe3bac) to be released a few hours later. 

But the point I'm making is the output of gcode commands M420 / G29 T has changed, as pointed in #40. The change breaks your pluggin for me.

However the csv format still works with your pluggin. 
So to make it work I used:
G28
G29 T1
Bed Topography Report for CSV:

The flipping x or y functionality also worked

Tested on version 0.0.9.

**Comment by jneilliii** [comment]
I thought that the change I made on the 0.0.9 branch would work with the format posted on #40, but I guess not.  I'm abandoning that change any way and will adjust the previous 0.0.8 code to work with the newer format...looks like I'll be flashing, etc. I have made improvements already to the graph for #28.
