### ISSUE TITLE
Visualizer not working

### ISSUE THREAD

**Issue by rkayd22** [jneilliii/OctoPrint-BedLevelVisualizer#204]
<img width="1211" alt="Screen Shot 2020-03-20 at 6 07 16 PM" src="https://user-images.githubusercontent.com/6746557/77216269-6186ef00-6ad6-11ea-9b13-0bbce76a6cd4.png">
Tried everything. Updated settings but still having this issue.

**Comment by jneilliii** [comment]
Try some of the recommendations in this thread.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/issues/195
