### ISSUE TITLE
Bed Visualizer causes high network load

### ISSUE THREAD

**Issue by AbuMaia** [jneilliii/OctoPrint-BedLevelVisualizer#208]
When I have this plugin enabled, there is a constant 2Mbps+ data flow on my network, which goes away only if I close the OctoPrint tab, or if I disable Bed Visualizer. I suspect this plugin is somehow keeping the webcam stream open constantly, whether the Control page is open or not. "Show webcam while processing" is disabled.

Bed Visualizer 0.1.12
OctoPrint 1.4.0 running on OctoPi 0.15.1

**Comment by jneilliii** [comment]
The new webcam feature is probably too blame here. I didn't do any form of turning on/off the image when I integrated that feature. Will look into fixing this in next release.

**Comment by jneilliii** [comment]
Just pushed a commit to the 0.1.13 branch that should resolve this issue. You can test by using the URL below in Plugin Manager until I've got more changes to officially release.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.1.13.zip

**Comment by AbuMaia** [comment]
That works. Thanks for the quick fix. :)

**Comment by AbuMaia** [comment]
Ok, the fix stopped the plugin from constantly running the video stream, until Update Mesh Now is pressed with the camera enabled during processing. Once probing has finished and the visualization has been updated, the camera stream is kept open, now showing as 3.5Mbps on my network. Refreshing the OctoPrint page stops it, though.

**Comment by jneilliii** [comment]
I'll take a look, but that doesn't make sense to me. The img src attribute is set back to blank when processing is finished if I remember correctly.

**Comment by jneilliii** [comment]
@AbuMaia how are you seeing this network utilization? I'm trying to figure out how to debug/reproduce this to see where it's happening. Once the processing of the mesh collection is completed and the graph is shown, the img displaying from the Bed Visualizer is completely removed from the UI because of the knockout if binding I'm using.

![image](https://user-images.githubusercontent.com/5249455/78179077-a09a3600-742e-11ea-9a8a-ebeabb4d6849.png)

What browser are you using?

@foosel, do you know if knockout bindings need to be disposed in some way when an element is removed from DOM to also remove it from memory? That's the only other thing I can think of that would be causing this.

**Comment by AbuMaia** [comment]
I use Firefox 74 on Ubuntu 18.04.04. And I see the network load with a taskbar netspeed indicator. The down speed drops to Kbps only after I refresh the OctoPrint page after updating the mesh through the Bed Visualizer plugin with the camera active.

It takes my printer about 5 minutes to run through a Home-Probe routine. Here are some screenshots of the Bed Visualizer tab.

The printer was homing, the camera stream over 3Mbps.
![Screenshot from 2020-04-01 19-29-40](https://user-images.githubusercontent.com/9308040/78202034-6d689e80-7450-11ea-8a40-c6099e370ff4.png)

I waited a few minutes after probing finish to take this next screenshot. Netspeed down still over 3Mbps.
![Screenshot from 2020-04-01 19-36-27](https://user-images.githubusercontent.com/9308040/78202068-82453200-7450-11ea-8c65-81076e6094ea.png)

Then I refreshed the page.
![Screenshot from 2020-04-01 19-38-17](https://user-images.githubusercontent.com/9308040/78202086-8f622100-7450-11ea-8c28-7da1b57c0646.png)

**Comment by foosel** [comment]
> @foosel, do you know if knockout bindings need to be disposed in some way when an element is removed from DOM to also remove it from memory? That's the only other thing I can think of that would be causing this.

Uff, sorry, no clue. I found this though: http://www.knockmeout.net/2014/10/knockout-cleaning-up.html

**Comment by jneilliii** [comment]
> taskbar netspeed indicator.

@AbuMaia, this must be an ubuntu specific thing? I'm unable to find any add-ons to get this on my firefox in windows.

> I found this though: http://www.knockmeout.net/2014/10/knockout-cleaning-up.html

Thanks @foosel, I'll take a look.

**Comment by AbuMaia** [comment]
The taskbar netspeed indicator? Yes, it's an Ubuntu thing. But there's a program called Rainmeter that can be set up to display the same information on the desktop. 

https://docs.rainmeter.net/tips/network-skin/

**Comment by jneilliii** [comment]
Ok, thanks. I found another one called Display Info that seems to give me the info too. So in windows on Google Chrome I do see the increase to 2.5+Mbps, but as soon as the graph displays it drops down to "normal" traffic on the network. The below shows where I've done the process twice.

![image](https://user-images.githubusercontent.com/5249455/78319978-64ea9380-7536-11ea-9c3a-1cdb89017650.png)

This leads me to believe it's either an issue with Firefox and/or Ubuntu combination. Going to do the same tests in Firefox now.

**Comment by jneilliii** [comment]
I can confirm this appears to be a Firefox issue. Just did a test in it and as soon as the graph displays sure enough the network traffic remains.

![image](https://user-images.githubusercontent.com/5249455/78320357-4042eb80-7537-11ea-9104-0b153228954a.png)

I'll see if there is any way around this.

What I find strange is that the dom element is removed from the page.

While webcam is visible.

![image](https://user-images.githubusercontent.com/5249455/78320621-decf4c80-7537-11ea-9071-e9fd38278866.png)

When webcam is closed and graph is displayed.

![image](https://user-images.githubusercontent.com/5249455/78320591-cbbc7c80-7537-11ea-96da-5c55606bede0.png)

**Comment by jneilliii** [comment]
Going to have to look into how @foosel is doing this because it doesn't happen on the control tab. It seems that with the control tab after you switch away from the tab firefox gets a final 200 return status to the img request, but with my plugin when the img is removed from DOM and the graph is shown the image never gets a finalized 200 status response.

![image](https://user-images.githubusercontent.com/5249455/78321067-f955f580-7538-11ea-9a7a-1d62c56d7b85.png)

**Comment by calania** [comment]
Was this ever fixed or why has the issue been closed? Have been holding off updating to newer versions of the plugin due to people reporting this issue.

**Comment by jneilliii** [comment]
I think I fixed it in the last version update for good. If not, please report back.

**Comment by calania** [comment]
Okay, thank you will try it!
