### ISSUE TITLE
Error: gl-fbo: Parameters are too large for FBO

### ISSUE THREAD

**Issue by Silversurfer79** [jneilliii/OctoPrint-BedLevelVisualizer#218]
Any idea whats wrong here? 

Was working fine before the update tot he new version of BLV and OP1.4.

![image](https://user-images.githubusercontent.com/58236890/78456888-148a4780-7696-11ea-856a-69fca052b37d.png)

GCODE:
```
G28
M155 S30
@BEDLEVELVISUALIZER
G29 T
M155 S3
```
Thanks

**Comment by Silversurfer79** [comment]
`G28
M155 S30
@BEDLEVELVISUALIZER
G29 T
M155 S3`

**Comment by Silversurfer79** [comment]
No this?
![image](https://user-images.githubusercontent.com/58236890/78457228-3684c980-7698-11ea-9f0f-c07b7c2908b5.png)

**Comment by jneilliii** [comment]
Please enable debug logging and restart octoprint. Press update mesh button and then download the plugin_bedlevelvisualizer_debug.log file from the logging section of octoprint's settings. Then drag and drop it into a comment here.

**Comment by Silversurfer79** [comment]
Hi, Thanks for looking ;-)

[plugin_bedlevelvisualizer_debug.log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/4432296/plugin_bedlevelvisualizer_debug.log)

**Comment by jneilliii** [comment]
No problem. what is returned in the log appears to show "normal" results, so the graphing library is probably flaking out for some reason. This is what is being graphed for the z offsets.

![image](https://user-images.githubusercontent.com/5249455/78459940-cface380-768a-11ea-8a55-a501439e8c9d.png)

Your view does look odd to me though, assuming you used the mouse to change the angle. What does it look like when it first loads? I took that debug log and virtually ran it in my OctoPrint and got this.

![image](https://user-images.githubusercontent.com/5249455/78460129-5c0bd600-768c-11ea-82c2-9c4addc9f882.png)

**Comment by Silversurfer79** [comment]
Like this,
![image](https://user-images.githubusercontent.com/58236890/78462591-3221d600-76c3-11ea-9c8b-970d80df43f3.png)

Im going to uninstall the plugin and clear the data and resinstall and see how I get on. Fingers corssed its something to do with the upgrade which is corupted.

**Comment by Silversurfer79** [comment]
No dice
![image](https://user-images.githubusercontent.com/58236890/78462969-0acd0800-76c7-11ea-9b75-475852dd284d.png)

**Comment by jneilliii** [comment]
Something is getting messed up, because the dimensions of the graph in x and y axes are in the thousands.

**Comment by Silversurfer79** [comment]
Any ideas?

**Comment by jneilliii** [comment]
Try this. Go into settings and un-check the box to store mesh and see if it makes a difference. It looks like your settings have your bed configured as 220 x 220 x 250 in OctoPrint, is that correct?

**Comment by Silversurfer79** [comment]
I found that if i switched between Bed Visualiser and Resource Monitor or refreshded the page it load like this, though I still got the same Error message. So the page loads as above (all small) and if I folow my previous points it loads like this.
![image](https://user-images.githubusercontent.com/58236890/78569364-07df2e00-7813-11ea-80b9-abaa7fc0e14d.png)

**Comment by Silversurfer79** [comment]
> 
> 
> Try this. Go into settings and un-check the box to store mesh and see if it makes a difference. It looks like your settings have your bed configured as 220 x 220 x 250 in OctoPrint, is that correct?

I have ender 3, so that is correct. Please remember this has been working up to this point (update to the new version ot BV and OP)

**Comment by Silversurfer79** [comment]
> 
> 
> Try this. Go into settings and un-check the box to store mesh and see if it makes a difference. It looks like your settings have your bed configured as 220 x 220 x 250 in OctoPrint, is that correct?

Well now...

![image](https://user-images.githubusercontent.com/58236890/78571303-8fc63780-7815-11ea-82f8-7576b0d9afc4.png)

I did notice an over lap of the previous mesh at times.

**Comment by jneilliii** [comment]
Oh wait, Resource Monitor is a good point. There could be a conflicting plotly version in that plugin. Let me check.

**Comment by jneilliii** [comment]
Nope, that's not it. Resource Monitor is using the built in graphing library of OctoPrint (flot). Not sure why this is happening, but one user on another issue mentioned that the graph would work once after saving settings, but then stop working. Would be interested to know if it's the same for you as well.

**Comment by Silversurfer79** [comment]
Its also now auto leveling when i click on the tab

**Comment by jneilliii** [comment]
Yeah, that's because we turned off the store mesh option, that is expected. In order for it to graph when that option is disabled it has to probe the bed to get the report. If it's working now with that option disabled, try enabling the option back and let's see if it sticks or reverts to a problematic situation.

**Comment by Silversurfer79** [comment]
I also noticed that there is some stange behaviour happeining and I have zoomed out so that you can see, its when i hover over the graph. highlighted below,

![image](https://user-images.githubusercontent.com/58236890/78575413-d79b8d80-781a-11ea-98d8-2092600f0432.png)

**Comment by jneilliii** [comment]
That's because of your Themify customizations I think. The width is causing weird stuff to happen.

**Comment by Silversurfer79** [comment]
Same issue
![image](https://user-images.githubusercontent.com/58236890/78615318-ae9deb80-7860-11ea-9c0a-93f08109fbce.png)

**Comment by Silversurfer79** [comment]
If I click any other tab and click back and its fine, the erro message still sticks around (top right - its missng as i cancelled it)
![image](https://user-images.githubusercontent.com/58236890/78615409-f4f34a80-7860-11ea-95a5-7441065c4330.png)

**Comment by jneilliii** [comment]
Yeah, like I mentioned, I think it's your themify customizations. Turn off Themify and let me know if this still happens. If that works then I might be able to help you resolve with the correct CSS selecors to limit the size of the containing graph to bring it back in to normal width instead of the wide set-up that is currently throwing it off.

**Comment by Silversurfer79** [comment]
> 
> 
> Yeah, like I mentioned, I think it's your themify customizations. Turn off Themify and let me know if this still happens. If that works then I might be able to help you resolve with the correct CSS selecors to limit the size of the containing graph to bring it back in to normal width instead of the wide set-up that is currently throwing it off.

@jneilliii  Your on the money, seems to be something with the overscaling of the UI due to Themify. Any chance you could fix this? I love your plugin and would really love to use it without and issues.

![image](https://user-images.githubusercontent.com/58236890/78644581-9c926c00-78a5-11ea-9965-e761e04adb29.png)

**Comment by Silversurfer79** [comment]
Well after re-enabling Themeify, the issue is no long is presant... So Ill monitor this over the coming days and report back. Fingers crossed this has been reoslved.

**Comment by jneilliii** [comment]
If it does come back you could try setting the width of `div#bedlevelvisualizergraph` CSS selector to be 588px, which is what it appears to stretch to in the non-themed view.

**Comment by Silversurfer79** [comment]
> be 588px, which is what it appears to stretch to in the non-themed view.

Where would I do this? Sorry for the doff question ;-)

**Comment by jneilliii** [comment]
In themify advanced section... the same way you set the width to make it wider...

**Comment by Silversurfer79** [comment]
Sorry @jneilliii 
Im not following, please see my advanced settings, what do I put and where?
![image](https://user-images.githubusercontent.com/58236890/79042447-cd4d0b00-7bef-11ea-9afa-6d3b87748d29.png)

**Comment by jneilliii** [comment]
Create a new custom style and set the selector to `div#bedlevelvisualizergraph` thre css-rule to `width` and the value to `588px`.

**Comment by Silversurfer79** [comment]
No dice ![image](https://user-images.githubusercontent.com/58236890/79057018-66157200-7c54-11ea-842c-848760d17e3c.png)

**Comment by jneilliii** [comment]
No dot (.) at the beginning of the css rule.

**Comment by Silversurfer79** [comment]
Same thing... Gutted

**Comment by jneilliii** [comment]
Interesting, I'll have to test this. It should work. Might require an !important at the end of the value like this, but not sure.

```
588px !important
```

**Comment by Silversurfer79** [comment]
Tried that, it lools like this now. Im not sure if its related...
![image](https://user-images.githubusercontent.com/58236890/79338193-c50e0c00-7f1e-11ea-9a35-0b4628537a1e.png)

**Comment by jneilliii** [comment]
Interesting, looks like it folded over on itself. Not sure if that's related to the sizing or not.

**Comment by Silversurfer79** [comment]
Its to unrelaible to use in this state, I will have to find another solution. Anyway to revert to the  preiviuos version which work perfectly with themify?

**Comment by jneilliii** [comment]
Yes, go to the releases tab up top and use the url for the zip file in plugin manager for thre previous version.

**Comment by Silversurfer79** [comment]
Thanks for that. With BV 0.1.12 install, first off it never presents a table and worst of all it uses 50% of my nic, sending 50MB-60MB constantly and making my Pi run like a dog (CPU 25%) (data cleared before testing). So, I updated back to 0.1.13, above issues no longer appear, as I have upgraded to OctoPrint 1.4 I am now stuck in this limbo :-(

**Comment by Silversurfer79** [comment]
Well now, after doing the downgrade 0.1.12 and clearing the data and cache and then doing the update (i guess the cache clearing maybe the fix) it seems to be responisive and alot faster and loads correctly. Watch this space, will report back. 
![image](https://user-images.githubusercontent.com/58236890/79564583-daae3d80-80a6-11ea-80c9-04620267c19e.png)

**Comment by Silversurfer79** [comment]
Scratch that, on just clicking the tab after running previously, for the first time, the error appears again (see first post). Its likely something to do the excisitng cache mesh and sizing as you suggested.

**Comment by PretzelVector** [comment]
For anyone new coming across this bug, the error can also be caused by Librewolf's "Resist Fingerprinting".

Thank you for this plugin.
