### ISSUE TITLE
Adjustment Angle Table Y ordering

### ISSUE THREAD

**Issue by luudvkeulen** [jneilliii/OctoPrint-BedLevelVisualizer#219]
I am using the new Adjustment Angle tool. I found one thing that might be a bug.
Shouldn't the Y start at 220 and then go down to 0 instead of the way around?
It is like this now:
Y
0
110
220
X 0 110 220
Wouldn't it be better to have it like this?
Y
220
110
0
X 0 110 220
Because the Front/Bottom left corner is 0.0.

**Comment by luudvkeulen** [comment]
![image](https://user-images.githubusercontent.com/10993154/78691663-2a4b7700-78f9-11ea-87ae-6bc6808ae3b0.png)

**Comment by jneilliii** [comment]
I believe there's an option in settings to flip that y axis. Those changes were added by another user.

**Comment by luudvkeulen** [comment]
> I believe there's an option in settings to flip that y axis. Those changes were added by another user.

I tried that option but it doesn't flip that table. Only the values in it.

**Comment by jneilliii** [comment]
Sorry, not the flip option in case you misinterpreted, but the option on the cureent mesh data section in settings.

![image](https://user-images.githubusercontent.com/5249455/78705956-48ef4500-78dc-11ea-9eed-e0566fe0bc4d.png)

**Comment by luudvkeulen** [comment]
Thanks! I didn't see that button at first.
