### ISSUE TITLE
Suggestion...set colors for heights...

### ISSUE THREAD

**Issue by Deadbot1** [jneilliii/OctoPrint-BedLevelVisualizer#221]
I am part of an online group and I see occasional panic posts about how far off the bed is with a pic of the graphic. Usually it's a 0.1 difference, but of course the graphic shows the alarming red and deep blue for the far ends.Would it be possible to assign a set color graph for variance from zero instead? So that a difference from zero of, say, 0.1+ is always a certain color? Or a difference from zero of 0.1- is always a certain color? This would make understanding the graph a bit more intuitive and less alarming to a newcomer.

**Comment by jneilliii** [comment]
This will be a little easier to digest in the next release. The z axis is height configurable and the color scale will be based on a percentage of that height.

![image](https://user-images.githubusercontent.com/5249455/86508541-d85aa600-bdae-11ea-9126-577b8ee00e10.png)
