### ISSUE TITLE
Logging question

### ISSUE THREAD

**Issue by kantlivelong** [jneilliii/OctoPrint-BedLevelVisualizer#229]
Howdy!

I'm working on a PR and was just curious about why `_logger` is manually instantiated and what the reasoning behind `_bedlevelvisualizer_logger` is vs using regular `_logger.debug` statements? Users can turn debug logging on from the UI in the Logging tab.

TY :)

**Comment by jneilliii** [comment]
I use that option to be able to do all my logging in a separate file rather than embedded inside the default octoprint.log.

**Comment by kantlivelong** [comment]
Ah. Wasn't sure if it was some pre-"logging options" thing. Fair enough :)
