### ISSUE TITLE
Bedlevel Bug

### ISSUE THREAD

**Issue by joloman2** [jneilliii/OctoPrint-BedLevelVisualizer#236]
i have changed my headed bed and manuely leveled it but the plugin stil says it is not level how ca i fix this 

![afbeelding](https://user-images.githubusercontent.com/64356554/80305013-60726d00-87ba-11ea-9862-f31c969a4071.png)

**Comment by jneilliii** [comment]
This drastic of a skew +2/-1.5 is to much outof alignment, adjust to get those  closer and update mesh again.

**Comment by joloman2** [comment]
i know that is looks lik if its out off alinement but it is not but is says it is

**Comment by jneilliii** [comment]
Then please enable debug logging in the plugin's settings, restart octoprint and try again. If it still does it, upload your plugin_bedlevelvisualizer_debug.log file by dragging/dropping it into a comment here,

**Comment by joloman2** [comment]
Ty for helping me it works now i reinstaled it and it works ty
