### ISSUE TITLE
Graph data does not align with visual bed representation

### ISSUE THREAD

**Issue by Silventar** [jneilliii/OctoPrint-BedLevelVisualizer#238]
Please see the attached image. The graph data under the visual data does not align with the bed.

My printer has a center homeing point, so x-150,y-150 is lower left. I have the visualization oriented that way. However, the graph shows it in the upper left. This is visually confusing.

![BedVisualizerYinverted](https://user-images.githubusercontent.com/17868374/80436802-d824c280-88b4-11ea-96e9-1f20d7c97eb1.PNG)

**Comment by jneilliii** [comment]
If you go to the current mesh tab in the plugin's settings and enable the option `Descending y axis` does it change it to what you were expecting?

**Comment by Silventar** [comment]
Yes! That is perfect. Thank you!

Shoot well!
Andrew Robertson
RobertsonArchery.com
