### ISSUE TITLE
Bed leveling results questionable

### ISSUE THREAD

**Issue by bwermes** [jneilliii/OctoPrint-BedLevelVisualizer#240]
Hello all,

First off, this is an awesome tool. It has definitely helped me get my CR10 Max to have some semblance of a level bed.

But I'm curious about the output.
My ABL touches on 25 points and my bed has 4 adjustment points.

Based on the image below, how (physically) can my bed have:
Y0 X113 higher than Y0 X0 and Y0 X225
while
Y450 X0 and Y0 X450 are lower than that point

![image](https://user-images.githubusercontent.com/22311634/80641121-3f5b8780-8a19-11ea-8379-d63d36515b83.png)

**Comment by jneilliii** [comment]
That looks extremely level, with only a 0.25 variance (side bar). So the differences you are seeing could either be related to the flatness of the bed itself or mechanical and/or inconsistencies in the probe itself.
