### ISSUE TITLE
Feature request: Add border and move z when changing point

### ISSUE THREAD

**Issue by Deses** [jneilliii/OctoPrint-BedLevelVisualizer#241]
Hi! In marlin there's an option to define a safe zone around the border to prevent proving in that area, to avoid clips and other means of bed locking...
In Marlin 2.0 is `MIN_PROBE_EDGE`.

When I move the nozzle using the plugin there's no way to add that safe border and it just moves to 0.0 right at the corner of the bed, and because it doesn't move vertically every time I select another point (it just goes straight to it without increasing Z), the nozzle could crash into the clips or something else.

Please, add a way to add that border and also move the nozzle up a little every time theres a XY change.

Thank you!

**Comment by jneilliii** [comment]
This can be handled in one of two ways...add the [GCODE](https://reprap.org/wiki/G-code#G0_.26_G1:_Move) to the plugin's settings prior to the leveling command before the `@BEDLEVELVISUALIZER` flag like this
```
G91			; use relative positioning
G1 Z10 F1200		; raise z by 10
G92			; use absolute positioning
M155 S30		; set temperature reporting delay, use a value longer than the time it takes for your leveling command to complete.
@BEDLEVELVISUALIZER	; instruct plugin to start recording responses from printer.
G29 T			; report the bed leveling mesh points.
M155 S3			; set the temperature reporting delay back to a shorter time span.
```
or enable `Z_SAFE_HOMING` in your firmware.
