### ISSUE TITLE
Adjustment Angle axis causes confusion

### ISSUE THREAD

**Issue by b4545** [jneilliii/OctoPrint-BedLevelVisualizer#246]
![image](https://user-images.githubusercontent.com/21189387/81998906-45588780-9619-11ea-969b-ea4c05017e96.png)

It took me forever to realize that your adjustment angle table does not start with 0,0 on the bottom left like one might assume, but instead has the Y origin on the top row.

Can you please please put the Y origin on the bottom row?

**Comment by b4545** [comment]
Also what would be really nice is an option to display number of turns instead of degrees. So instead of 400 degrees it would be 400/360 = 1.11 turns

**Comment by jneilliii** [comment]
There's an option for that in settings...

![image](https://user-images.githubusercontent.com/5249455/81999960-d54ffe80-9624-11ea-813e-c700882da4da.png)

And there is an option that kind of shows that math, but it's was buggy and currently hidden from view until I can figure it out.
