### ISSUE TITLE
Please Wait, Retrieving  Current Mesh

### ISSUE THREAD

**Issue by amaskedman** [jneilliii/OctoPrint-BedLevelVisualizer#249]
Mesh show up in the terminal, but "please wait, retrieving current mesh" never finishes. Im running a new Octoprint install, printer firmware is Marlin 2.05 on a CR-10 V2 with BL Touch.

**Comment by mhocso** [comment]
Same issue here after upgrading to 2.05 on an ender 3.

[edit]
after adjusting the timeout to 180 it times out and the result is displayed. It seems to miss the terminal output.

**Comment by jneilliii** [comment]
You guys upgrading, please verify your processing timeout is set high, the default is now 1800. Also try restarting octoprint once saving thre settings and trying again. If that doesn't work, enable debug logging, restart octoprint, try again. If that doesn't work upload your plugin_bedlevelvisualizer_debug.log file.
