### ISSUE TITLE
plugin removes other plugin (custom Control editor)

### ISSUE THREAD

**Issue by Clint75** [jneilliii/OctoPrint-BedLevelVisualizer#252]
when I installed the plugin my plugin Custom Control Editor was removed or disabeld,
is this as know issue? or is it somthing new?

**Comment by jneilliii** [comment]
Sounds like you're experiencing the bug with custom control editor that others have reported. That plugin author is working on the issue, but has started with system command editor first, as they both share the same bug.

**Comment by jneilliii** [comment]
I've submitted a PR to the Custom Control Editor plugin that should resolve this issue.
