### ISSUE TITLE
cannot read property 'canvas' of undefined

### ISSUE THREAD

**Issue by sacy80** [jneilliii/OctoPrint-BedLevelVisualizer#258]
![image](https://user-images.githubusercontent.com/30169265/83603176-86074900-a5a6-11ea-8d70-5b3b6b973fb4.png)

hi i got this error. after updating Bed Visuailzer.

Bed Visualizer version: 0.1.13
clear data from plugin and reprobe got the same error. 

GCODE Commands for Mesh Updae Process:
G1 X20 Y20 Z20 F3000 ; Free Axis
G28      ; aome all axes
M155 S30 ; reduce temperature reporting rate to reduce output pollution
@BEDLEVELVISUALIZER	; tell the plugin to watch for reported mesh
G29 T	   ; run bilinear probing
M155 S3  ; reset temperature reporting

enable: Save Mesh
Processing Timeout: 3000sec

**Comment by jneilliii** [comment]
What browser are you using and on what device?

**Comment by sacy80** [comment]
Google Chrome version: 83.0.4103.61 <- windows 10 desktop
Octoprint version: 1.4.0
OS: armbian ubuntu bionic 4.19.62

**Comment by jneilliii** [comment]
I've seen this error before when there was a video driver issue or your video card doesn't support openGL. If you go to the link below does the rotating box load for you?

https://get.webgl.org/

**Comment by sacy80** [comment]
the box load and rotate . :)
![image](https://user-images.githubusercontent.com/30169265/83764996-36f80b80-a6ad-11ea-8f36-2738c873da35.png)

**Comment by jneilliii** [comment]
Ok, that's strange. Enable debug logging in the plugin's settings, restart OctoPrint and force a browser refresh (shift + F5), and try again when you get a chance. If it doesn't work then, please upload your `plugin_bedlevelvisualizer_debug.log` file from the logging section of OctoPrint.

**Comment by sacy80** [comment]
Hi .. guess it my desktop issue.. after the standard SOP of deskside support, if windows dont work.. reboot the computer.. And it works.  😅😅
![image](https://user-images.githubusercontent.com/30169265/83882068-28285c00-a774-11ea-8c36-af94ff4ba0e4.png)

**Comment by jneilliii** [comment]
lol...85% of the time, yes, that typically does resolve windows issues.
