### ISSUE TITLE
No displays timestamp on mouse hover

### ISSUE THREAD

**Issue by ShagoY** [jneilliii/OctoPrint-BedLevelVisualizer#27]
Hi Jneilliii :)
It's doesn't work. I see tooltips diretly on html code but not in Chrome brower.

**Comment by jneilliii** [comment]
Do you have the option to save the mesh enabled in settings?  It will only show the timestamp when that option is enabled.  It display on mouse hover over the "i" symbol on the button.

**Comment by ShagoY** [comment]
Yes.

Btw i see on html code : 
`<i class="icon-2 icon-info-sign" data-bind="attr: {'title': mesh_status}" title="Using saved mesh data from 22/04/2018 à 17:51:17."></i>`

**Comment by jneilliii** [comment]
Yeah, the code is showing it there, and I use Chrome and it's working for me when I hover the mouse over the i symbol.

![image](https://user-images.githubusercontent.com/5249455/39097703-ea2fef02-462d-11e8-9880-b59f754af55b.png)

**Comment by jneilliii** [comment]
I didn't want the timestamp to be completely visible, but there if you wanted to see when it was run.  The title attribute is the best method I could come up with for that.

**Comment by ShagoY** [comment]
Oh sorry... I don't see "It display on mouse hover over the "i" symbol on the button."

**Comment by jneilliii** [comment]
I've pushed an 0.1.0 branch that utilizes bootstrap tooltips.  Can you please try this one by installing the plugin from the URL below and let me know if it helps with not seeing the timestamp?

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.1.0.zip
