### ISSUE TITLE
Visualizer used with WideScreen plugin overflows into right size bar when browser window not maximized.

### ISSUE THREAD

**Issue by Vic-Y** [jneilliii/OctoPrint-BedLevelVisualizer#274]
Hi,

I'm running Bed Visualizer (0.1.14) and OctoPrint-WideScreen (0.1.3) on OctoPrint 1.4.0 (OctoPi 0.17.0). Thank you for writing these two great plugins. 

When my browser (Chrome) window is not maximized, the bed visualization overflows into the right side bar.

![image](https://user-images.githubusercontent.com/62916399/88498407-3fb7e000-cf80-11ea-8172-8c92729e56d2.png)

**Comment by jneilliii** [comment]
Fixed with the above commit, will be included in the next 0.1.15 release.

**Comment by Vic-Y** [comment]
Great! Thank you.
