### ISSUE TITLE
Z axis auto limit

### ISSUE THREAD

**Issue by pyrokidd89** [jneilliii/OctoPrint-BedLevelVisualizer#275]
in the recent update the Z axes limits changed to having set values. Can you add an auto function where the Z axes max is the max from the bed level mesh and the min is the min from the bed mesh?

**Comment by jneilliii** [comment]
You are correct, the new z-axis limits the overall height. It was another request. IIRC, what you are asking for is the way it was previously?

**Comment by pyrokidd89** [comment]
Yes you are correct I preferred the previous functionality. Maybe just add check box for auto axis or maybe allow the use of "auto,auto" in the new x axis limit box.

**Comment by jneilliii** [comment]
Yeah, can't make everybody happy I suppose. I can definitely see about making the suggested change using auto,auto, Relative to this you would also have to change your colorscale to one of the standard named versions. I think the default is `RdBu`.

**Comment by jneilliii** [comment]
Fixed in the above commit, if you enter auto in the z limits it will default to the previous autoscaling on the colorscale. To be released with the next 0.1.15 version.
