### ISSUE TITLE
Right side bar not auto-scaling...

### ISSUE THREAD

**Issue by centauri61032** [jneilliii/OctoPrint-BedLevelVisualizer#276]
OK, that probably didn't make any sense. But not sure how to explain it. See the attached screenshot.
![Capture](https://user-images.githubusercontent.com/50413763/88601480-68021600-d036-11ea-9ac7-9cff32cc0b8f.JPG)
Before the latest update, the bar on the right side of the screen would vary in its overall range to show measurements that correspond to the measured mesh. In other words, using my example, instead of the bar going from +2 to -2, it should actually go from something like +0.1 to -0.1 instead. At least that is what it used to do.
If this is a setting that I can change, I don't see it.
Thanks!

**Comment by jneilliii** [comment]
I know what you mean, and that's on purpose based on previous feedback and confusion. There is already a request to get the old method back and flagged for next release, see https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/issues/275

**Comment by jneilliii** [comment]
BTW @centauri61032 the z axis can be set to -.1,.1 to possibly do what you want as well.

**Comment by jneilliii** [comment]
This setting...

![image](https://user-images.githubusercontent.com/5249455/88603037-08116c80-d042-11ea-89e7-03efb82e731e.png)
