### ISSUE TITLE
[BUG]: X-Y colors inverted on angle adjustment view

### ISSUE THREAD

**Issue by jon-daemon** [jneilliii/OctoPrint-BedLevelVisualizer#278]
**Describe the bug**
I think that the x-Position and Y-Position text colors on angle adjustment view are inverted. See the screenshot below. My bed size is 220 x 205 (X x Y), so X-Position should be green and Y-Position should be black. The only option I have checked is "Descending y axis" to have a better view on angle adjustment table. Am I missing something?

**Screenshots**
![Screen Shot 2020-07-31 at 12 24 17 PM](https://user-images.githubusercontent.com/206048/89022295-713afd80-d32a-11ea-961c-4bc905139daf.png)

**Firmware and Version**
Octoprint 1.4.0
Bed Visualizer 0.1.14
Marlin 1.1.9

**Comment by jneilliii** [comment]
You are completely right, that angle correction color assignments on the labels are completely reversed. Thanks for pointing that out.

**Comment by jneilliii** [comment]
Issue fixed in above commit, and will be part of release 0.1.15.
