### ISSUE TITLE
[BUG]: Tilt image generated not corresponding to the real tilt

### ISSUE THREAD

**Issue by Freiheitpt** [jneilliii/OctoPrint-BedLevelVisualizer#282]
**Describe the bug**
I don't know if this was already reported, but I didn't find anything.
I restarted octoprint, resetted the plugin settings and the behaviour persists.
When I adjust the back left knob, and make that corner of the bed very low (on purpose), in the image shows that the front left corner is low. It seems that the logic is somewhat inverted. Please check the screenshots.

**Expected behavior**
Image generated to be correct

**Screenshots**
![image](https://user-images.githubusercontent.com/26274469/89920420-ada90c00-dbfc-11ea-8f19-2036c92e4ea7.png)
![image](https://user-images.githubusercontent.com/26274469/89920511-c4e7f980-dbfc-11ea-9637-08680396a9ff.png)

**Firmware and Version**
Octoprint 1.4.2
Marlin 2.0

**Comment by jneilliii** [comment]
That's what all those flip and rotate options are for.

**Comment by Freiheitpt** [comment]
I tried those flip options. Thing is.. The 200 coordinates switches with the 0 coordinate (real flip).
but then my home position, is.. 0,200 taking in account the image. i will post a screenshot in a little bit
edit: what the heck?? now it stays 0,0.. I swear I saw 0,200... o.O
Well.. Sorry for the uncessary and "non-existing-bug" report.

**Comment by jneilliii** [comment]
So you're good, I can close the issue?

**Comment by Freiheitpt** [comment]
I'll close it.
Sorry again
