### ISSUE TITLE
Problem after octoprint 1.4.1 update

### ISSUE THREAD

**Issue by yordanov-alexandar** [jneilliii/OctoPrint-BedLevelVisualizer#285]
This is the GCODE I use for Bed Visualizer:
```
M80 AnetA8Plus; turn on printer
G28
M155 S30
@BEDLEVELVISUALIZER
G29 T
M155 S3
M81 AnetA8Plus; turn off printer
```
I am using this plugin [Tasmota MQTT](https://github.com/jneilliii/OctoPrint-TasmotaMQTT) to turn on/off a WIFI plug in which the printer is plugged - the M80 and M81 commands.
Before the update it was working and I haven't changed the marlin firmware in the meantime.
After the update when I start Bed Visualizer with these two lines uncommented the printer turns on, starts homing and in a few seconds is turned off. There is a GCODE off delay setting in the Tasmota MQTT plugin which is set to 10 seconds. I haven't measured after how many seconds the printer turns off but its around 10...
My guess is that the M81 command is executed immediately after M80 for some reason.
The Tasmota MQTT plugin is otherwise working without a problem - in the start of a print the printer is turned on and in the end of a print it's turned off.
"Enable Debug Logging" is turned on in Bed Visualizer but there is nothing in the plugin_bedlevelvisualizer_debug.log or octoprint.log. In the terminal i see only:
```
Send: M80
Recv: echo:Unknown command: "M80"
Recv: ok
Send: G28
```
and then nothing until:
```
Recv: Error:Printer halted. kill() called!
Changing monitoring state from "Operational" to "Error: Printer halted. kill() called!"
```
Any solution for this? 
Thank you

**Comment by jneilliii** [comment]
Forgive the stupid question, but why are you powering on/off the plugin from the Bed Level Visualizer "update mesh" gcode? Just seems to be counterproductive.

**Comment by jneilliii** [comment]
And is the issue with BLV or TasmotaMQTT update that was released 4 days ago.

**Comment by yordanov-alexandar** [comment]
My printer is normally off unless I am printing so I have to either manually start/stop it from the TasmotaMQTT button in Octoprint or use the "update mesh" code... unless there is some other place I can put that GCODE?
I have just tried it to be sure it still happens and I don't have anything to update so both plugins should be the latest versions: Tasmota-MQTT (0.3.7), Bed Visualizer (0.1.14)

**Comment by jneilliii** [comment]
Right, that's why I'm asking in regard to the versions. Do you know if your update to OctoPrint happened at the same time possibly as the update to TasmotaMQTT? It still seems strange to me to include power control commands in the BLV plugin, specifically the power off command. I could understand having a power on command, but the off command seems odd to me.

**Comment by yordanov-alexandar** [comment]
In the logs I can see that TasmotaMQTT was updated on the 19-th, and Octoprint was already on version 1.4.2 on the 17-th - the earliest log I still have. I'm pretty sure I had this problem right after I updated to 1.4.1 so it happened on the previous version of TasmotaMQTT too.
As for the off command I am often doing something else when I run the BedVisualizer and it might be some time after it has finished that I go to see the results, and I don't want the printer to continue buzzing in that time.

**Comment by jneilliii** [comment]
If you don't mind testing the older version of TasmotaMQTT to verify that would be great. There was some change in logic on how the commands are monitored and I think it might be what the actual problem is possibly. To downgrade use the URL below in Plugin Manager > Get More > ...from URL and click Install.

```
https://github.com/jneilliii/OctoPrint-TasmotaMQTT/archive/0.3.6.zip
```

**Comment by yordanov-alexandar** [comment]
You are right - the problem doesn't exist with TasmotaMQTT 0.3.6. It seems my memory of when the problem started is wrong.
