### ISSUE TITLE
[FR]: Mesh Statistics Display

### ISSUE THREAD

**Issue by DodgeDeBoulet** [jneilliii/OctoPrint-BedLevelVisualizer#286]
This is an enhancement request for additional statistical information on the displayed mesh.

I'd like to have the option to display a table showing mesh min/max/mean/average variance and standard deviation along with the graphical display.

This would bring BV's reporting in line with Duet/RepRap's Bed Height Map 😁

It would also be useful to be able to graph (or at least extract) these values over time, in-line with my previous suggestion regarding a historical mesh database.

**Comment by AcJoker2** [comment]
I can only conclude that the addon is still missing that

**Comment by jneilliii** [comment]
That is why the issue is still open.

**Comment by AcJoker2** [comment]
I know that, I have only strengthened the desire for this expansion.
The more people advocate a new role, the more interesting.

**Comment by jneilliii** [comment]
This has been implemented in the latest release candidate version of the plugin. You can change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and upgrade when prompted to test and validate.

![image](https://user-images.githubusercontent.com/5249455/147846877-4a64a39d-16b9-4ddb-bc04-9a241df1d8dd.png)
