### ISSUE TITLE
Automatically use max and min for mesh

### ISSUE THREAD

**Issue by JOSECCZ** [jneilliii/OctoPrint-BedLevelVisualizer#287]
How can it be done to use the maximum and minimum of a mesh (on the Z axis) to limit the bed visualizer graph on the Z-axis? I used to get their difference to evaluate the quality of my mesh.

**Comment by jneilliii** [comment]
To get the old method, you'll have to wait until the next release or install my current dev version and use the word `auto` for z axis limits. See #275 for additional information.
