### ISSUE TITLE
SyntaxError: Unexpected token . in JSON at position 3

### ISSUE THREAD

**Issue by PinOkeyOh** [jneilliii/OctoPrint-BedLevelVisualizer#291]
**Describe the bug**
My visualizer was working great, except that i couldn't change the z values of my graph to get a more accurate reading of my bed. I was looking through other plugins and after downloading a few my visualizer was still working but i could still not get the z values to change on my graph. Im positive i was updating the intergers in the correct space(graph z limits) but i could be wrong.    

After searching around the plugins some more i downloaded the Themify plugin and after that i started receiving the error in my octoprint window. Now my printer will go through the auto bed leveling process and will update the mesh. But the actual visual graph will not show up and i receive the error in my title. I have enabled debug logging so i will update that in here. 
 
I am using the commands
G28 
M155 S30    
@BEDLEVELVISUALIZER 
G29 T   
M155 S3

**Debug Log**

[plugin_bedlevelvisualizer_debug (2).log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/5160676/plugin_bedlevelvisualizer_debug.2.log)

**Screenshots**
![settings](https://user-images.githubusercontent.com/70578675/91943166-bf447780-ecc1-11ea-824c-0cb05fa4e796.jpg)
![mesh](https://user-images.githubusercontent.com/70578675/91943179-c23f6800-ecc1-11ea-92ee-6f8f4fd6f4b5.jpg)
![error code](https://user-images.githubusercontent.com/70578675/91943576-6b865e00-ecc2-11ea-9f9b-6284884611b8.jpg)

**Firmware and Version**
I am using the most up to date Tiny Machines firmware on my cr10s-pro v2.

Any help would be appreciated.

**Comment by jneilliii** [comment]
Your debug log indicates it's collecting the data properly. I'm not sure why this would be happening all of a sudden. I use Themeify and am not aware of any conflicts with that plugin. If you open the developer console of your browser (F12) are there any errors when you initially load the page, or when switching to the Bed Visualizer tab or when updating mesh?

**Comment by PinOkeyOh** [comment]
I get the same error as soon as i click the “bed visualizer” tab. I will try the f12 thing when i get off work tonight. Thank you

**Comment by PinOkeyOh** [comment]
Thank you for the quick reply, I ended up uninstalling and rebooting then reinstalling and rebooting and it works! along with the Graph Z limits changing now! Thanks!

**Comment by jneilliii** [comment]
Ok, closing this then. Feel free to comment here again if it comes back.
