### ISSUE TITLE
[BUG]: Fails to install on Octoprint with Python 3

### ISSUE THREAD

**Issue by dharrisHub** [jneilliii/OctoPrint-BedLevelVisualizer#295]
**Describe the bug**
Fails to install on the lastest Octoprint with Python 3. 

**Expected behavior**
Installs properly

**Comment by jneilliii** [comment]
Did you try the command in known issues relative to python 3?

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer#known-issues

**Comment by dharrisHub** [comment]
Sorry, I did not see Known Issues section. `sudo apt install libgfortran5 libatlas3-base libatlas-base-dev`  worked perfectly

**Comment by jneilliii** [comment]
great, thanks for letting me know.
