### ISSUE TITLE
[BUG]: Bed Visualizer does not appear in list of installed plugins

### ISSUE THREAD

**Issue by tpsherrill** [jneilliii/OctoPrint-BedLevelVisualizer#297]
**Describe the bug**
I've installed Bed Visualizer a few times and rebooted OctoPrint. It shows successful but is not listed in the plugins list and is not available in the settings menu.

**Expected behavior**
Bed Level Visualizer should be listed in the menu system.

**Debug Log**
[BedLevelVisualizer-install.txt](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/5219886/BedLevelVisualizer-install.txt)

**Screenshots**
No settings link present. 
![BedLevelVisualizer-install](https://user-images.githubusercontent.com/58983922/93115443-d9029900-f689-11ea-9856-a9c87e722891.PNG)

**Firmware and Version**
Ender 3 Pro with Marlin 2

**Comment by tpsherrill** [comment]
I had issues with this in a previous try. My challenges with build 14 were due to the documented dependency issue with Python 3:
Running
`sudo apt install libgfortran5 libatlas3-base libatlas-base-dev`
fixed the issue. Please close as fixed.

**Comment by jneilliii** [comment]
Thanks, that's why I had posted that in the known issues, glad you found it.
