### ISSUE TITLE
[BUG]: "Update Mesh Now" button deletes all the custom control buttons from the "custom control editor" Plugin

### ISSUE THREAD

**Issue by pediegoivan** [jneilliii/OctoPrint-BedLevelVisualizer#298]
**Describe the bug**
When I press the button "Update Mesh Now" All the buttons from the custom control editor are deleted.
I am running Octoprint Version 1.4.2 with Python 3

**Comment by jneilliii** [comment]
This is a known bug with that plugin, discussed in #228 and #244 .There is a patched version of Custom Controls that I have provided, but is not yet merged to resolve this issue that is from the Custom Controls plugin and not my plugin. You can install my patched version by copying/pasting the URL below into Plugin Manager > Get More > ... from URL.

```
https://github.com/jneilliii/octoprint-customControl/archive/devel.zip
```
