### ISSUE TITLE
Non-UBL leveling Currently Not Supported - working on fix

### ISSUE THREAD

**Issue by Core3dTech** [jneilliii/OctoPrint-BedLevelVisualizer#3]
Love the idea but... My printer requires g28 prior to g29 t1 so from the get go the visualized gets stuck on Please wait, , retrieving current mesh.

I have to reboot system, restart browser and manually perform g28 prior to opening the visualizer (once opened it won't get out of the please wait state). 

After that if I open visualizer it will perform g29 but then still get stuck on please wait. Terminal does show some results 

Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: Bilinear Leveling Grid:
Recv:       0      1      2
Recv:  0 +0.002 +0.062 -0.025
Recv:  1 -0.005 +0.022 -0.028
Recv:  2 +0.005 -0.048 -0.010
Recv: 
Recv: X:262.00 Y:175.00 Z:5.81 E:0.00 Count A:34977 B:6963 Z:2316
Recv: ok

I have not seen anything past the please wait...

**Comment by jneilliii** [comment]
What firmware are you using? The plugin only works if your firmware supports the Bed Topography Report in csv format. For Marlin that gcode is G29 T1. Other reports, like these you are showing won't know how to be interpreted without some code rewrites.

**Comment by GhostlyCrowd** [comment]
Same issue, i am on marlin.

**Comment by oliboehm** [comment]
Same issue. I'm on marlin 1.1.8. Also need G28 prior G29 T1.

I manually performed G28 and switched to the visualizer tab.
Also stucked on "Please wait, retrieving current mesh."

My Terminal output: 

Send: G29 T1
Recv: Bilinear Leveling Grid:
Recv:       0      1      2      3      4
Recv:  0 +0.190 +0.050 -0.040 -0.041 +0.221
Recv:  1 +0.157 +0.052 -0.058 -0.036 +0.132
Recv:  2 +0.203 +0.095 -0.009 -0.001 +0.162
Recv:  3 +0.257 +0.161 +0.051 +0.059 +0.211
Recv:  4 +0.340 +0.231 +0.119 +0.110 +0.334

**Comment by jneilliii** [comment]
I'm working on this, the flag being used to trigger the data collection is different based on the leveling method used.  Should have an update today to resolve this for you guys.

**Comment by Core3dTech** [comment]
Marlin bug_fix 1.1.8 in case it helps. Thx

**Comment by NickRimmer** [comment]
I've same problem with marlin

**Comment by jneilliii** [comment]
Added new release 0.0.3 to add non-UBL support.  Give it a try and report back.  I did some cursory testing with both bi-linear and UBL and it seems to work with both, make sure to select the correct "Data Collector Flag" in settings.

I specifically would like to know if the orientation of the graph display relative to the x/y axes is correct.

**Comment by oliboehm** [comment]
Now it works with Marlin 1.1.8 and Bilinear Leveling. Also orientation of axis is correct (with my configuration).

It would be nice if visualizer will not start automatically when I switch to the tab. A button to start it manually gives more control.

**Comment by jneilliii** [comment]
If the option is checked to save the mesh it will only run the G29 leveling process once, then load the graph when you switched to that tab. Every subsequent time it will load the stored mesh from memory.

**Comment by Core3dTech** [comment]
Thx, that worked!!
