### ISSUE TITLE
Bed Visualizer Error

### ISSUE THREAD

**Issue by btk007** [jneilliii/OctoPrint-BedLevelVisualizer#30]
Hello,
I, upgrade to v 0.0.8 and I got this error:

Bed Visualizer Error
Looks like your settings are not correct or there was an error. Please see the Readme for configuration hints.

TypeError: Plotly.react is not a function

I set all the plug-in parameters as in Readme but I still have this error and no graph display.
Best regards.
Laurent

**Comment by jneilliii** [comment]
Do you have the tempsgraph plugin installed? There is a conflict between the two.

**Comment by btk007** [comment]
Yes. I disable tempsgraph and it's working.
Thanks.
