### ISSUE TITLE
 Please wait, retrieving current mesh | It keeps loading on Ender 5 Plus

### ISSUE THREAD

**Issue by TnkrrGit** [jneilliii/OctoPrint-BedLevelVisualizer#307]
Hey there, i am using a Raspberry pi 3 Model B and a Creality Ender 5 plus. Its not doing anything. I reinstalled multiple times. But nothing was wrong about that. Any ideas?

**Comment by jneilliii** [comment]
The issue template had detailed instructions on what I need to help you out, specifically the settings you've configured, the pliugin_bedlevelvisualizer_debug.log, and the output in your terminal from running update mesh button.
