### ISSUE TITLE
[FR]:  Please add timeout parameter to @BEDLEVELVISUALIZER

### ISSUE THREAD

**Issue by LMS0815** [jneilliii/OctoPrint-BedLevelVisualizer#314]
Please add a timeout value as optional parameter to `@BEDLEVELVISUALIZER 30` which is overwriting the default from the settings.

This would be useful if you have various methods getting the mesh.

e.g. UBL:
```
@BEDLEVELVISUALIZER 30
G29 PT; Probe
G29 P3 T; calculate missing points and report
```
```
@BEDLEVELVISUALIZER 5
G29 T; Report only
```

**Comment by jneilliii** [comment]
Just added a version 1.0.1rc2 that adds this functionality. It's possible that you could experience a race condition if you make it too short, but it should be pretty obvious. If you want to test you can change the Release Channel for the plugin to Release Candidate in Octoprint's Software Update settings (assuming OctoPrint 1.5.0+).
