### ISSUE TITLE
[BUG]: BLV Broken in OctoPrint 1.5.0

### ISSUE THREAD

**Issue by jneilliii** [jneilliii/OctoPrint-BedLevelVisualizer#319]
**Describe the bug**
when using OctoPrint 1.5.0rc1 the tables don't load.

**Expected behavior**
mesh data and angle corrections tables to work.

**Debug Log**

**Screenshots**
![image](https://user-images.githubusercontent.com/5249455/98699075-bd8fd380-2344-11eb-8728-876b1768385d.png)

**Firmware and Version**
N/A

**Comment by jneilliii** [comment]
@LMS0815 I was wondering if you might know why the latest knockout upgrade included in OctoPrint 1.5.0 broke your correction matrix and mesh data tables? Seems there is an error related to `$parentContext.$index is not a function`.

**Comment by Pavulon87** [comment]
Octolapse is affected too:
`packed_core.js?4e2bc246:1021 Could not bind view model  to target #octolapse_tab : ReferenceError: Unable to process binding "template: function(){return 'snapshot-plan-status-template' }"`
Pretty gcode:
`Could not bind view model PrettyGCodeViewModel to target #tab_plugin_prettygcode : Error: You cannot apply bindings multiple times to the same element.`

BLV:
`Could not bind view model bedlevelvisualizerViewModel to target #settings_plugin_bedlevelvisualizer : TypeError: Unable to process binding "template: function(){return {name:'bedlevelvisualize_meshtable',data:{mesh:$root.mesh_data(),len:3}} }"`

`packed_core.js?4e2bc246:1021 Could not bind view model bedlevelvisualizerViewModel to target #tab_plugin_bedlevelvisualizer : TypeError: Unable to process binding "if: function(){return $root.showdegree() && $root.mesh_data().length }"`

**Comment by jneilliii** [comment]
pretty gcode actually has a PR against it from foosel that resolves its issue. The error with BLV is a little more involved and will probably take a while for me to fix, unless @LMS0815 is able to step in and advise, as all the effected parts were contributed to this plugin by them.

**Comment by LMS0815** [comment]
I am currently bound to an other project with limited time. I'll try installing a RC test environment (earliest next week). 
This is probably related to the ViewModel container parent/child references...

**Comment by jneilliii** [comment]
I think I was able to figure it out with a little tweak to the childContext option of the inner most foreach binding. If anyone makes it here looking for a fix, you can copy/paste the URL below in plugin manager > get more > ...from URL.

```
https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/1.0.0rc4.zip
```

**Comment by Pavulon87** [comment]
> I think I was able to figure it out with a little tweak to the childContext option of the inner most foreach binding. If anyone makes it here looking for a fix, you can copy/paste the URL below in plugin manager > get more > ...from URL.
> 
> ```
> https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/1.0.0rc4.zip
> ```
For me it is fixed.

**Comment by jneilliii** [comment]
Awesome, thanks for confirming @Pavulon87.
