### ISSUE TITLE
[BUG]: Illegal Instruction

### ISSUE THREAD

**Issue by racerxdl** [jneilliii/OctoPrint-BedLevelVisualizer#320]
**Describe the bug**
After installing the BedLevelVisualizer, the Octoprint doesnt start anymore giving a Illegal instruction message.

**Expected behavior**
Octoprint works

**Debug Log**
Can't get log since octoprint does not start after installing the plugin.

**Screenshots**

![image](https://user-images.githubusercontent.com/578310/99159671-70519000-26bd-11eb-91ed-cb3786135749.png)
![image](https://user-images.githubusercontent.com/578310/99159674-77789e00-26bd-11eb-8090-ace914fbb873.png)

**Firmware and Version**
Octoprint installed on ubuntu using https://octoprint.org/download/ manual install tutorial.

I did a fresh install of the Octoprint, and it gives me the same error. Its an AArch64 platform (ODROID C2)

**Comment by jneilliii** [comment]
My assumption here it's related to numpy. You can uninstall by running the following command, replacing the path to your venv folder's pip command. The path listed below is what you would see on an octopi installation.

```
~/oprint/bin/pip uninstall Bed-Visualizer
```

**Comment by miklschmidt** [comment]
Same problem here on octopi0.17.0, octoprint version 1.4.2, python 2.7. Failed to install, then server shutdown. Restarting it works fine, but i can't install the plugin.

**Comment by jneilliii** [comment]
This is probably due to the numpy dependency not compiling. Try to run the following commands on your pi via SSH while not printing.

```
~/oprint/bin/pip install numpy
sudo service octoprint restart
```

then try again and report back.

**Comment by jneilliii** [comment]
@miklschmidt are you also on AArch64 platform (ODROID C2)?

**Comment by miklschmidt** [comment]
@jneilliii no sorry, i'm on a regular Raspberry Pi 4 Model B 4gb.

**Comment by ecob81** [comment]
Same problem on Pi 3 B+. Fails to install Numpy

tried

~/oprint/bin/pip install numpy

and stopped at

Running setup.py bdist_wheel for numpy ...

**Comment by jneilliii** [comment]
did it stop, or you just didn't wait long enough? The compile time on Pi 3 B+ would be around 20-40 minutes if I remember correctly. Another option is to upgrade your octoprint environment to python 3 using the script linked below, running the command `sudo apt install libatlas3-base` after the upgrade is complete and then install the plugin.

https://github.com/cp2004/Octoprint-Upgrade-To-Py3

Another option would be flashing the octopi 0.18rc1 image to a sd card and it already is python 3 and has the libatlas3-base pre-installed.

**Comment by ecob81** [comment]
Thankyou, I just needed to wait longer, it took around 15mins to install numpy.

I used "~/oprint/bin/pip install numpy" and then installed plugin but guessing it would have all installed ok from octoprint ui if I waited longer.

**Comment by danships** [comment]
For anyone else landing here: I use an Odroid C2, and the wheel that pip downloaded turned out not to be compatible with the architecture of the device. I forced a local compilation of numpy using: `pip install --no-binary :all: numpy==1.20.3`
