### ISSUE TITLE
Question about Auto Update???

### ISSUE THREAD

**Issue by Sekisback** [jneilliii/OctoPrint-BedLevelVisualizer#326]
Not a bug its a question.

Ist it possible that BLV displays the **last** saved mesh per default?
to get the current mesh i have to push "update mesh now" 

I wrote a G29 in Cura Start script, so every print will be new leveled. It is possible that BLV dispays this last mesh without pushing the Button?

```
G28;
M155 S30 ; reduce temperature reporting rate to reduce output pollution
@BEDLEVELVISUALIZER	; tell the plugin to watch for reported mesh
G29 T	   ; run bilinear probing
M155 S3  ; reset temperature reporting
```

**Comment by jneilliii** [comment]
That is correct. If you have that in your start gcode on the slicer the graph should update after the probing process is complete. The @BEDLEVELVISUALIZER will however only work if printing from OctoPrint local files. If you print from SD card you need to replace `@BEDLEVELVISUALIZER` with `M118 E1 BEDLEVELVISUALIZER` and your firmware has to support the M118 command. You can test that by sending the command from terminal tab and verifying the response.
