### ISSUE TITLE
[BUG]: y axis inverted in linear leveling

### ISSUE THREAD

**Issue by hamster65** [jneilliii/OctoPrint-BedLevelVisualizer#328]
Hi,
in linear levelling, the Marlin output of the y axis is inverted compared to bilinear levelling. Front and back are swapped.
I noticed that when I placed a small object onto my bed at the front and probed. With bilinear levelling, bed level visualizer shows it at the front, where it is. But with linear levelling, it appears at the back of the bed.

I am aware that you can swap the axis in the options but I wonder if anyone has noted that issue before.
Another question is if it is worth the effort to fix it and then, where... Fix the inconsistent output in Marlin or adapt bed level visualizer.

Recv: Bilinear Leveling Grid:
Recv:       0      1      2      3      4      5      6      7
Recv:  0 -0.041 -0.067 -0.066 +0.012 **+0.948** +0.058 +0.043 +0.065
Recv:  1 -0.013 -0.011 -0.011 +0.039 +0.046 +0.080 +0.048 +0.049
Recv:  2 -0.028 -0.022 +0.002 +0.032 +0.089 +0.087 +0.055 +0.022
Recv:  3 -0.096 -0.095 -0.063 +0.011 +0.042 +0.028 +0.012 -0.034
Recv:  4 -0.159 -0.120 -0.096 -0.018 +0.015 +0.021 -0.026 -0.068
Recv:  5 -0.179 -0.153 -0.097 -0.055 -0.016 -0.014 -0.070 -0.100
Recv:  6 -0.123 -0.092 -0.068 -0.006 -0.005 +0.001 -0.055 -0.081
Recv:  7 +0.033 +0.035 +0.043 +0.101 +0.108 +0.118 +0.062 +0.040

#Linear
Recv: Bed Height Topography:
Recv:    +--- BACK --+
Recv:    |           |
Recv:  L |    (+)    | R
Recv:  E |           | I
Recv:  F | (-) N (+) | G
Recv:  T |           | H
Recv:    |    (-)    | T
Recv:    |           |
Recv:    O-- FRONT --+
Recv:  (0,0)
Recv:  +0.04066 +0.03472 +0.05034 +0.10014 +0.09972 +0.09336 +0.06909 +0.03899
Recv:  -0.09914 -0.08486 -0.08445 -0.00632 -0.01393 -0.00778 -0.05549 -0.08111
Recv:  -0.17111 -0.15341 -0.11361 -0.04789 -0.04820 -0.05476 -0.07111 -0.10132
Recv:  -0.14309 -0.13705 -0.07278 -0.01049 -0.00205 +0.00399 -0.04361 -0.07747
Recv:  -0.12164 -0.10382 -0.04799 -0.01445 +0.02503 +0.01899 +0.01045 -0.04351
Recv:  -0.02955 -0.02351 +0.01701 +0.04722 +0.05534 +0.06170 +0.09409 +0.02014
Recv:  -0.01393 -0.02820 +0.00336 +0.04534 +0.03680 +0.07076 +0.04639 +0.04826
Recv:  -0.05809 -0.07570 -0.04341 +0.00284 **+0.96284** +0.04941 +0.06586 +0.07201

**Comment by jneilliii** [comment]
that's actually why the swap axis and rotate options exist, I've adapted with settings to make the data look right. There's just no real good way that I could figure out how to handle it otherwise.
