### ISSUE TITLE
TypeError: Plotly.react is not a function

### ISSUE THREAD

**Issue by wardnica** [jneilliii/OctoPrint-BedLevelVisualizer#33]
Hi,
I'm getting this "Plotly.react is not a function" error when i'm trying to use the plugin.

I've installed the plugin from the Plugin Manager.
This are my settings:
![image](https://user-images.githubusercontent.com/8615135/39149591-ec7b3e52-473f-11e8-9005-5f1608b63e92.png)
Tried both with the Save Mesh checkbox checked and unchecked.. 
I've updated the Plotly on my Pi via SSH but that didn't solve it.

**Comment by jneilliii** [comment]
This is caused by a conflict with the tempsgraph plugin.
