### ISSUE TITLE
[FR]: Flip the angle corrections table upside down

### ISSUE THREAD

**Issue by mfurlend** [jneilliii/OctoPrint-BedLevelVisualizer#333]
First I wanna say great job with this plugin. IMO it is the most useful plugin out there.
My issue is with the angle correction table. It appears  vertically flipped in respect to a top-town view of the mesh. This makes it kind of hard and annoying to determine which sides I actually need to correct by how much. A simple toggle to flip it upside down would be awesome.

Thanks!

**Comment by jneilliii** [comment]
Could you please elaborate, possibly with screenshots, not sure I quite understand.

**Comment by mfurlend** [comment]
<img width="633" alt="image" src="https://user-images.githubusercontent.com/1995161/101820965-468d5c80-3af5-11eb-9cd9-052b298f0653.png">
In this picture you can see that the top right corner needs to be lowered and the bottom right corner needs to be raised, however in the table it is flipped.

**Comment by jneilliii** [comment]
On the Current Mesh Data tab in settings check the box for descending y axis?

**Comment by holocronology** [comment]
Most people are, I would guess, looking at their bed from the front with the 0,0 (front-left) corner closest to them. So, at the least, the table should have 0,0 in the lower left view on the screen, rather than at the upper left.

**Comment by jneilliii** [comment]
I will make the descending y default to enabled.
