### ISSUE TITLE
[BUG]:  Bed not storing values after running

### ISSUE THREAD

**Issue by Sllarsen** [jneilliii/OctoPrint-BedLevelVisualizer#334]
I ran the level and the mesh is not stored neither is the graph of the points. No error message is generated. It worked once and then bugged out. So far I've tried rebooting several times. It is stuck on  "Please wait, retrieving current mesh."

**Comment by jneilliii** [comment]
Enable debug logging, restart OctoPrint, and then try again. Then provide the file plugin_bedlevelvisualizer_debug.log file here for examination.
