### ISSUE TITLE
[FR]: Help for Ajustment Angle Table Functionality

### ISSUE THREAD

**Issue by holocronology** [jneilliii/OctoPrint-BedLevelVisualizer#335]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Expanded help describing the features and functionality of the Adjustment Angle table. For example, what does clicking on a cell and setting it to zero accomplish.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by ceshop-nick** [comment]
Thanks for this.  I didn't even know you could do that.  It sets the point to be the origin point and all other points relative to that from what I see.
