### ISSUE TITLE
[BUG]: Probing Failure - Needs to run auto home before probing

### ISSUE THREAD

**Issue by eblieb** [jneilliii/OctoPrint-BedLevelVisualizer#338]
Been having issues with this plugin and my Ender 3 V2 with a BLTouch. If I don't run an auto home before running the bed leveling via this plugin then I will always get a probe failure. Please add the option to auto home before probing.

**Comment by jneilliii** [comment]
Just add the G28 command to the beginning of your gcode script. 

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/blob/master/wiki/gcode-examples.md
