### ISSUE TITLE
Fixed Y scale on graph

### ISSUE THREAD

**Issue by token47** [jneilliii/OctoPrint-BedLevelVisualizer#34]
Hi!

I noticed that as I try to level the bed, the inclination on screen always stays the same, and what changes is the scale on the Y axis. This is technically correct, but is hard to work with. It would be better if the scale was fixed and you could see the plane changing inclination on the screen until it's horizontal. I suggest a fixed scale of 2mm as a starting point. If my bed is more dis-aligned than that, I wouldn't mind to see parts of graph off screen anyway.

This plugin is awsome, keep up the good work!

**Comment by jneilliii** [comment]
That kind of falls under the changes for #28.

**Comment by token47** [comment]
Ok, I'll close this one and comment on that one.
