### ISSUE TITLE
[FR]: Default Z axis scale

### ISSUE THREAD

**Issue by AcJoker2** [jneilliii/OctoPrint-BedLevelVisualizer#342]
Hi,

as I can see, the Z axis is always scaled to -2 to + 2mm.
A bed will never have such deviations.
Therefore, in my opinion, it would make sense to adapt the default values to e.g. -0.3 to + 0.3.
That is still a lot, but it should fit most users and still clearly show the warps of the bed.

Otherwise a good addon and thanks for the work

Best regards
Markus

**Comment by jneilliii** [comment]
Look at the settings, you can change the z heights of the grid, have fun.

**Comment by AcJoker2** [comment]
That's clear, I said that myself.
My suggestion was to add this nonsensical DEFAULT value to e.g. -0.3 to + 0.3mm.
Or you can make the Z axis dynamic so that it is always scaled to Min / Max.

**Comment by jneilliii** [comment]
If the default starts that low then people get initial graphs with meshes that get clipped, which is even more non sensical for first time users.
