### ISSUE TITLE
[FR]: Add auto home prior to bed leveling

### ISSUE THREAD

**Issue by wlwatkins** [jneilliii/OctoPrint-BedLevelVisualizer#346]
**Is your feature request related to a problem? Please describe.**
Sometimes when I do an auto levelling after a print failed, I forget to do an auto home first. I only realise this at the end of the levelling when the y-axis crashes. 

**Describe the solution you'd like**
Maybe add a tick box to do an auto home prior to the levelling next to the "update" button 

**Describe alternatives you've considered**
apart from cancelling the auto level and do the auto home, i don't see other solutions

**Additional context**
I'm using a CR 10 if that helps

**Comment by jneilliii** [comment]
Every one of the examples for gcode settings in the plugin includes that as part of the gcode. You just need to add it there.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/blob/master/wiki/gcode-examples.md
