### ISSUE TITLE
[FR]: Add shortlink to plugin settings

### ISSUE THREAD

**Issue by Sonnenwerk** [jneilliii/OctoPrint-BedLevelVisualizer#349]
**Is your feature request related to a problem? Please describe.**

As a user 
i would like to have a direct link to the plugin settings
so that i don´t have to navigate to octoprint settings->plugins->search for bed leveling-> settings..
and can use a short way to optimize my setup.

**Additional context**

![image](https://user-images.githubusercontent.com/28840367/103443545-8f51b480-4c60-11eb-86c7-1269731a2d03.png)

**Comment by jneilliii** [comment]
Just added version 1.0.1rc2 that adds a small button to take you straight to settings. Will be included in the next release. If you want to test you can change the Release Channel for the plugin to Release Candidate in Octoprint's Software Update settings (assuming OctoPrint 1.5.0+).
