### ISSUE TITLE
Help with Data Collection flag?

### ISSUE THREAD

**Issue by bluemeane** [jneilliii/OctoPrint-BedLevelVisualizer#35]
What would I use here for a Prusa i3 MK3? And would I need to add custom code before, and after my G29?

**Comment by jneilliii** [comment]
Prusa Firmware uses G80 to run auto-leveling and G81 to report the mesh data.  So you would use:

```
G80
G81
```

Set your data collector flag to:

```
Measured points:
```

And check the box for Prusa firmware in settings.
