### ISSUE TITLE
[BUG]: mesh data with points with more than single digits doesn't collect data.

### ISSUE THREAD

**Issue by jneilliii** [jneilliii/OctoPrint-BedLevelVisualizer#352]
**Describe the bug**
Using the Snapmaker the mesh report returns points larger that 9 (ie, 10+) and the regex doesn't extract the points properly.

**Expected behavior**
To red the mesh as valid numbers and graph the data.

See this discussion on the forum.

https://community.octoprint.org/t/bedvisualizer-and-snapmaler-2-0/28407?u=jneilliii

**Comment by jneilliii** [comment]
I think this is fixed in 1.0.1rc1 release.

**Comment by srvoets** [comment]
Ok so I'm no longer timing out. And don't get errors. But there's no mesh visible with the RC release. Just the graph.

**Comment by jneilliii** [comment]
Enable the option to use relative z offset and that will bring the mesh down into view. Or change the z graph limits to `auto,auto`.
