### ISSUE TITLE
[BUG]: Bed Level visualizer not "installing"

### ISSUE THREAD

**Issue by nfons** [jneilliii/OctoPrint-BedLevelVisualizer#359]
**Describe the bug**

when installing the app, it "installs"

But does not seem to actually register with octopi:
```


Successfully uninstalled Bed-Visualizer-1.0.0
Successfully installed Bed-Visualizer-1.0.0
Done!

```

in the restart popup, we see the name being unknown:

![image](https://user-images.githubusercontent.com/882236/105038657-9a149380-5a2d-11eb-8d91-6ba156b95d9c.png)

once restarted, the bed level is not in the installed plugin list

**Expected behavior**

**Debug Log**

**Screenshots**

**Firmware and Version**
latest 1.5+

**Comment by jneilliii** [comment]
Python 3? If so read known issues in the readme for a fix.

**Comment by nicojako** [comment]
Have the same Problem.
![image](https://user-images.githubusercontent.com/76476988/105095176-a3414700-5aa5-11eb-81c7-a5d4d6d8de0a.png)

**Comment by jneilliii** [comment]
Probably the same will fix it for you... @nicojako  see the first item listed here in known issues...

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer#known-issues

**Comment by MelvinSnijders** [comment]
Same issue, even after installing libatlas3-base

**Comment by nicojako** [comment]
Install python 3

**Comment by MelvinSnijders** [comment]
Can I just install python 3 via the SSH through apt? Do I have to configure anything else?

**Comment by jneilliii** [comment]
Easiest way to install python 3 is to use the upgrade script. https://github.com/cp2004/Octoprint-Upgrade-To-Py3

**Comment by nfons** [comment]
This worked with the update script @jneilliii posted

**Comment by o-nix** [comment]
Seems my board has Wi-Fi connection issues, so `numpy` installation was broken. In my case, this was leading to repeated "silent" plugin failures after "successful" (as `numpy` was, technically, present) installation reports.
I did `~/oprint/bin/pip uninstall numpy bed-visualizer`, restarted, and reinstalled the plugin via OctoPrint's manager.
