### ISSUE TITLE
TypeError: Plotly.react is not a function

### ISSUE THREAD

**Issue by akurz42** [jneilliii/OctoPrint-BedLevelVisualizer#36]
Hi,

I'm getting the above error when I go to the Bed Visualizer page. In settings things look allright and I even get stored mesh date. I'm using Bilinear Leveling on Marlin 1.1.8.

Stored Mesh Data:
+0.103	-0.005	-0.010	+0.108
+0.095	-0.027	+0.048	+0.205
+0.075	+0.070	+0.118	+0.210
+0.048	+0.172	+0.162	+0.095

**Comment by guarnacciaa** [comment]
I'm getting the same error.

**Comment by jneilliii** [comment]
This error is due to a conflict with the tempsgraph plugin. There will be a new version of it released soon to resolve this.
