### ISSUE TITLE
[BUG]: every time I hit update mesh it goes to home touches twice and just sits there

### ISSUE THREAD

**Issue by midget1960** [jneilliii/OctoPrint-BedLevelVisualizer#362]
**Describe the bug**

**Expected behavior**

**Debug Log**

**Screenshots**

**Firmware and Version**

**Comment by jneilliii** [comment]
I can't help you unless you fill in the template...

**Comment by midget1960** [comment]
Sorry I have bltouch v 3.1 using octoprint I have 
G29 
M155 S30
@BEDLEVELVISUALIZER
G29 T
M155 S3
And when I hit update mesh it goes to home touches twice and just sits there it won’t continue on and do the bed level I tried clearing data and rebooting octoprint and it still does the same thing when I go to my ender 3 pro with the skr mini v1.2 board and hit level bed it go’s through the hole process just fine.

**Comment by midget1960** [comment]
I have it figured out so it’s working thanks

**Comment by jneilliii** [comment]
Yeah, you had the flag in the wrong spot. Glad you got it worked out.
