### ISSUE TITLE
[BUG]: How does Bed Level Visualizer determine how high/low the bed should be overall?

### ISSUE THREAD

**Issue by JohnClementine** [jneilliii/OctoPrint-BedLevelVisualizer#371]
Hello,
I'm running the latest Marlin nightly.
Bed Level Visualizer used to work great for me. It still works, however recently I've run into an issue where it's telling me I need to lower my top left corner by a full half-turn even though it is lowered as far as it can go and I physically cannot turn the screw anymore.
This was working fine for me last week, since then I've updated my marlin and changed a bunch of configs. I went through a period of re-leveling where it had me bring the bed down significantly in all four corners, even though it was showing as perfectly level before.

What firmware property does Bed Level Visualizer use to determine what should be considered the correct bed height? Theoretically I should be able to bring my bed up on all corners and decrease my z probe offset and it should work fine, but I'm not sure what configuration I need to change for it to recognize that higher bed as correctly leveled instead of having it tell me that I need to lower my whole bed

Thanks in advance for any advice!

**Comment by jneilliii** [comment]
The plugin just visualizes what it's given from the firmware, so it all boils down to what type of leveling and if you're using a probe or not. If you are using a probe, like a BLTouch, it doesn't matter if the springs are let out a little and you level on that. There is an option in the settings to use relative z offset, which will basically use the lowest point reported as "0" and all the offsets from there will be reported in the positive direction. It might be helpful in your situation.
