### ISSUE TITLE
Multiple mesh support [FR]: 

### ISSUE THREAD

**Issue by jghake** [jneilliii/OctoPrint-BedLevelVisualizer#375]
It would be super handy if there was an option to choose which mesh slot you wanted to use when clicking update mesh!!!

**Comment by jneilliii** [comment]
You could technically do this with the custom command options. You would just put in the same gcode with the necessary changes to select a different mesh.

**Comment by jneilliii** [comment]
For example, the following command could allow you to graph the individual slots, assuming UBL.

![image](https://user-images.githubusercontent.com/5249455/106692478-8d9e4800-65a2-11eb-8f01-1dd367e50093.png)
