### ISSUE TITLE
Changing the size of the mesh and probing points

### ISSUE THREAD

**Issue by Harry1266** [jneilliii/OctoPrint-BedLevelVisualizer#378]
Hi,

i'm using smith3d firmware with my Ender 3 V2 together with bed visualizer.
Can i change the mesh size and the count of probing points?
smith3d uses a 5x5 mesh with a size of only 150x200

Thanks

**Comment by jneilliii** [comment]
the actual probing points are based on what is possible in the firmware. If you can define the number of points probed via gcode commands, then you can use that in the plugin's settings to probe more points. Smith3D I believe is just a pre-compiled Marlin fork, so you might be able to find out if that is possible at the link below.

https://marlinfw.org/docs/gcode/G029.html
