### ISSUE TITLE
[0.0.8] TypeError: Plotly.react is not a function

### ISSUE THREAD

**Issue by Zwaubel** [jneilliii/OctoPrint-BedLevelVisualizer#38]
Hey,
I'm getting the following error message, when trying to use your plugin:
TypeError: Plotly.react is not a function

This is the serial output through the OctoPrint terminal:

Recv: Bilinear Leveling Grid:
Recv:       0      1      2      3
Recv:  0 -0.102 -0.046 +0.053 +0.138
Recv:  1 -0.132 -0.047 +0.036 +0.127
Recv:  2 -0.194 -0.105 -0.010 +0.106
Recv:  3 -0.295 -0.200 -0.096 +0.032

I'm running the latest Marlin Firmware from the bugfix-2.0.x branch on a cartesian printer.
The Data Collector Flag has been set to "Bilinear Leveling Grid:" and I'm using your suggested GCODE:

M155 S30
G28
G29 T1
M155 S3 

Data collection seem to work just fine, as the acquired data in the settings tab of your plugin shows exactly what is displayed in the terminal.

I haven't been looking through your code but the error message to seems to be some what related to a typo or am I using just to few probing points?

**Comment by jneilliii** [comment]
There have been several issues posted on this. There is a conflict with the tempsgraph plugin with a new release from that author coming soon.
