### ISSUE TITLE
Seems to be displaying values that are flipped on the Y-axis

### ISSUE THREAD

**Issue by Zer0t3ch** [jneilliii/OctoPrint-BedLevelVisualizer#40]
I'm on my [personal fork](https://github.com/Zer0t3ch/Marlin) of the Marlin bugfix-2.0.x branch using UBL. The default branch of my repo is what I'm compiling right now, so you can have a look there if you need to see my Marlin configuration headers.

![2018-04-25 09_09_55-octoprint](https://user-images.githubusercontent.com/1359291/39251342-a0513e8a-4868-11e8-8067-23bf74432bd4.png)
![2018-04-25 09_10_11-octoprint](https://user-images.githubusercontent.com/1359291/39251343-a067fdbe-4868-11e8-91c1-db6c413471d5.png)

As you can see, terminal is showing (0,0) should be 0.387, but the visualizer is showing 0.312, which should be the value of (0,3).

**Comment by jneilliii** [comment]
Thanks for this information.  No-one has reported on the axis order yet.  I was concerned it would be flipped for some. I'll review for my next set of revisions related to #28.

**Comment by Zer0t3ch** [comment]
Thanks for the response.

As an arbitrary suggestion: how plausible would it be to implement some simple "flip x" and "flip y" options? If there's ever any more issues for anyone in the future, they'll at least have a functional stop-gap solution.

**Comment by Zer0t3ch** [comment]
@jneilliii 

Note: the output format seems to have recently changed in the 2.0.x branch. Here's my current output for reference:

![image](https://user-images.githubusercontent.com/1359291/39309426-8e04c01a-492d-11e8-850f-7cf231aa3d0a.png)

and it spawns this error:

![image](https://user-images.githubusercontent.com/1359291/39312918-4a8c2ee6-4936-11e8-911e-19b14ca79760.png)

But if I do `G29 T1`, (CSV output) I get this

![image](https://user-images.githubusercontent.com/1359291/39312886-39b6e64c-4936-11e8-866c-921c63938b93.png)
 and the bed visualizer tab loads forever.

I'm not sure if the `T1`/CSV support is in the stable branch, but if it is, I would suggest you default to retrieving and parsing that, as it's designed to be parsed by computers.

**EDIT - Digging into the code, it seems that Marlin is now using tab spacing in CSV output. For now, I adjusted my code to go back to using commas (I can share a patch file if anyone else is having this issue for now) but it should only take a small tweak for the visualizer to parse that.

**Comment by jneilliii** [comment]
I just pushed a commit to the 0.0.9 branch with the Flip X/Y axis options.  I also updated the collector regular expression, which will probably break delta printer output, but would work for the 2.0.x report that you posted before in theory.  You can test by installing with the below url in plugin manager.  Make sure to CTRL+F5 afterwards just to make sure the page is refreshed.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.0.9.zip

**Comment by Zer0t3ch** [comment]
Seems to be working as expected. (for both the tabbed-CSV output and flipping) Thank you.

Do you intend to debug/fix the flipped mesh data issue directly, or is the manual flipping configuration your long-term solution? (wasn't sure if I should close the issue or not)

**Comment by jneilliii** [comment]
I think this will be the long term solution.  There are too many variables when dealing with the different firmware and how they report the mesh data.
