### ISSUE TITLE
[FR]: Get Report from Manual Leveling via LCD

### ISSUE THREAD

**Issue by tibmeister** [jneilliii/OctoPrint-BedLevelVisualizer#402]
Update to gcode-examples.md

To retrieve the values stored in the EEPROM, in cases where manual leveling is done via the LCD, for Marlin 2.x the following GCODE will do the trick:

@BEDLEVELVISUALIZER	; tell the plugin to watch for reported mesh
G29 S0	   ; Get Report

**Comment by jneilliii** [comment]
Couldn't you also use `M420 V`?
