### ISSUE TITLE
Duet output to console

### ISSUE THREAD

**Issue by sweets9** [jneilliii/OctoPrint-BedLevelVisualizer#404]
Board: Duet 2 WiFi (2WiFi)
Firmware: RepRapFirmware for Duet 2 WiFi/Ethernet 3.2 (2021-01-05)

I have spent a few hours going through the documentation / wiki and reading through the gcode but cannot find a way to get my Duet board to output G29 data to terminal for BLV.  Is there a debug mode or something that I am missing. G29 maps are created into a CSV file but are not outputted to console. (heatmap in Duet Web Control works but I am trying to use Octoprint as much as possible)

Any help appreciated. Thanks.

**Comment by jneilliii** [comment]
If the firmware doesn't report it over the serial connection then there is no possible way that I can graph that data.
