### ISSUE TITLE
[FR]: cannot see the recommended correcting rotations on iPhone (iPhone browsers do not have hover mouse facility)

### ISSUE THREAD

**Issue by hitmusic100** [jneilliii/OctoPrint-BedLevelVisualizer#413]
**Is your feature request related to a problem? Please describe.**

no
**Describe the solution you'd like**

if possible, have an option to eliminate the need to hover over the wheel correction, so that I can see the corrections on Iphone 
**Describe alternatives you've considered**

none
**Additional context**

**Comment by jneilliii** [comment]
kind of duplicate of #336 let's keep that one.
