### ISSUE TITLE
Printrbot simple metal settings

### ISSUE THREAD

**Issue by M-Barrows** [jneilliii/OctoPrint-BedLevelVisualizer#42]
I cant seem to find the right settings for my Printrbot Simple Metal printer. I've included screenshots of my settings and console output. I've been able to find the right settings for the Prusa i3 MK3 with the help of these issue posts so I'm hoping to have some luck with the Printrbot. I've included screenshots of the settings I'm currently using (although I've tried all of the data collector flag options). Thanks in advance! 

<img width="726" alt="bedvisualizersettings" src="https://user-images.githubusercontent.com/7907749/39310367-322cd2c2-4938-11e8-9d45-61a126d062d5.png">
<img width="597" alt="console output" src="https://user-images.githubusercontent.com/7907749/39310366-321d0356-4938-11e8-86a6-0fd02c8ba858.png">

**Comment by jneilliii** [comment]
Unfortunately, the plugin does not currently know how to interpret this format of report.  What do you get if you just send the command `G29 T`? Do you know what firmware the Printrbot Simple Metal uses?

**Comment by M-Barrows** [comment]
Hi @jneilliii, thanks for your quick response. The `G29 T` command yields the same output as my screenshot above. If I run the `M115` command to print firmware version, I get the following: 

`M115Recv: FIRMWARE_NAME:Marlin V1; Sprinter/grbl mashup for gen6 FIRMWARE_URL:http://printrbot.com PROTOCOL_VERSION:1.0 MACHINE_TYPE:Printrbot EXTRUDER_COUNT:1 UUID:00000000-0000-0000-0000-000000000000`

I love this addon for the MK3 and look forward to seeing it implemented on the Printrbot :)

**Comment by jneilliii** [comment]
What about if you enter `M420 V`?

**Comment by M-Barrows** [comment]
`M420 V` and `M420` just returns a `Recv: ok` result. I've tried running `G29 V4` as well and that gives the same output as my original screenshot. If it helps, I'm operating with the Marlin list of GCodes [here.](http://reprap.org/wiki/G-code#M420:_Leveling_On.2FOff.2FFade_.28Marlin.29)

**Comment by jneilliii** [comment]
My only guess here is that the version of Marlin on your printer is so old (looks like a printrbot specific fork) that the report is not going to work with this plugin.  That is unless the report from the type of leveling configured in the firmware just reports that way in all Marlin's but no-one else has reported it that I remember.

**Comment by jslay88** [comment]
@MBarrows20 I'd suggest updating the firmware on your printer to 1.1.8

See here for more info on your printer.
http://www.printrbottalk.com/forum/viewtopic.php?f=115&t=11462

**Comment by M-Barrows** [comment]
Unfortunately I've left the organization with this printer before I was able to try the firmware update. I hope this thread will help someone in the future but feel free to mark the issue as closed if you wish.
