### ISSUE TITLE
[FR]: Add Settings Option for Locale to use when Date, Time is shown

### ISSUE THREAD

**Issue by planetar** [jneilliii/OctoPrint-BedLevelVisualizer#427]
Please add an option to the settings of the plugin to select and add a locale used for formatting the fate and time shown under the mesh visualization.

The plugin shows the bed visualization and below has the line of text: Using saved mesh data from 
followed by a date/time string. That string is formatted on line 191
like new Date().toLocaleString()

For some users this renders like  new Date().toLocaleString("en-US") regardless of the locale settings of their OS or browser. 

Besides, even if toLocaleString() worked like it was expected to do it would still rely on the assumption that the language version of the browser represents the locale the current user prefers Which may or may not be the case. Think of a user in Ireland, en-IE who installed the 'English' version of the browser and now gets en-US

There is no reliable way to determine a user's preferred language or date format without asking them. 

As a test I modified the code of bedlevelvisualizer.js on my octopi system at line 191, inserting "de-DE"  for toLocaleString("de-DE")
This gave me the intended date format.

I suggest an input field on the settings dialog which allows users to type in the preferred locale, followed by a test if that is a correct and supported locale, and, if so, use that as a parameter in line 191

**Comment by jneilliii** [comment]
available as part of version 1.1.0.
