### ISSUE TITLE
[BUG]: Y axis displays two values.

### ISSUE THREAD

**Issue by twild1990** [jneilliii/OctoPrint-BedLevelVisualizer#431]
**Describe the bug**

Y axis values display two values at once.
**Expected behavior**

I would expect the visualizer to list 0 , 115, 230

I should also mention the my ABL seems to skew to the left side of my print bed but I think this is a marlin config issue.
**Debug Log**

[octoprint-logs(1).zip](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/6481825/octoprint-logs.1.zip)

**Screenshots**

![image](https://user-images.githubusercontent.com/1694520/118346270-2d576480-b508-11eb-8388-552ebc47baa7.png)

**Firmware and Version**

Marlin 2.0.x-bugfix

**Comment by jneilliii** [comment]
double check your printer profile inside octoprint. I think you have your rectangular dimensions wrong. notice the y max is wrong.

```
{'type': 'rectangular', 'x_min': 0, 'x_max': 220.0, 'y_min': 0, 'y_max': 200220.0, 'z_min': 0, 'z_max': 250.0}
```

**Comment by twild1990** [comment]
Thank you. This corrected the issue. You've made my day that much better!
