### ISSUE TITLE
Can't get the plugin to work

### ISSUE THREAD

**Issue by ShinSnap** [jneilliii/OctoPrint-BedLevelVisualizer#44]
I receive an error when I first open the Bed Visualizer plugin.

"TypeError: Cannot read property 'length' of undefined"

![image](https://user-images.githubusercontent.com/29789787/39336150-de5752fc-496a-11e8-8cef-d9994fc6a768.png)

Data Collection Flag: 
`Measured points:`

Gcode Commands:
`G28
G29 T`

Save Mesh
`Checked`

Check I click update. All I get is, but it doesn't do anything
`Please wait, retrieving current mesh.`

When I check the logs G28 and G29 T responds with `OK` almost immediately. 

I am also on Marlin 1.1.1

**Comment by jneilliii** [comment]
Please share a screenshot of your settings and the output of manually sending command `G29 T`

**Comment by ShinSnap** [comment]
![image](https://user-images.githubusercontent.com/29789787/39337568-90c75a70-4972-11e8-8365-fe4d4820eca7.png)

![image](https://user-images.githubusercontent.com/29789787/39337599-acb7be46-4972-11e8-8a36-3a9d259e4432.png)

**Comment by jneilliii** [comment]
Are you sure you have auto bed leveling enabled? The fact the G29 T command doesn't return anything at all in terminal is suspicious.

**Comment by onlyhuman91** [comment]
I am also seeing this same error message now, but I wasn't last week. Was there an update recently?

**Comment by jneilliii** [comment]
The original 0.0.8 release had a bug that I resolved and pushed back to the same version number.  If you uninstall and reinstall the issue should be resolved for you, unless you're having the same problem as @ShinSnap where his command is not returning any data.

**Comment by jneilliii** [comment]
I have pushed a new branch that should help a ton in data collection related issues., as long as your GCODE commands are set properly for retrieving a report of some nature.  It eliminates entirely the necessity of a data collector flag.  Install from the URL below and let me know if you are still getting the errors, and if it works for you at all.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.1.0.zip
