### ISSUE TITLE
You must be logged in

### ISSUE THREAD

**Issue by TimmyOl** [jneilliii/OctoPrint-BedLevelVisualizer#441]
I've never succeded in getting this to work but i really want to, i get the "You must be logged in" with a warning triangle, logged in to what? and how do i log in?

It doesn't get any mesh and my guess is that this is the reason since i have the gcode set up? as soon as i click the bed visualizer button it just tries to get a mesh but doesn't run the gcode and below it says: " You must be logged in.
In order for this plugin to work properly, you must configure the GCODE commands necessary to send back a Bed Topography Report in Settings."

below that there is 2 buttons that doesn't do anything, one with an "i" and one with a cog i guess should take me to the settings page?

**Comment by jneilliii** [comment]
Enable debug logging, restart OctoPrint, try again. Once it fails (assuming it does) then grab the files octoprint.log and plugin_bedlevelvisualizer_debug.log from the logging section of OctoPrint and drag them into a comment here to upload. Also please share the gcode settings you are using, the firmware variant and version, and Auto Bed Leveling type configured in your firmware.

**Comment by TimmyOl** [comment]
> Enable debug logging, restart OctoPrint, try again. Once it fails (assuming it does) then grab the files octoprint.log and plugin_bedlevelvisualizer_debug.log from the logging section of OctoPrint and drag them into a comment here to upload. Also please share the gcode settings you are using, the firmware variant and version, and Auto Bed Leveling type configured in your firmware.

Okej, but No it doesnt fail, just spinning the wheel and "Please wait, retrieving mest"
![IMG_20210528_235914](https://user-images.githubusercontent.com/45720464/120045653-cdd17c80-c010-11eb-9c64-9d10675a96c1.jpg)

Sorry for the bad image, ill check for the logs tomorrow

**Comment by jneilliii** [comment]
that looks strange to me, the logs, as well as check the developer tools (F12) in your browser and look for any red errors on the console tab on initial page load and while it's doing that process. The above looks like a broken UI, and there could be a conflict with another plugin as well. also share a screenshot of your gcode commands you're using for reference as well.
