### ISSUE TITLE
[BUG]: When bed probing is interrupted, visualizer fails.

### ISSUE THREAD

**Issue by unkwntech** [jneilliii/OctoPrint-BedLevelVisualizer#444]
**Describe the bug**
When a user initiates a mesh update, if the printer fails to update the mesh the visualizer never completes and cannot be reset until after a restart of octoprint.

**Expected behavior**
When a printer disconnects or is put into an error state the mesh update should be abandon, and user should be able to attempt the update again once the error state is cleared.

**Firmware and Version**
This was observed in Bed Visualizer 1.0.1

**Reproduction Steps**
Start a mesh update and disconnect the printer, or force it into an error state (such as triggering the leveling sensor early on the first probe)

**Comment by jneilliii** [comment]
you can press the button again to cancel the collection process or wait for the timeout to occur based on the plugin's settings.
