### ISSUE TITLE
[BUG]: Restricted user has access to all settings

### ISSUE THREAD

**Issue by Danafra** [jneilliii/OctoPrint-BedLevelVisualizer#445]
Normally, a user added in Octoprint as in "Operator" does not have access to Octoprint's settings. However, if the user access's the settings for Bed Visualizer, they have access to all settings.

This is using Bed Visualizer 1.0.1 and Octoprint 1.6.1.

![image](https://user-images.githubusercontent.com/32659658/121176379-26cbbc80-c82a-11eb-9554-bcff233e84a2.png)
![image](https://user-images.githubusercontent.com/32659658/121176390-2a5f4380-c82a-11eb-894a-6a18ff95a60c.png)
![image](https://user-images.githubusercontent.com/32659658/121176411-2df2ca80-c82a-11eb-82e6-7a851b90da63.png)

**Comment by jneilliii** [comment]
Quick question, that allows them to open the settings, but are they allowed to save changes? If so that almost seems like a higher end bug that should be reported to core OctoPrint as well. I will definitely adjust this plugin to not show the button unless the user has the proper permissions.

**Comment by jneilliii** [comment]
fixed by above commit and will be included in the next release.
