### ISSUE TITLE
[FR]: Mini FR for add a button reload from marlin

### ISSUE THREAD

**Issue by devildant** [jneilliii/OctoPrint-BedLevelVisualizer#452]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
add native button (no custom)  for force refresh visual mesh from marlin data
example : 
![image](https://user-images.githubusercontent.com/8700106/126881823-59dffc6d-4486-4bfb-b6c8-b43f1d4aa05f.png)

gcode: 
@BEDLEVELVISUALIZER
M420 V1

nb: not enable during print or mesh

**Describe alternatives you've considered**
presently i using custom button for that, but it's can useful for another users :)

**Additional context**
no

**Comment by jneilliii** [comment]
I would consider that if all versions of firmware/leveling type supported storing mesh data. That is the reason I added the custom button options originally anyway. It's possible to all kinds of things with them. 

![image](https://user-images.githubusercontent.com/5249455/126887546-78dc5c29-92ad-4a85-a095-9fa2fdafce77.png)
