### ISSUE TITLE
[BUG]: Settings do not save after server reboot

### ISSUE THREAD

**Issue by DigiVore-Programing** [jneilliii/OctoPrint-BedLevelVisualizer#456]
**Describe the bug**
When you change corrections settings, they do not persist after a server / system reboot

**Expected behavior**
All settings staying after any number of reboots or system reboots. 

**Debug Log**
File empty...

**Screenshots**
![image](https://user-images.githubusercontent.com/38924918/129116695-1b45e1f2-1801-4204-9f3e-aaa36479a450.png)

**Firmware and Version**
Marlin v2.x.x bugfix (unsure date of bugfix, planning on moving to release Marlin soon.)

**Comment by jneilliii** [comment]
could you please enable debut logging in the plugin's settings, restart octoprint, and test again. Then the plugin_bedlevelvisualizer_debug.log file won't be empty. However, I think this might be a front-end UI issue. Could you open your browser's developer tools (F12) and on the console tab look for any red text/errors on initial page load, or when opening the settings.

**Comment by DigiVore-Programing** [comment]
Nope. Still empty.

Hayden, Hayden Fixes <http://haydenfixes.jordanmccollum.com>
Repairing iPhones and computers since 2017

**Comment by DigiVore-Programing** [comment]
However, it did not clear my settings this time.
Hayden, Hayden Fixes <http://haydenfixes.jordanmccollum.com>
Repairing iPhones and computers since 2017
