### ISSUE TITLE
[FR] Ender 3 Max bed visualiser not working, any suggestions?

### ISSUE THREAD

**Issue by Bolvulcan-Mining** [jneilliii/OctoPrint-BedLevelVisualizer#460]
BL Touch with Ender 3 Max will not upload the bed visualizer, I have tried multiple softwares from Creality and Marlin pre-builds. 4.2.2 board.

Is there any software you'd reccomend? It did work for a while until the software was changed. I have attached below the current Terminal output after reading other peoples issues. 
![Screenshot (232)](https://user-images.githubusercontent.com/89110545/129816086-2fe7fdc9-39da-4249-baee-c19f77fde7c1.png)

Recv:   TT::25.4525.45  //0.000.00  BB::64.8364.83  //65.0065.00  @@::00  BB@@::125125
Recv: 
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: X:99.50 Y:161.00 Z:10.40 E:0.00 Count X:7960 Y:12880 Z:4160
Recv: ok
Send: M155 S30
Recv: ok
Send: M190 S65
Recv: ok
Send: G29 P1
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: Error:Probing Failed
Recv: X:-3.50 Y:41.00 Z:0.00 E:0.00 Count X:-280 Y:3280 Z:0
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: ok
Send: G29 P3
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: Error:Probing Failed
Recv: X:-3.50 Y:41.00 Z:0.00 E:0.00 Count X:-280 Y:3280 Z:0
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: ok
Send: G29 P3
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv:   TT::25.5425.54  //0.000.00  BB::65.3465.34  //65.0065.00  @@::00  BB@@::00
Recv: 
Recv: Error:Probing Failed
Recv: X:-3.50 Y:41.00 Z:0.00 E:0.00 Count X:-280 Y:3280 Z:0
Recv: echo:busy: processing
Recv: echo:busy: processing
Recv: ok
Send: M420 S1 V
Recv: Bilinear Leveling Grid:
Recv:       0      1      2
Recv:  0 +0.949 -0.550  =====
Recv:  1  =====  =====  =====
Recv:  2  =====  =====  =====
Recv: 
Recv: echo:Bed Leveling ON
Recv: echo:Fade Height OFF
Recv: X:150.00 Y:150.00 Z:0.00 E:0.00 Count X:12000 Y:12000 Z:0
Recv: ok
Send: M500
Recv: ok
Send: M155 S3
Recv: ok
Recv:   TT::25.5425.54  //0.000.00  BB::65.1765.17  //65.0065.00  @@::00  BB@@::00
Recv: 
Recv:   TT::25.5725.57  //0.000.00  BB::64.9464.94  //65.0065.00  @@::00  BB@@::2929
Recv: 
Recv:   TT::25.5125.51  //0.000.00  BB::64.7864.78  //65.0065.00  @@::00  BB@@::8888
Recv: 
Recv:   TT::25.4525.45  //0.000.00  BB::64.7664.76  //65.0065.00  @@::00  BB@@::122122
Recv:

**Comment by jneilliii** [comment]
```
Recv: Bilinear Leveling Grid:
Recv: 0 1 2
Recv: 0 +0.949 -0.550 =====
Recv: 1 ===== ===== =====
Recv: 2 ===== ===== =====
```

There's something wrong here in the return information from your firmware you currently have installed on the printer. For whatever reason it's not returning all the necessary points. Since I don't have your printer model/board combination I wouldn't venture to say which is a good alternative, I only have knowledge of InsanityAutomation, jyers, and smith3d to be known working firmwares, otherwise I would just compile default Marlin myself using the example configs.
