### ISSUE TITLE
Adjustable Window frame request

### ISSUE THREAD

**Issue by Lumanet2012** [jneilliii/OctoPrint-BedLevelVisualizer#462]
Currently the Plugin has a height limitation of what can be seen by default. 
It would be nice to have a field Bed Visualizer Settings --> Visualization where you define also the height of the plugin. 
The reason given is by default the graph window adjust to the width automatically but on the height it cut's off the graph and there for it is not fully visable and forces it to be way to small on a bigger display. 
To date a lot of people have widescreens so it would be a nice feature if we can add this field.

**Comment by jneilliii** [comment]
Added with above commit, you can change the plugin's release channel to `Release Candidate` in OctoPrint's software update settings and upgrade when prompted. 

![image](https://user-images.githubusercontent.com/5249455/131051069-55a3c0b7-d020-496a-9389-db327c9f7b98.png)
