### ISSUE TITLE
Conflict with Gcode Macros (1.1.0)

### ISSUE THREAD

**Issue by jp-001** [jneilliii/OctoPrint-BedLevelVisualizer#464]
This is just an FYI.
Upon updating to Gcode Macros (1.1.0), Bed Visualizer started showing many of the issues already reported here, such as not completing the leveling operation and not showing the correction matrix.
I have also reported this as a bug for Gcode Macros.

**Comment by jneilliii** [comment]
This could happen if that plugin is eating up the gcode responses. I haven't personally looked at that plugin yet, so would require some feedback from @cp2004 on the issue potentially.

**Comment by jneilliii** [comment]
Closing ticket as my hint to Charlie does seem to have been the issue.
