### ISSUE TITLE
[FR]: Changeable colors of CSS classes .raise and .lower

### ISSUE THREAD

**Issue by electronicm** [jneilliii/OctoPrint-BedLevelVisualizer#468]
**Is your feature request related to a problem? Please describe.**
I use a dark theme and the blue of the CSS class `.raise` is very hard to read, as well as the red of the class `.lower`.

**Describe the solution you'd like**
editable otions for the both classes as colorpicker or textfield for hex/colorname.

**Describe alternatives you've considered**
Right now I'm using some custom css to override your color. `.meshtable .raise { color: #006aff !important; }`

**Additional context**

**Comment by jneilliii** [comment]
Your approach of using the custom/advanced css configurations of whatever UI customization plugin you are using is spot on, and probably the best approach for now, as it's only because of the other plugin that this looks non-optimal.

**Comment by electronicm** [comment]
BTW: I am using UI Customizer with the theme Discorded.

**Comment by jneilliii** [comment]
Yeah, same would work with any theme or themeify. I'm leaning towards just documenting the class names and showing examples of your workaround because the ui is already getting cluttered.
