### ISSUE TITLE
Z-axis limits need work.

### ISSUE THREAD

**Issue by jackbradach** [jneilliii/OctoPrint-BedLevelVisualizer#47]
It looks like the Z-axis limits are set to the min/max of the data set to be drawn.  This has the effect of exaggerating the heightmap.  Check out this data set:

Recv: Bed Topography Report for CSV:
Recv: 
Recv: -0.093,-0.067,0.002,0.033,0.011
Recv: -0.061,-0.019,0.030,0.077,0.039
Recv: -0.031,0.002,0.016,0.053,0.016
Recv: 0.012,-0.022,-0.002,0.008,-0.003
Recv: -0.020,-0.021,-0.019,-0.002,-0.039

Now, that's not going to break a Morty or nothing, but it's still pretty damn level.  Here's the humpity-shlump that BLV told me my bed looked like:

![image](https://user-images.githubusercontent.com/5945181/39411272-aae07dc4-4bbb-11e8-8cdb-f3d8cd265918.png)

Maybe lock the range closer to +/- 0.5 or +/-1?

**Comment by jneilliii** [comment]
This is already being worked on and I'm just awaiting some feedback from #28 for the delta guys to verify it's working for them as well.  If you install from the 0.1.0 branch using the link below in plugin manager you'll see where we're headed.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.1.0.zip

**Comment by jackbradach** [comment]
Dagnabit, I glanced at that one and went "nope, that bug is about Deltas and probably doesn't cover the bug I'm about to file."  Now that I've scrolled down through the whole thing, the new behavior looks awesome.  I'll give it a try, thanks!
