### ISSUE TITLE
[FR]: Auto calculate bed variance

### ISSUE THREAD

**Issue by SirChryse** [jneilliii/OctoPrint-BedLevelVisualizer#470]
**Is your feature request related to a problem? Please describe.**
No it is not

**Describe the solution you'd like**
It would be nice to have something on the graph show the calculated bed variance, even though I learned how to calculate it there are some users who may not know how to calculate it and this would be convenient for them. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by jneilliii** [comment]
Also include min/max values somewhere.

**Comment by jneilliii** [comment]
Implemented in above commit and available in version 1.1.1rc2. Change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and upgrade when prompted if you want to test it out. 

![image](https://user-images.githubusercontent.com/5249455/133911246-ae220abd-46ea-4636-8444-dcd924de5208.png)
