### ISSUE TITLE
[BUG]: no downgrade at release channel change

### ISSUE THREAD

**Issue by electronicm** [jneilliii/OctoPrint-BedLevelVisualizer#472]
**Describe the bug**
When I change the release channel from "Release Candidate" back to "Stable", I do not get a downgrade.
I have to uninstall and reinstall the plug in.

**Expected behavior**
When I change the release channel, as with various other plugins and also OctoPrint itself, the current version of the channel should be installed.

**Comment by jneilliii** [comment]
This should work like the others, Are there any errors in octoprint.log or plugin_bedlevelvisualizer_debug.log file?

**Comment by jneilliii** [comment]
confirmed reproducible

**Comment by jneilliii** [comment]
I believe this to be an upstream bug and have created the above issue in OctoPrint's repo to track.

**Comment by jneilliii** [comment]
Since this appears to be resolved upstream and will be release in the next version of OctoPrint closing issue.
