### ISSUE TITLE
[FR]: Is it possible to change the probing path?

### ISSUE THREAD

**Issue by alexw22** [jneilliii/OctoPrint-BedLevelVisualizer#478]
When probing my bed I notice it is warped in a way that could be related to the probing path of the G29 command. I am adding a picture of the bed probing results below:

<img width="594" alt="Screenshot 2021-10-08 at 00 03 58" src="https://user-images.githubusercontent.com/63752599/136468468-56a57fab-737b-4a68-a3fc-d3ac495b5334.png">

The probing direction right now follows the red arrows:
<img width="594" alt="Screenshot 2021-10-08 at 00 03 58 copy" src="https://user-images.githubusercontent.com/63752599/136468815-e54b2d9d-8be2-412f-a3e6-4fdb4ca5d027.png">

I can't help but wonder if the probing direction to the right (X -> more positive ) might be lowering the BlTouch and probing in the left (X -> more negative) direction is somehow lowering the BlTouch due to some slack in the belts or something like that. Would there be a way to easily change the probing path so that I could test this? For example flipping it 90 degrees like marked with the light blue arrows below so I could test this hypothesis?

<img width="594" alt="Screenshot 2021-10-08 at 00 03 58 copy 2" src="https://user-images.githubusercontent.com/63752599/136469463-3cd21e08-0c3b-4a85-b665-de170f4295a7.png">

**Comment by jneilliii** [comment]
Firmware controls that, I have no control of what your firmware does when probing. This plugin only visualizes the points returned by the firmware to graph.
