### ISSUE TITLE
[FR]: Change Min/Max Text Color

### ISSUE THREAD

**Issue by jsdokos** [jneilliii/OctoPrint-BedLevelVisualizer#479]
**Is your feature request related to a problem? Please describe.**
I just updated to the new RC, and I have the themeify plugin enabled to do a dark mode within Octoprint. Since I am unable to change the text color it makes it hard to read within the webpage. There is also no HTML element that I can edit (that I saw) to change the text color.

**Describe the solution you'd like**
Be able to change the text color to white, or white with a black border to enhance readability.

**Describe alternatives you've considered**
I looked into changing it with the themeify plugin it self, but i didn't see any way to do that. I may have missed it

**Additional context**
![image](https://user-images.githubusercontent.com/10056186/136882719-8e35e511-28b6-4462-b499-9c4b40422b82.png)
Themeify Theme - Discorded

**Comment by jneilliii** [comment]
Thanks for pointing this out, didn't think about that during initial creation of the feature (quick through Discord discussions). Will definitely adjust prior to official release.

**Comment by jsdokos** [comment]
Glad to help. I thought about requesting this a few weeks ago. Glad someone read my mind.

**Comment by jneilliii** [comment]
Got this fixed, will push a new rc version shortly.

![image](https://user-images.githubusercontent.com/5249455/147842391-f28a4353-c226-464d-8e98-fb0169be0c44.png)

**Comment by jsdokos** [comment]
Great I'll text it out and report back to you.
