### ISSUE TITLE
Plugin is not compatible with Internet Explorer

### ISSUE THREAD

**Issue by AcHub** [jneilliii/OctoPrint-BedLevelVisualizer#48]
While testing the Plugin with different browsers I realised that it is not working with Internet Explorer. Is that still considered to be a recent browser?

I already had settings stored to the plugin, but with Internet explorer the settings are not read to the settings page.

![settings](https://user-images.githubusercontent.com/10789955/39471665-9d0f105e-4d44-11e8-996e-472b100a20aa.JPG)

It is possible to type in settings and click on "save", and these settings are also displayed if I reopen the settings tab, but they are not actually stored to the config.yaml.

Due to the "missing" (in terms of not present at the browser) configuration, also the plot-view does not work:

![plotscreen](https://user-images.githubusercontent.com/10789955/39471702-def381c6-4d44-11e8-9414-3449cf5b35aa.JPG)

Also it states that I need to be logged, which I was.

**Comment by jneilliii** [comment]
Not sure what issue you are running into here.  I'm able to use Internet Explorer with the plugin with no issues.

![image](https://user-images.githubusercontent.com/5249455/39498527-9d4c76d8-4d76-11e8-9853-f50ae9245a42.png)

The only issue I see is when first loaded in the browser, the Bed Visualizer settings tabs aren't applying, but once you flip to one of the tabs it works itself out. I'm assuming that's a bootstrap bug in IE.

![image](https://user-images.githubusercontent.com/5249455/39498607-1008d0c2-4d77-11e8-982a-6c1d30251b2d.png)

IE does however freeze up if I try to open developer tools to look into the issue, so not sure there's much I can do here.
