### ISSUE TITLE
[BUG]: Uneven Probe Points X to Y Causes Issues With Rendering

### ISSUE THREAD

**Issue by jsdokos** [jneilliii/OctoPrint-BedLevelVisualizer#480]
**Describe the bug**
Bug is in the middle of the columns for the Data tab and Corrections angle (see below)
![image](https://user-images.githubusercontent.com/10056186/136889625-363ff0e3-085a-46d0-8704-9b67b90fb633.png)

**Expected behavior**
Circle should be the last column on the right
[plugin_bedlevelvisualizer_debug.log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/7326834/plugin_bedlevelvisualizer_debug.log)

**Debug Log**

**Screenshots**
![image](https://user-images.githubusercontent.com/10056186/136889698-d87e8104-e16d-4d97-bc71-2afe5c9927d1.png)
![image](https://user-images.githubusercontent.com/10056186/136889756-e73181ef-579c-4fc8-8f55-be9eaba0f1bb.png)

**Firmware and Version**
Marlin 2.0.9.1 - Ender 3

**Comment by jneilliii** [comment]
Ah, you've hit the issue with unequal probing points x to y. It seems your probing grid is 3x4, and the plugin has issues with that currently.

**Comment by jsdokos** [comment]
Yeah, I find it better to be a good mix of speed and data. I had the same probing grid with the Non-RC release, but there were no issues there. I can switch back to see if that is still happening since it was a few weeks ago.

**Comment by jneilliii** [comment]
duplicate of #381
