### ISSUE TITLE
[BUG]: Bed Level Visualizer display Problem with klipper

### ISSUE THREAD

**Issue by trunglp** [jneilliii/OctoPrint-BedLevelVisualizer#481]
**Describe the bug**

I use Bed Level Visualizer , i buy and change two sensor , but my bed leveling not correct.

![image](https://user-images.githubusercontent.com/38026441/136912196-5fbf276d-de3e-41c3-8c51-8f3e38392c85.png)

i use Firmware Klipper . Please help me. 

**Expected behavior**

**Debug Log**

**Screenshots**

**Firmware and Version**

**Comment by jneilliii** [comment]
More than likely you need to use one of the flip options. Place something in the front right corner of your bed so that the probe triggers early in that corner so you can identify the proper orientation.

**Comment by trunglp** [comment]
> More than likely you need to use one of the flip options. Place something in the front right corner of your bed so that the probe triggers early in that corner so you can identify the proper orientation.

Thank you for reply
My problem is resolved. I just check Key-Bak on voron switchwire, and i see Gantry X axis some little bit not correct . after that i tuning and result bed level very well

![image](https://user-images.githubusercontent.com/38026441/137089742-708a55d8-5401-4f71-a905-7ebc43c90fcb.png)
