### ISSUE TITLE
[BUG]: Running Update Mesh causes 'customisation to controls tab' to disappear

### ISSUE THREAD

**Issue by LightningShark25** [jneilliii/OctoPrint-BedLevelVisualizer#482]
**Describe the bug**
Running Update Mesh causes 'customisation (added controls) on the Control tab to disappear - this is a weird one!

I've added the following 'custom controls' to the control tab by inserting them into config.yaml.  These have been working well for a very long time.  (months if not years)

controls:
- children:
  - children:
    - command: M851
      confirm: null
      name: Get
    - command: M500
      confirm: null
      name: Save
    layout: horizontal
  - default: 'Current Z Offset: ???'
    regex: M851 X([-+]?[0-9.-]+) Y([-+]?[0-9.-]+) Z([-+]?[0-9.-]+)
    template: 'Current Z Offset: {2}mm'
  - children:
    - command: M290 Z0.02
      confirm: null
      name: Babystep Up
    - command: M290 Z-0.02
      confirm: null
      name: Babystep Down
    - command: M290 Z0.01
      confirm: null
      name: Microstep Up
    - command: M290 Z-0.01
      confirm: null
      name: Microstep Down
    layout: horizontal
  layout: vertical
  name: Live-Z Probe Offset

When I run the 'Update Mesh Now' they disappear from the config, and the Control tab in Octoprint
The controls normally stay on the page - even when I restart Octoprint

**Expected behavior**
The control should stay on the page.

When  i next run the Update Mesh at the end of the mesh - they disappear!

I'm on Octoprint 1.7.0 - the issue appeared soon after upgrading.  However I've also updated other plugins so can't be sure this is exactly the cause.

**Screenshots**
![image](https://user-images.githubusercontent.com/79340535/139023485-65e95e6b-ca2f-4c90-b1a1-f697def7687b.png)

Becomes;
![image](https://user-images.githubusercontent.com/79340535/139026719-9dcd6949-c879-4338-b7a3-69fe790a4be7.png)

**Firmware and Version**
Octoprint 1.7.0
Marlin Bugfix 2.0.x

I can provide the debug if it will help - but the issue is not with the plugin itself.. its more with the way it seems to alter the Octoprint config?

**Comment by jneilliii** [comment]
This is a bug with how that plugin is doing it's work. I have a forked version of that plugin and submitted a PR to resolve, but the maintainer has not merged in the changes and released. If you want to use my fork, you can install it by copying/pasting the URL below into plugin manager > get more > ...from URL and clicking install. If the other plugin ever gets updated, you will still get notified of the update from them.

```
https://github.com/jneilliii/octoprint-customControl/archive/refs/heads/devel.zip
```

**Comment by LightningShark25** [comment]
@jneilliii Thanks for your response.  The link you have provided is for the CustomControl plugin.  I used to have this installed but suspected it was causing the problem so I removed it.  

The issue was continuing, even with CustomControl plugin removed....

 Did you mean to supply a link to BedVisualizer fork instead?

**Comment by jneilliii** [comment]
No, the only way this issue occurs is if the Custom Controls plugin is installed and enabled. My plugin does nothing to those settings outside of the plugins > bedlevelvisualizer section of your config.yaml. I've heard the issue can also occur if you have the system control editor installed, but that would clear out the system controls, not custom controls.

**Comment by LightningShark25** [comment]
Strange.  I was still having the problem EVEN after disabling CustomControls plugin.
However, it seems stable now.  What I did:

- Uninstalled BedLevelVisualizer
- Installed the forked CustomControl
- Disabled the CustomControl plugin - I've lost confidence in it
- Added my custom lines to config.yaml (via ssh)
- Reinstalled the BedLevelVisualizer

So far its OK.  I wonder if  the main difference between this and what I've tried in the past is the remove and reinstall of BedLevelVisualizer?

Either way I'm happy its working again.  Thanks again for your help

**Comment by LightningShark25** [comment]
Thought I'd feedback - I'm now using your build of the CustomControl Plugin.
Seems to be working well - I've updated the mesh many times and customs persist.
Can confirm the compiled version above fixes this issue for anyone else having this problem
