### ISSUE TITLE
[FR]: for the adjustment screen (especially for beginners) it may be helpful to be able to move the print head to the grid region you are trying to adjust.  (it may also be helpful to be able to adjust that corner then it will verify you have adjusted it the correct direction).

### ISSUE THREAD

**Issue by ryan-wo-3t** [jneilliii/OctoPrint-BedLevelVisualizer#484]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jneilliii** [comment]
Click the little arrows icon in the modebar of the graph and when you click on a point in the 3d view of the bed the head will move to that point.
