### ISSUE TITLE
[FR]: 

### ISSUE THREAD

**Issue by blured** [jneilliii/OctoPrint-BedLevelVisualizer#486]
**Is your feature request related to a problem? Please describe.**

Each time I level the bed, I need to figure out how the 9 points relate to the bed so I can correct the right one. 
**Describe the solution you'd like**

Could you make it so each of the 9 points number is displayed in order of evaluation? Thanks in advance.
**Describe alternatives you've considered**

**Additional context**

**Comment by jneilliii** [comment]
I can't control how it's returned by your firmware, it should return it in the same way every time. The axis lines are colored to help identify what is 0 and there are distances on these as well so maybe I'm just confused what your request actually is?
