### ISSUE TITLE
[BUG]: The UBL example on the wiki never shuts off the bed heater

### ISSUE THREAD

**Issue by KeyserSoSay0** [jneilliii/OctoPrint-BedLevelVisualizer#487]
**Describe the bug**
The UBL example code is missing "M140 S0 ; cooling down the bed".  I recently switched over to UBL and just copy and pasted the example and was surprised when I went out and my bed was still hot.

**Expected behavior**
The UBL example should also turn off the bed heating by having a "M140 S0 ; cooling down the bed" line.

**Debug Log**
NA

**Screenshots**
NA

**Firmware and Version**
NA

**Comment by jneilliii** [comment]
Thanes to @JoveToo this has been updated.
