### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by acmeGR** [jneilliii/OctoPrint-BedLevelVisualizer#489]
Hello.
I have a problem with G29 - Bed Leveling (Bilinear) and G29 - Bed Leveling (Unified)
When it sends G29 T (or G29 P1 P2 and P3), I receive: 
```Recv: echo:Unknown command: "G29 T"```

```
Recv:   TT::23.7523.75  //0.000.00  BB::47.8947.89  //0.000.00  @@::00  BB@@::00
Recv: 
Send: M140 S60
Recv: ok
Send: M117 Homing all axes
Recv: ok
Send: G28
Recv:   TT::23.7523.75  //0.000.00  BB::47.8947.89  //60.0060.00  @@::00  BB@@::127127
[...]
Recv: 
Recv: ok
Send: M300 S1000 P500
Recv: ok
Send: M117 Creating the bed mesh levels
Recv: ok
Send: M155 S30
Recv: ok
Send: G29 T
Recv: echo:Unknown command: "G29 T"
Recv: ok
Send: M155 S3
Recv: ok
Send: M140 S0
Recv: ok
Send: M300 S440 P200
Recv: ok
Send: M300 S660 P250
Recv: ok
Send: M300 S880 P300
Recv: ok
Send: M117 Bed mesh levels completed
Recv: ok
Recv:   TT::23.7923.79  //0.000.00  BB::60.1760.17  //0.000.00  @@::00  BB@@::00

```
What the printer does, is to go to home, heat the bed at 60 and then bips like it finished and cools the bed. 
In Bed Visualizer tab I keep seeing "Please wait, retrieving current mesh." till I press cancel button.

I use Ender 3 pro with Marlin fw 1.0.1

**Comment by jneilliii** [comment]
Unknown command means your printer's firmware isn't setup for Auto Bed Leveling.

**Comment by acmeGR** [comment]
So which firmwares are capable? Or do I need to have something like BL Touch for it to work?
thx

**Comment by jneilliii** [comment]
There is the option of manual mesh leveling,  otherwise the plugin requires the use of a probe of some sort.

**Comment by acmeGR** [comment]
I will buy bl touch and try it again. Thx
