### ISSUE TITLE
[FR]: 

### ISSUE THREAD

**Issue by Gwebber-Net** [jneilliii/OctoPrint-BedLevelVisualizer#492]
**Is your feature request related to a problem? Please describe.**

Not being able to see if my printer is actually doing bed levelling.

**Describe the solution you'd like**

It would be nice, if i could see the camera feed while doing this process.
So i know the printer is actually doing something
**Describe alternatives you've considered**

Running back and forth from my pc to the printer
**Additional context**

**Comment by Thegs68** [comment]
Hi
There is an option in Octoprint/settings/plugins/Bed Visualizer/Collection tab, there you can find the option to have the “Webcam while processing” at the bottom.
Hope this helps.

**Comment by jneilliii** [comment]
Thanks @Thegs68, that is correct.
