### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by K20FRITZ** [jneilliii/OctoPrint-BedLevelVisualizer#493]
**Describe the bug**

not showing the visual. shows error but when i click on it it says the webgl is fine.
**Expected behavior**

to see the visual like before 
**Debug Log**

**Screenshots**

**Firmware and Version**

1.7.2 python3

**Comment by jneilliii** [comment]
could you enable debug logging in the plugin's settings and attempt to update mesh again? Then share the octoprint.log, plugin_bedlevelvisualizer_debug.log and check your browser's developer tools, console tab for any errors on initial page load. I think you may be running into some form of conflict or loading issue. I run the plugin in multiple instances running python 3 and OctoPrint 1.7.2.

**Comment by K20FRITZ** [comment]
![16402876006267576687530834481962](https://user-images.githubusercontent.com/59301029/147284156-449d8b32-9a58-43d4-9e4d-7f70f8e2612b.jpg)

**Comment by K20FRITZ** [comment]
![16402876228045570259113398060316](https://user-images.githubusercontent.com/59301029/147284176-972f9c58-a42d-48f6-8545-eade9a4ec7bf.jpg)

**Comment by K20FRITZ** [comment]
![20211223_151130](https://user-images.githubusercontent.com/59301029/147287745-07bad03f-eeb0-48fa-b54f-da0142403e24.jpg)

**Comment by jneilliii** [comment]
you can upload those files here by dragging them into the comment. Nothing wrong in those. What multicam plugin are you using because I believe that is what's interfering here.

**Comment by K20FRITZ** [comment]
[octoprint-logs.zip](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/7771247/octoprint-logs.zip)

**Comment by jneilliii** [comment]
yeah, the data is getting collected so this is definitely a front-end conflict. What is the multi-cam plugin that you are using for displaying multiple cameras as that seems to be what's showing up here?

**Comment by K20FRITZ** [comment]
its not the cam its the actual plotter. but to test ive removed multicam and re tested with the same results.

**Comment by K20FRITZ** [comment]
Disregard. It was a mess up on my end adguard blocking the plotter 🤦🏽‍♂️ I truly appreciate your time and help. Merry Christmas and happy holidays to you
