### ISSUE TITLE
[BUG]: Displayed "Var" value not rounded to nearest 3rd decimal

### ISSUE THREAD

**Issue by AlexVercammen** [jneilliii/OctoPrint-BedLevelVisualizer#499]
Not really a BUG not a FEATURE, just a formatting issue.
In my case the "Var" value is 0.0399999999994. Where "Min" and "Max" values are rounded: -0.018 and 0.022
Excellent plug-in. I am definitely not using at its most potential but it gets the job done.
Snip Image included.
![image](https://user-images.githubusercontent.com/57072015/148064336-29cbff34-10a6-4ce6-977a-56c1c82b5433.png)

**Comment by jneilliii** [comment]
I'll take a look, the other values are probably not rounded, but returned rounded from the firmware.

**Comment by jneilliii** [comment]
I've resolved this in the above commit and will be available with the next 1.1.2 release candidate for testing in the future.
