### ISSUE TITLE
Home First

### ISSUE THREAD

**Issue by coogle** [jneilliii/OctoPrint-BedLevelVisualizer#5]
Looks like you forgot a case where `G29 T1` won't work unless you home the bed first:

```
Send: G29 T1
Recv: echo:Home XYZ first
```

There should be a pop-up that happens to ask if you want to home to bed (Latest Marlin)

**Comment by jneilliii** [comment]
You can modify the GOCE commands sent to the printer in settings.  Put in G28 and then G29 on the next line.  It currently does not work with anything other than UBL, I'm working on an update to resolve that.

**Comment by jneilliii** [comment]
Closing due to duplication, see #3.
