### ISSUE TITLE
[FR]: Individual bed size

### ISSUE THREAD

**Issue by Alex-APK-HZ** [jneilliii/OctoPrint-BedLevelVisualizer#500]
**Is your feature request related to a problem? Please describe.**
The dimension of the Graph and the probing points are off

**Describe the solution you'd like**
My printbed has a rectangular shape (220 mm by 195 mm). Still, the bed size of the graph is displayed as a square (220 mm by 220 mm). Furthermore the probe (BLTouch) is offset to the side, so the probe cannot reach the edge of the printbed. The probing points are spaced evenly in the accessable area. This results in the probing positions, calculated by the plugin, being off.

The best solution would be to draw the bed size values for the graph from the active printer profile.
Furthermore it would be nice to add the possibility to manually set the x and y coordinates of each of the probing points and link the resulting grid to the selected printer profile, so the plugin automatically draws the right grid for each setup. (for example when I switch between printbeds)

Lastly, (this is more of a convenience option) it would me great to have a way for the plugin to recalculate the data after changing the bed size and/or the positions of the probing points. Maybe just a button in the requested probing point coordinates menu, so the user can press it right after changing the values.

**Describe alternatives you've considered**
Just add a menu, to set the coordinates of each point in the grid, for example input them as a matrix. Afterwards store the values and link them to the printer profile, as they might only change when the printer receives a firmware update.

**Additional context**
I know this project is a lot of work. Many thanks to all the developers!

**Comment by jneilliii** [comment]
The plugin does utilize the printer profile to grab the dimensions of the bed. It does however, not take into account offsets from probing settings, etc. and the points are a rough estimate of where those would be based on dividing the dimensions by the number of probe points. Could you do me a favor and enable debug logging in the plugin, restart OctoPrint and then run through the update mesh process and then share your plugin_bedlevelvisualizer_debug.log file from OctoPrint's logging section?

**Comment by Alex-APK-HZ** [comment]
Edited the comment, because I explained it wrong. The bed size issue only applies for the values shown in the graph, not in the actual data tab. Only the issue with the probe offset altering the probing points is present in the data tab.

I should have the file ready in about half an hour.

Edit: Here is the file
[plugin_bedlevelvisualizer_debug.log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/7831089/plugin_bedlevelvisualizer_debug.log)

**Comment by Alex-APK-HZ** [comment]
Is the file readable?

**Comment by jneilliii** [comment]
Sorry, didn't get notice of an edit, was expecting new comment. I'll review later today.

**Comment by Alex-APK-HZ** [comment]
Oh, sorry. No problem.

**Comment by jneilliii** [comment]
Can you share a screenshot of your printer profile settings? What I'm seeing in the log is that you have the following:

> 'x_min': 0, 'x_max': 220.0, 'y_min': 0, 'y_max': 195.0

which leads me to believe your printer profile is set as 220 x 195.

**Comment by Alex-APK-HZ** [comment]
Yes, the available bed size is 220 x 195 (I am using an Ender 3 V2, so originally a 220 x 220, but the clips holding the bed take up some space in the y direction)
Furthermore the printhead has the folowing movement limits:
 X min -3 
 X max 245
 Y min 0 
 Y max 225 
 Z max 235

I should be able to provide a screenshot tomorrow.

**Comment by Alex-APK-HZ** [comment]
![B031414A-79B0-46D7-ABAB-E731C118EDA5](https://user-images.githubusercontent.com/97251381/151120814-9d7d7ac1-4766-4ede-a6cb-af0ea3c14d43.jpeg)
I‘m sorry it took so long. We had a lot of trouble at work. Here is the screenshot.

**Comment by jneilliii** [comment]
No problem, this is what I thought, and is very similar to other requests of this nature, #516, #434, #130.

**Comment by jneilliii** [comment]
Going to close in preference of #130 for now. I believe if I can get that one it will also meet the requirements of this one.

**Comment by jneilliii** [comment]
Added the option to define probe margin/offset in above commit and is available in version 1.1.2rc2. You can change the plugin's release channel in OctoPrint's Software Update settings to `Release Candidate` and update when prompted if you want to try it out.
