### ISSUE TITLE
Is this GCODE accuratly loading the bed level state of the printer?

### ISSUE THREAD

**Issue by MartinMeyerOnGithub** [jneilliii/OctoPrint-BedLevelVisualizer#504]
M155 S30  ; reduce temperature reporting rate to reduce output pollution
@BEDLEVELVISUALIZER	; tell the plugin to watch for reported mesh
M420 S1 V ; enabled leveling and report the new mesh
M500      ; save the new mesh to EEPROM
M155 S3   ; reset temperature reporting

**Comment by jneilliii** [comment]
`M420 S1 V ; enabled leveling and report the new mesh` would be enabling the mesh and reporting. I think you may want `M420 L1 V ; enabled leveling and report the new mesh` to load the stored mesh in slot 1 and report, but that's assuming you are using UBL. I personally just put in `M420 V` and that's it and have individual custom buttons for running the probing procedure with G29 P1, G29 P3, etc.
