### ISSUE TITLE
[FR]: 

### ISSUE THREAD

**Issue by Chavera81** [jneilliii/OctoPrint-BedLevelVisualizer#509]
**Is your feature request related to a problem? Please describe.**

I'd like to controll the number of probe points
**Describe the solution you'd like**

add the ability to enter the number of pints.
**Describe alternatives you've considered**

None, but im starting to look to see if it can be done.
**Additional context**

**Comment by jneilliii** [comment]
This is a firmware setting and not controllable by GCODE commands or any plugin, you'd have to recompile your firmware with the desired number of points.

**Comment by Chavera81** [comment]
Thank you for the quick response! Okay I will definitely look into it. New
to all this still.
