### ISSUE TITLE
[FR]: probe selected mesh square 

### ISSUE THREAD

**Issue by Volanaro** [jneilliii/OctoPrint-BedLevelVisualizer#510]
I'm wanting to be able to probe the bed on a specific square of the mesh, so I can level the bed alot more easily so for example the rear right region in till I stop it or for a specific amount of probes

**Comment by jneilliii** [comment]
I'd recommend you look into using the Autobim plugin or my Bed Leveling Wizard plugin to achieve what you are asking as a feature request. This plugin is only for graphing what is reported from firmware really, and can't control where your Auto Bed Leveling process probes.
