### ISSUE TITLE
[BUG]: Mesh doesn't get rendered, empty graph

### ISSUE THREAD

**Issue by xjjak** [jneilliii/OctoPrint-BedLevelVisualizer#518]
**Describe the bug**

Running automatic bed leveling is working fine and it seems that the plugin receives the data, but the mesh doesn't get rendered, just the coordinate system.

**Expected behavior**

A color-graded "sheet". The colors would represent the captured heights.

**Debug Log**

[plugin_bedlevelvisualizer_debug.log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/7977576/plugin_bedlevelvisualizer_debug.log)

**Screenshots**
![gcode-config](https://user-images.githubusercontent.com/55949396/151950101-9dbe7f71-5298-40ef-967f-47c5f6124fb8.png)
![visual-settings](https://user-images.githubusercontent.com/55949396/151950170-1fa94944-8349-4b13-93aa-42c9df2dc4bf.png)
![mesh-data](https://user-images.githubusercontent.com/55949396/151950217-808dc70b-5a24-4ded-a128-8d5bb9f09471.png)
![no-mesh](https://user-images.githubusercontent.com/55949396/151950225-a0820c74-997f-478d-810e-699e23aad6bd.png)

**Firmware and Version**

Marlin bugfix-2.0.x

**Comment by xjjak** [comment]
Well, I think I found the issue. I finally noticed that the data points are just way too low. Trying to search for a fix now, as soon as I find one, I'll close this issue.

**Comment by jneilliii** [comment]
Enable relative z offsets in the plugin's settings.
