### ISSUE TITLE
Perfect 0 on the Z Axis is beyond where my screw can physically tighten

### ISSUE THREAD

**Issue by djxs2000** [jneilliii/OctoPrint-BedLevelVisualizer#520]
My bed screw can't go any tighter to level the bed any lower, after adding a glass bed.
Is there a way to shift the entire z index when changing a bed plate, to facilitate getting my bed screw to move away from its physical tightened limit. I'm wishing for a way to move everything up by 1 or 2 MM , thus allowing me to unscrew that bed screw at least somewhat.
The perfect 0 level of what the visualizer is giving me is beyond the limits of my bed screw. How would I go about getting the screw somewhat looser and still going for perfect 0 in the visualizer?

**Comment by jneilliii** [comment]
enable the relative z offset option in visualization settings and it will normalize the lowest point to be 0.

**Comment by djxs2000** [comment]
Perfect! Thank you so much. Excellent plugin, by the way. Genius stuff.
