### ISSUE TITLE
Keeps saying wait Please wait, retrieving current mesh. It never retrieves.

### ISSUE THREAD

**Issue by nmfireman** [jneilliii/OctoPrint-BedLevelVisualizer#523]
**Describe the bug**

**Expected behavior**

**Debug Log**

**Screenshots**

**Firmware and Version**

**Comment by jneilliii** [comment]
Please provide the requested information in the issue template so I can better assist you.

**Comment by nmfireman** [comment]
[plugin_bedlevelvisualizer_debug.log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/8102574/plugin_bedlevelvisualizer_debug.log)

Not sure what else to say I think I explained it. Here is the Debug Log. I think I have your latest version. Let me know how I can  help you help me as I'm pretty new to using Octoprint and plug-ins

All I can tell you is it say's this Please wait, retrieving current mesh and never finishes. Here is a screen shot as wel
![Capture](https://user-images.githubusercontent.com/24758723/154809423-63a696e1-c738-47cd-ade7-05e3f0fec42f.JPG)
l

**Comment by nmfireman** [comment]
[plugin_bedlevelvisualizer_debug.log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/8102591/plugin_bedlevelvisualizer_debug.log)

**Comment by nmfireman** [comment]
![Capture](https://user-images.githubusercontent.com/24758723/154809471-fcf722e6-070c-4a80-a89e-95b1e4114f8b.JPG)

**Comment by jneilliii** [comment]
Based on the log it appears you might not be getting a response from your printer for the commands being sent. If you run the commands one at a time in the terminal tab do you get responses for all commands? At this point I think you're sending the wrong command or you don't have Auto Bed Leveling enabled firmware.
