### ISSUE TITLE
Compatibility For Prusa i3 MK3

### ISSUE THREAD

**Issue by PepperPengu** [jneilliii/OctoPrint-BedLevelVisualizer#53]
hi I wanted to know if this was compatible for Prusa i3 MK3 since mine and the other owners I know are not working

**Comment by jneilliii** [comment]
It should work for you as long as you use the correct sequence of gcode commands. My understanding is that the commands necessary for you are

```
G80
@BEDLEVELVISUALIZER
G81
```

let me knowif that doesn't work and provide as much detail as possible including terminal output, check for errors in octoprint.log, etc.

**Comment by ShakataGaNai** [comment]
I just finished building my Mk3 and tried this out. I can confirm the code above works. Once executed it runs a calibration pass on all 9 points and my octoprint happily spit out a graph.

![newplot](https://user-images.githubusercontent.com/1415068/40623647-c61277a2-625c-11e8-93e0-d5a54a41e0fa.png)

(Note: Running mk3 3.2.1 firmware & OctoPrint 1.3.8 running on OctoPi 0.15.0, latest as of time of this writing)

**Comment by jneilliii** [comment]
Thanks for confirmation.
