### ISSUE TITLE
[BUG]: Ender 6

### ISSUE THREAD

**Issue by Harveybean** [jneilliii/OctoPrint-BedLevelVisualizer#533]
**Describe the bug**
Manually levelled bed and its good. Probe the bed from firmware, and thats all good when I look at the mesh in Marlin.
When I move over to octoprint and use your plugin, it says the bed is miles off.

![bedmeshlevel](https://user-images.githubusercontent.com/101847783/158919644-c3ffe680-a959-42df-b2ec-d62303898d3c.jpg)

Marin 2.0.9.3 Ender 6 Core XY

**Comment by jneilliii** [comment]
Ther plugin just graphs what it is given from firmware. If you look at the mesh data in settings that it's retrieved you'll see the measured points. Based on your graph it appears that you haven't squared your gantry to the frame (not bed) I suspect.
