### ISSUE TITLE
[FR]: Ability to change grid sizes

### ISSUE THREAD

**Issue by Navyguy330** [jneilliii/OctoPrint-BedLevelVisualizer#536]
Just would like an easy way to change the printers grid size easily. 

4x4, 5x5, 4 corner only etc. etc

**Comment by jneilliii** [comment]
Sorry but this is a firmware option and nothing I can do to make that any different. The plugin just graphs the data provided by the printer. If you're looking for something to make it easier to adjust the screws on your printer you might want to check out the Autobim plugin.
