### ISSUE TITLE
[FR]: what is the code for flsun SR?

### ISSUE THREAD

**Issue by platini76** [jneilliii/OctoPrint-BedLevelVisualizer#538]
I need the code for flsun SR please

**Comment by jneilliii** [comment]
I can't tell you what that is as I don't know, what command do you use to do auto bed leveling?

**Comment by platini76** [comment]
I really don't know... I make autolevel from the display but before I have to mount an accessory with switch

**Comment by jneilliii** [comment]
My best guess would be bilinear example in the docs. Which minimally would be the following.

```
@BEDVISUALIZER
TWO
```

**Comment by platini76** [comment]
like this
<img width="814" alt="Schermata 2022-04-25 alle 22 18 16" src="https://user-images.githubusercontent.com/10352902/165168100-1af4bdad-8acf-4d9f-bb5a-549d3a0bef5d.png">
?

**Comment by jneilliii** [comment]
oh sorry, phone autocompleted that second line. it should be like this.

```
@BEDLEVELVISUALIZER
G29
```

**Comment by jneilliii** [comment]
oh sorry, phone autocompleted that second line. it should be like this.

```
@BEDLEVELVISUALIZER
G29
```

**Comment by platini76** [comment]
but I need to to it with switch mounted or without?

**Comment by jneilliii** [comment]
If the firmware is configured properly it should prompt you to attach the probe, same as from leveling from the LCD.

**Comment by platini76** [comment]
no it did not prompt message

**Comment by jneilliii** [comment]
Did it do anything? I know my flsun q5 with Marlin flashed on it does. Not sure if stock has ABL enabled. Delta calibration and auto bed leveling are slightly different things.

**Comment by platini76** [comment]
yes it worked...
thanks

<img width="617" alt="Schermata 2022-04-26 alle 14 24 59" src="https://user-images.githubusercontent.com/10352902/165299442-40c8708a-e622-420c-bdf7-effe423063a0.png">
I

it is good?

**Comment by jneilliii** [comment]
You might want to enable relative z offset setting.

**Comment by platini76** [comment]
here
<img width="796" alt="Schermata 2022-04-26 alle 22 09 22" src="https://user-images.githubusercontent.com/10352902/165383677-e082cff6-2ec5-4ad4-9267-daa8f0154b8e.png">
?

**Comment by jneilliii** [comment]
yeah, that's the one. it will allow the reported numbers to be moved down so that the lowest point graphs at 0 instead of floating way up in the air. once enabled, just click the update mesh button again and you should see the difference.

**Comment by platini76** [comment]
this is the resul
![newplot](https://user-images.githubusercontent.com/10352902/165408171-73509bed-628b-4933-bbd2-aa0804a0be03.png)
t

**Comment by jneilliii** [comment]
Yep, that looks about normal for a low probe count.

**Comment by platini76** [comment]
and can I also give an higher number of probe?

**Comment by jneilliii** [comment]
that would require flashing new firmware, it's not controllable via gcode I'm afraid.

**Comment by platini76** [comment]
so not factory firmware?

**Comment by jneilliii** [comment]
correct, it would have to be custom I think. not really sure what FLSUN ships with in their speed racer.

**Comment by platini76** [comment]
thank you very much.
plat
