### ISSUE TITLE
[BUG]: Bed graphic not displayed

### ISSUE THREAD

**Issue by KonigTX** [jneilliii/OctoPrint-BedLevelVisualizer#539]
**Describe the bug**
Was on an old version of OctoPrint using Python 2.something -- did a long overdue upgrade to Python 3+. Everything worked fine for about 24 hours then the Bed Visualizer completely disappeared. For a day it was just blank, with buttons shown but nothing else.  Today there was a brief message about my browser not supporting webgl which has since disappeared. Clicked the link in the briefly present message for help and was lead here: https://support.google.com/chrome/thread/1906535?hl=en -- did all these steps and still no fix. Here's the crome:gpu report: https://pastebin.com/cUR7VTJi

**Expected behavior**
Bed visualizer is shown and can be interacted with

**Screenshots**
[Image](https://imgur.com/a/6ufbGqG)

**Firmware and Version**
Marlin 2.0.x / OctoPrint 1.7.3 Python 3.7.3 OctoPi 0.17.0

**Comment by jneilliii** [comment]
That's strange. Typically if there are rendering issues with the 3d view it's related to video drivers/graphic card issues. Have you verified the latest available drivers are installed for your video card?

**Comment by KonigTX** [comment]
Sorry for wasting your time. I decided to do a clean install of graphics drivers and now it's working.
