### ISSUE TITLE
[BUG]: Display chart  layout does not match display graph

### ISSUE THREAD

**Issue by htrabbit** [jneilliii/OctoPrint-BedLevelVisualizer#545]
**Describe the bug**
<in the chart Y0 is at the topleft
Image for the Dial is not visible

**Expected behavior**
<i expect to see X0Y0 in the bottom left of the chart to match the image\
i have try the option to flip the axis , however thy do not appear to do anything

**Screenshots**
![Bed_lvl_octoprint](https://user-images.githubusercontent.com/59135057/170733917-1463850e-b6c0-44fa-9b8b-268e1a9e60e6.png)

**Firmware and Version**
[octoprint-systeminfo-20220527085117.zip](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/8787868/octoprint-systeminfo-20220527085117.zip)

**Comment by jneilliii** [comment]
There's options in the adjustments section in settings to reverse the rows in the table.

**Comment by htrabbit** [comment]
Yes, i see those, they had no effect. i will reinstall and start fresh. i was going to post logs but both logs are empty


 
  
Subject: Re: [jneilliii/OctoPrint-BedLevelVisualizer] [BUG]: Display chart layout does not match display graph (Issue #545)


There's options in the adjustments section in settings to reverse the rows in the table.

**Comment by htrabbit** [comment]
any ideas about the thumb wheel in the middle of the image instead of the right side?
also here is the logging window, am i doing something wrong?
![Bed_lvl_octoprint logging](https://user-images.githubusercontent.com/59135057/170801373-29997dd4-9260-4a21-9286-829e93774288.png)

**Comment by jneilliii** [comment]
The mixed up columns is usually because of uneven probe point quantity x,y. On the support team of the plugin's settings enable debug logging there and restart octoprint.

**Comment by htrabbit** [comment]
the octo log shows debug log set, but i get no bed log.
[octoprint (4).log.txt](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/8790174/octoprint.4.log.txt)

**Comment by jneilliii** [comment]
If you want to enable debug logging, do it from the plugin's settings as instructed please, not OctoPrint's logging settings.

**Comment by htrabbit** [comment]
ok, got the debug log, still can not reverse the Y-position in the adjustment chart so that 0,0 is in the bottom left. i tried with flip y-axis  checked and unchecked. 
[plugin_bedlevelvisualizer_debug.log.txt](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/8791886/plugin_bedlevelvisualizer_debug.log.txt)

![Bed_lvl_octoprint collection](https://user-images.githubusercontent.com/59135057/170843311-2272c525-bd37-4c2d-8af1-e8c861293c09.png)
![Bed_lvl_octoprint corections](https://user-images.githubusercontent.com/59135057/170843322-019f9764-b677-44a3-97f8-79b7fdc2a6f8.png)
![Bed_lvl_octoprint](https://user-images.githubusercontent.com/59135057/170843330-e097c389-1ca1-49de-8889-86699765c7d0.png)

as for the  thumbwheel being in the middle of the chart, i think it might be a image scale issue because i use octoprint widescreen, it might be pushing the thumbwheel over Maybe.
![Bed_lvl_octoprint Wide screen](https://user-images.githubusercontent.com/59135057/170843293-a6e02172-c451-447e-9a3d-b0c6904fb877.png)

**Comment by jneilliii** [comment]
Oh sorry, it's on the Data tab. It should adjust both. 

![image](https://user-images.githubusercontent.com/5249455/170843711-e6286799-8a65-4a14-aa68-e45f03c1f412.png)

Based on the log it is as I expected, a rectangular probing data. Seems like you're getting a 13x9 probing grid.

```
['-0.075833', '-0.089080', '-0.110623', '-0.122500', '-0.115444', '-0.100833', '-0.091667', '-0.091056', '-0.091667', '-0.090833', '-0.080988', '-0.064809', '-0.055000']
['-0.095003', '-0.109291', '-0.132563', '-0.145539', '-0.138939', '-0.124842', '-0.116008', '-0.115762', '-0.116875', '-0.116273', '-0.105993', '-0.089027', '-0.078734']
['-0.130312', '-0.146531', '-0.173009', '-0.188021', '-0.182250', '-0.169084', '-0.160854', '-0.161303', '-0.163381', '-0.163229', '-0.152148', '-0.133728', '-0.122542']
['-0.163591', '-0.181718', '-0.211360', '-0.228367', '-0.223313', '-0.210903', '-0.203190', '-0.204452', '-0.207715', '-0.208154', '-0.196324', '-0.176504', '-0.164453']
['-0.176667', '-0.195765', '-0.227012', '-0.245000', '-0.240062', '-0.227642', '-0.220000', '-0.221981', '-0.226407', '-0.227500', '-0.215389', '-0.194944', '-0.182500']
['-0.151065', '-0.170007', '-0.200945', '-0.218549', '-0.212089', '-0.197281', '-0.188464', '-0.192173', '-0.199787', '-0.202906', '-0.191450', '-0.171643', '-0.159544']
['-0.097937', '-0.116263', '-0.146092', '-0.162646', '-0.153242', '-0.133877', '-0.122792', '-0.129566', '-0.142890', '-0.149667', '-0.139551', '-0.121164', '-0.109854']
['-0.043549', '-0.061186', '-0.089784', '-0.105211', '-0.092837', '-0.068888', '-0.055516', '-0.065323', '-0.084309', '-0.094719', '-0.085973', '-0.069058', '-0.058570']
['-0.014167', '-0.031426', '-0.059352', '-0.074167', '-0.060191', '-0.033772', '-0.019167', '-0.030605', '-0.052636', '-0.065000', '-0.056994', '-0.040877', '-0.030833']
```

could you place the `@BEDLEVELVISUALIZER` line just above the `BED_MESH_OUTPUT` line and see if it makes a difference? would like to see what's at the very end of the process in the terminal tab.

**Comment by htrabbit** [comment]
Like this?
HOME
BED_MESH_CALIBRATE
@BEDLEVELVISUALIZER	; instruct plugin to start recording responses from printer.
BED_MESH_OUTPUT		; report the bed leveling mesh points.
SAVE_CONFIG 

Klipper
bed mesh
probe_count: 5,3
algorithm: bicubic #bicubic,lagrange

5x3 probe with Mesh Interpolation

**Comment by jneilliii** [comment]
Yes, like that. If you change to `probe_count: 5,5` it would resolve the wheel issue.

**Comment by htrabbit** [comment]
so close , lol. 
No thumbwheel at all now. too many points haha

![Bed_lvl_octoprint](https://user-images.githubusercontent.com/59135057/170844948-4cbc632b-81bc-406b-b51a-b86a2d67decb.png)

**Comment by htrabbit** [comment]
ok, if i set
mesh_pps: 0  so there is NO  Mesh Interpolation......Victory
we just lose some "guessed" resolution
![Bed_lvl_octoprint](https://user-images.githubusercontent.com/59135057/170845380-ca7a104d-17c2-41a1-9be7-ecda238f781a.png)

**Comment by jneilliii** [comment]
With mesh interpolation enabled what does the command BED_MESH_OUTPUT return on the terminal tab? I suppose it's outputting the points in-between the probe points in it's report, or did you change probe_count to 13,13? I personally am using UBL in Marlin and that is utilizing a 10,10 probe_count.

**Comment by htrabbit** [comment]
that was 5,5 probe With no mesh interpolation
in klipper i can enable mesh interpolation with many in between points
ie 
mesh_pps: 2,3  # 2 points between every x and 3 in between every y

what would you like to see and i will run them

**Comment by htrabbit** [comment]
with mesh_pps: 2,2
[Bed_lvl_octoprint.txt](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/8792430/Bed_lvl_octoprint.txt)
![Bed_lvl_octoprint](https://user-images.githubusercontent.com/59135057/170847755-ead2ac76-1b33-4fc1-8c32-f5c14dac9994.png)

**Comment by jneilliii** [comment]
That makes more sense to me now. So it basically needs to be equal x,y for both probe_count and for mesh_pps.

**Comment by htrabbit** [comment]
yes I have confirmed that if I change it to any odd value, the display loses the thumb wheel. the only other thing that would be nice on this, is if we could have positions for the thumb wheels like they do on klipper. as an example I don't have a 169 thumb wheels to adjust. rather I have six three along X the front, and three along X at the rear.

**Comment by jneilliii** [comment]
Yeah, the rectangular issue is covered by #381. For what you're asking for it seems like you would benefit more from the Autobim plugin.

**Comment by htrabbit** [comment]
i think we have a good solution, keep X and Y samples equal.
