### ISSUE TITLE
[BUG]:Your printer's firmware reported an error. Due to that OctoPrint will disconnect. Reported error: Probing Failed

### ISSUE THREAD

**Issue by GuBo88** [jneilliii/OctoPrint-BedLevelVisualizer#547]
**Describe the bug**

**Expected behavior**

**Debug Log**

**Screenshots**

**Firmware and Version**

[plugin_bedlevelvisualizer_debug.log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/8926415/plugin_bedlevelvisualizer_debug.log)

**Comment by jneilliii** [comment]
I don't control that. I suspect you are using gcode command in the settings your printer doesn't understand. Do you happen to need using jyers firmware? If so it's a known a issue and you should check their wiki for recommended octoprint settings and complain in their repo not mine.
