### ISSUE TITLE
[FR]: 

### ISSUE THREAD

**Issue by PeterGillham1** [jneilliii/OctoPrint-BedLevelVisualizer#548]
**Is your feature request related to a problem? Please describe.**

When printing multiple products (PLA,PLA+,PETG etc.), they all need different bed temperatures.
It would be nice to be able to select the product with pre-defined temperature rather than having to edit the code manually.
*Describe the solution you'd like**

To be able to configure a product with a pre-defined bed temperature and simply select the product rather than changing the code all the time
**Describe alternatives you've considered**

Bed temperature selection dopdown would be OK

**Additional context**

**Comment by jneilliii** [comment]
You can technically use the commands to create your own custom buttons and as long as you use the @BEDLEVELVISUALIZER tag it would work. I use this approach for actually doing my probing with UBL and the various slots for different temperatures.

![image](https://user-images.githubusercontent.com/5249455/174448686-bd9a275f-f284-4057-a025-59437353f077.png)

**Comment by PeterGillham1** [comment]
Many thanks - neat solution :-)
