### ISSUE TITLE
[BUG]: Beep before retrieving mesh does not stop.

### ISSUE THREAD

**Issue by TLBradbury** [jneilliii/OctoPrint-BedLevelVisualizer#549]
**Describe the bug**
Before retrieving the current mesh, the plugin emits a short beep, but sometimes it does not stop. Once it has started, there is no way to silence it.

**Expected behavior**
A short beep before retrieving current mesh.

**Debug Log**

[octoprint-logs.zip](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/8933592/octoprint-logs.zip)

**Screenshots**

**Firmware and Version**
Firmware Name: Marlin 2.0.9.2 (Nov 14 2021 10:06:37)
Machine Type: Ender-3 4.2.7

**Comment by jneilliii** [comment]
That's probably just a printer firmware issue. Remove the lines with M300 from your gcode commands and you'll be fine.

**Comment by TLBradbury** [comment]
Thanks, I'll be sure to give it a try. I was planning on updating my firmware soon anyway (changing hotend).
