### ISSUE TITLE
WebGL error on iPad Safari

### ISSUE THREAD

**Issue by mark-psl** [jneilliii/OctoPrint-BedLevelVisualizer#55]
Hi,

I’m getting the error displayed in the attached file.  When I go to the WebGL site and test the browser I confirm it supports WebGL (I see the spinning cube).  Any thoughts on what might be causing this?
![fc389389-d706-4ba1-b192-42d5545b83cf](https://user-images.githubusercontent.com/3613327/40869819-afcea3c6-65ef-11e8-9429-49cf66ba3a5b.jpeg)

**Comment by jneilliii** [comment]
Looks like there is an open ticket for this on the plotly library being used that indicates a compatibility issue.  See it over [here](https://github.com/plotly/plotly.js/issues/280).

**Comment by jneilliii** [comment]
I just pushed a new 0.1.1 branch that potentially could resolve this.  If you don't mind testing by installing using the following url in plugin manager and let me know that would be great.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.1.1.zip

**Comment by mark-psl** [comment]
That did it.  Thanks!

BTW, your plug-in is a life saver.  Helps me level the bed to get my EZABL working correctly.  

Mark G.
