### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by lcbathtissue** [jneilliii/OctoPrint-BedLevelVisualizer#550]
**Describe the bug**
After updating Marlin firmware now getting stuck on ' Please wait, retrieving current mesh. '

I have tried several times now removing the plugin entirely and reinstalling. And I have tried previously with the lines of GCODE that were used and working prior to updating Marlin and also using the bilinear GCODE example supplied. Both result in getting stuck on ' Please wait, retrieving current mesh. '

**Expected behavior**
After XY home and Z home normally Bed Visualizer probes our ender-3's bed 9 times in a grid.

**Debug Log**
[2022-06-18 03:00:01,680] DEBUG: mesh collection started
[2022-06-18 03:00:16,706] DEBUG: Canceling mesh collection per user request
[2022-06-18 03:00:16,707] DEBUG: Mesh data collected prior to cancel:
[2022-06-18 03:00:16,707] DEBUG: []
[2022-06-18 03:00:16,708] DEBUG: Mesh data after clearing:
[2022-06-18 03:00:16,709] DEBUG: []
[2022-06-19 02:06:58,833] DEBUG: mesh collection started
[2022-06-19 02:07:49,885] DEBUG: mesh collection started

These (above) were the contents of the debug log

**Screenshots**
![image](https://user-images.githubusercontent.com/67947477/174461829-499070cc-5963-4534-bb50-52cd1a6c9a02.png)
![image](https://user-images.githubusercontent.com/67947477/174461836-61dde645-9601-4490-8f15-450c793a797a.png)
![image](https://user-images.githubusercontent.com/67947477/174461845-4083fa34-ad8f-4b97-a294-ef0a53ce4b21.png)
![image](https://user-images.githubusercontent.com/67947477/174461850-bcf7c74d-c8f4-4114-bf2b-b821ed071629.png)
![image](https://user-images.githubusercontent.com/67947477/174461855-c23b6339-6b02-4819-be70-4fb09b5221e1.png)
![image](https://user-images.githubusercontent.com/67947477/174461857-dbcb45a6-5018-4fc3-b8c4-f9a0f4fc808c.png)
![image](https://user-images.githubusercontent.com/67947477/174461864-cea22d25-3de9-4e17-8c10-72d572f35a9f.png)

**Firmware and Version**

Marlin 2.0.9.3

OctoPrint Version 1.8.1 on Raspberry Pi

Thank you jneilliii, I love this plugin and get a kick out of using it as well as a new 3D printer it has solved a lot of my bed leveling woes...

**Comment by jneilliii** [comment]
Typically means the firmware doesn't have leveling enabled. If it happened to be jyers firmware there are known octoprint settings that need to be adjusted per their wiki, only other time I've seen this type of issue. That or the printer wasn't turned on.
