### ISSUE TITLE
Mesh doesn't reload after reboot the printer and octoprint

### ISSUE THREAD

**Issue by labamichnetvoll** [jneilliii/OctoPrint-BedLevelVisualizer#556]
Hi there,
first of all thank you very much for this nice visual plugin of the BedLeveling.

I have an Anycubic Vyper (Zombie Firmware 2.8) connected to a raspberry pi zero 2w with octoprint installed.

When I'm turning on the printer and the Raspberry Pi I can start the "update mesh" to receive the current heated bed-leveling.
Thats working great!
The only problem: The mesh should be stored on the printer with the M420 S1 command followed by M500 right? But after a reboot it seems like with M503 the M420 is S0... so something doesn't safe corretly there.

So, how to save the mesh right on the eeprom of the printer and how can I get it back right?

I've tried some commands like M501, M420 L, M420 S1 before I started a print after a reboot, but that didn't help.

I hope you have some Ideas where the issues are located here
Thanks in advance:)

**Comment by jneilliii** [comment]
That all depends on your firmware and what type of leveling, but yes M500 would saved to eeprom. I recommend you look into what commands are necessary for your printer or funds out off it's even possible. Recommend the support-printer channel on OctoPrint's discord server.
