### ISSUE TITLE
[FR]: Orthogonal rendering

### ISSUE THREAD

**Issue by JernejL** [jneilliii/OctoPrint-BedLevelVisualizer#557]
A orthogonal rendering would be very welcome, as it would enable better perspective at the bed, allowing to see labels that are obscured due to perspecive vanishing point. 
 
An toggle option for this would be welcome.

**Comment by jneilliii** [comment]
I don't understand what you mean.

**Comment by JernejL** [comment]
https://en.wikipedia.org/wiki/Orthographic_projection
 
it is a rendering view with no perspective, it would allow for axis labels to be shown regardless of "depth"

**Comment by jneilliii** [comment]
See if this works. Load the tab to show the graph and then open your browser's developer tools and copy/paste the commands below into the console tab and hit enter. 

```
temp1 = $('#bedlevelvisualizergraph')[0].layout;
temp1.scene.camera['projection'] = {'type': 'orthographic'};
Plotly.relayout('bedlevelvisualizergraph', temp1);
```

Changed this

![image](https://user-images.githubusercontent.com/5249455/179149620-981e7737-4290-443b-bfef-9751c835070a.png)

to this for me

![image](https://user-images.githubusercontent.com/5249455/179149708-9934604c-3847-4712-b0a1-45e8abde5e07.png)

I see what you mean about being able to see the grid labels, but personally not sure if I like the look. Would definitely consider making it an option.

**Comment by JernejL** [comment]
I love it, if that is availible as an option that would be awesome.

**Comment by jneilliii** [comment]
Added with the above commit to the rc branch and will be available in next rc release after getting a couple of more issues completed this weekend. You can change the plugin's release channel in OctoPrint's Software Update settings to Release Candidate and update when it comes out, or manually install by copying/pasting the URL below into plugin manager > get more > ...from URL and clicking install.

```
https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/refs/heads/rc.zip
```
