### ISSUE TITLE
nasty background-color

### ISSUE THREAD

**Issue by electronicm** [jneilliii/OctoPrint-BedLevelVisualizer#559]
The following Lines crashes some Themes from UI Customizer

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/blob/88eb516294efa08a1a3407f4bd55bd27259b3fac/octoprint_bedlevelvisualizer/static/css/bedlevelvisualizer.css#L73-L75

![image](https://user-images.githubusercontent.com/13643227/180600628-00caee3e-2eab-47df-ae22-7102d86fe370.png)

I have so far overridden it via UI Customizer > Advanced > Custom CSS, but maybe others have the problem too.
```
div#tab_plugin_bedlevelvisualizer .table thead tr.info > th, div#tab_plugin_bedlevelvisualizer .table tbody tr td.info, div#tab_plugin_bedlevelvisualizer .table tfoot tr.info > th {
   background-color: inherit !important;
}
```

**Comment by jneilliii** [comment]
That's why I documented them.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/blob/master/wiki/index.md#theme-support
