### ISSUE TITLE
[BUG]: Unfortunately it no longer works with 4.4.0-BETA2 Firmware for Original Prusa MINI/MINI+

### ISSUE THREAD

**Issue by tafelberg** [jneilliii/OctoPrint-BedLevelVisualizer#560]
**Describe the bug**
The Mini beeps once and does not run the program.

**Expected behavior**

**Debug Log**

**Screenshots**

**Firmware and Version**
4.4.0-BETA2 Firmware for Original Prusa MINI/MINI+

**Comment by jneilliii** [comment]
Maybe they changed the commands? Would need lots more information than it just doesn't work since I don't have a mini. Enable debug logging, serial logging etc and that might help to see what the mini is doing/responding with.

**Comment by jneilliii** [comment]
Might be able to see what's happening from the terminal tab. It might show us basically the same info that would need logged to serial.log when enabled.

**Comment by tafelberg** [comment]
[serial.log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/9213571/serial.log)
[plugin_bedlevelvisualizer_debug.log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/9213573/plugin_bedlevelvisualizer_debug.log)

**Comment by jneilliii** [comment]
weird, I don't see the command being sent to the printer for actually doing the probe operation. Are you using the [Prusa Mini gcode](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/blob/master/wiki/gcode-examples.md#prusa-mini) from the examples?

**Comment by tafelberg** [comment]
<img width="638" alt="Bildschirmfoto 2022-07-29 um 08 35 42" src="https://user-images.githubusercontent.com/110171598/181698465-e3c94fb0-d8ae-43d8-81b6-9d0888fb9817.png">

<img width="688" alt="Bildschirmfoto 2022-07-29 um 09 52 45" src="https://user-images.githubusercontent.com/110171598/181711722-e3f5bed7-1de7-4f9e-99f1-8c959808b2aa.png">

Starting with the button (Update Mesh Now) in octoprint. (As always for two years)
Then I see that the print head moves to the first position. The printer heats up. At 59 degrees, the printer beeps once and nothing happens anymore. Without restarting the printer, I can no longer print

.

**Comment by jneilliii** [comment]
You might want to ask Prusa what has changed in their firmware, I can't control that.

**Comment by tafelberg** [comment]
Prusa-Support is now looking for it.

**Comment by tafelberg** [comment]
Same problem with 4.4.0-RC1
Prusa I also informed
(https://github.com/prusa3d/Prusa-Firmware-Buddy/issues/2322)

**Comment by jneilliii** [comment]
curious if you simplify the gcode options down to the following if it works?

```
@BEDLEVELVISUALIZER
G29 T
```

**Comment by tafelberg** [comment]
Then nothing happens

**Comment by tafelberg** [comment]
This code works. But at the end there is a beep and the plugin crashed. I have always to restart the mini.



M140 S60 ; starting by heating the bed for nominal mesh accuracy
M117 Homing all axes ; send message to printer display
G28 ; home all axes
M420 S0 ; Turning off bed leveling while probing, if firmware is set
; to restore after probing
M117 Creating the bed mesh levels ; send message to printer display
M155 S30 ; reduce temperature reporting rate to reduce output pollution
@BEDLEVELVISUALIZER ; tell the plugin to watch for reported mesh
G29 T ; run bilinear probing
M500 ; store mesh in EEPROM
M300 S440 P200 ; make calibration completed tones
M300 S660 P250
M300 S880 P300
M117 Bed mesh levels completed ; send message to printer display


<img width="624" alt="Bildschirmfoto 2022-10-08 um 13 43 50" src="https://user-images.githubusercontent.com/110171598/194705785-b850f309-5539-4886-8c13-7a62220422ae.png">

**Comment by jneilliii** [comment]
Just take out any additional gcode that is unnecessary, so the M300 commands and M117 commands are beeps and messages on printer screen.
