### ISSUE TITLE
[BUG]: My printer just kept repeating the leveling, over and over. Then it got stuck in the back right corner and it would make a terrible sounding "beep" and then keep probing the same point. 

### ISSUE THREAD

**Issue by Dragonstuff83** [jneilliii/OctoPrint-BedLevelVisualizer#564]
**Describe the bug**
[BUG]: My printer just kept repeating the leveling, over and over. Then it got stuck in the back right corner and it would make a terrible sounding "beep" and then keep probing the same point. 

**Expected behavior**
 Not that

**Debug Log**

**Screenshots**

**Firmware and Version**

**Comment by jneilliii** [comment]
I think you may have copied the wrong gcode from the examples page. The beeping is from the M300 commands, you can remove those from the gcode your sending. My best guess is that you should be using the bilinear example.

**Comment by Dragonstuff83** [comment]
@jneilliii Thank you. I'll give that a try.
