### ISSUE TITLE
[FR]: Support for Repetier Firmware v1.0.0+

### ISSUE THREAD

**Issue by curtyc** [jneilliii/OctoPrint-BedLevelVisualizer#565]
Hi everybody! :-)

jneilliii, very nice job with your plugin! Thank you!

I would like to use it with Repetier Firmware also.

Unfortunately, I have not yet received results because Repetier Firmware uses a different GCode (G29 T --> G32 S1 P0) and output format, as follows:

---cut here---
[...]
Send: N67 G32 S1 P0*43
Recv: ok
Send: N68 M155 S3*92
Recv: Z correction disabled
Recv: Info:Autoleveling disabled
[...]
Recv: Z-probe:12.951 X:5.00 Y:5.00
[...]
Recv: Z-probe:12.553 X:5.00 Y:58.33
[...]
Recv: Z-probe:12.517 X:5.00 Y:111.66
[...]
Recv: Z-probe:12.390 X:5.00 Y:165.00
[...]
Recv: Z-probe:12.713 X:46.66 Y:5.00
[...]
Recv: Z-probe:12.531 X:46.66 Y:58.33
[...]
Recv: Z-probe:12.533 X:46.66 Y:111.66
[...]
Recv: Z-probe:12.427 X:46.66 Y:165.00
[...]
Recv: Z-probe:12.502 X:88.32 Y:5.00
[...]
Recv: Z-probe:12.477 X:88.32 Y:58.33
[...]
Recv: Z-probe:12.507 X:88.32 Y:111.66
[...]
Recv: Z-probe:12.442 X:88.32 Y:165.00
[...]
Recv: Z-probe:12.255 X:130.00 Y:5.00
[...]
Recv: Z-probe:12.343 X:130.00 Y:58.33
[...]
Recv: Z-probe:12.428 X:130.00 Y:111.66
[...]
Recv: Z-probe:12.428 X:130.00 Y:165.00
Recv: plane: a = -0.0019 b = -0.0010 c = 12.7116
Recv: Transformation matrix: 0.999998 0.000000 0.001887 -0.000002 1.000000 0.000994 -0.001887 -0.000994 0.999998
Recv: Printer height:169.65
Recv: CurrentZ:12.71 atZ:12.78
[...]
Recv: Info:Autoleveling enabled
Recv: X:130.02 Y:165.01 Z:12.302 E:0.0000
Recv: ok
[...]

---cut here---

Could you include support for Repetier Firmware v1.0.0+?

Thank you in advance! :-)

**Comment by jneilliii** [comment]
Have you tried

```
@BEDLEVELVISUALIZER
G32 S1 P0
```
