### ISSUE TITLE
[FR]: adjustable zero point

### ISSUE THREAD

**Issue by DaveDec** [jneilliii/OctoPrint-BedLevelVisualizer#567]
**Is your feature request related to a problem? Please describe.**
With Mingda printers, the BL is down around -8

**Describe the solution you'd like**
I would like to be able to set the "zero point" for the Z along with the Z Limits.

**Describe alternatives you've considered**

**Additional context**

**Comment by jneilliii** [comment]
> I would like to be able to set the "zero point" for the Z

enable the option `Use Relative Z Offsets` on the collection tab in the plugin's settings.

> along with the Z Limits.

Set the Z limits on the visualization tab in the plugin's settings.
