### ISSUE TITLE
Where i can Set the Z Offset.[FR]: 

### ISSUE THREAD

**Issue by Aukub1990** [jneilliii/OctoPrint-BedLevelVisualizer#569]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jneilliii** [comment]
the plugin doesn't set the z offset, but if you want to add a custom button to do so you can. something like this.

![image](https://user-images.githubusercontent.com/5249455/194760919-921a6ae2-d93f-4d9a-8d4e-9ced2b6764b5.png)

![image](https://user-images.githubusercontent.com/5249455/194760954-8e08e0ae-d8d1-4392-8840-280a60eb31be.png)
