### ISSUE TITLE
Bed Visualizer Error

### ISSUE THREAD

**Issue by ipproekt** [jneilliii/OctoPrint-BedLevelVisualizer#57]
"TypeError: Cannot read property 'canvas' of undefined Looks like your settings are not correct or there was an error. "

Settings:
G29 T

Marlin 1.1.8 UBL

Send: G29 T
Recv: echo:������������ XYZ ������������
Recv: 
Recv: Bed Topography Report:
Recv: 
Recv: (0,2)           (2,2)
Recv: (50,250)        (250,250)
Recv:  -0.053   -0.188   -0.268
Recv: 
Recv:   0.003   -0.128   -0.241
Recv: 
Recv: [ 0.141]  -0.145   -0.357
Recv: (50,50)            (250,50)
Recv: (0,0)             (2,0)
Recv: ok

Whats wrong?

**Comment by jneilliii** [comment]
Which browser are you using?

**Comment by ipproekt** [comment]
Chrome, but i think  that problem with parsing Bed Topogrraphy Report. Maybe non english character ater "echo"?

**Comment by jneilliii** [comment]
Can you post your settings please?

**Comment by ipproekt** [comment]
Hello! Now i enabled WebGL in Chrome settings and it work fine. In my case Chrome show on website "WebGL enabled" and i see rotate cube, actually in same time WebGL not been enabled in settings. 
Thank you.

**Comment by jneilliii** [comment]
Cool, that makes sense.  I didn't even realize you could turn off webgl, thanks for sharing.
