### ISSUE TITLE
[FR]: Would be amazing to know were the front of your bed is... 

### ISSUE THREAD

**Issue by DirtyKityLitter** [jneilliii/OctoPrint-BedLevelVisualizer#575]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DirtyKityLitter** [comment]
Sorry, New to GitHub.

It would be nice to have some text on the bottom of the graph that says "front of bed" maybe some navigational directions. Its probably obvious to most people but would be a simple "ease of life" thing.

Thank you for your hard work.

Also, this app would be so amazing if it could be an option with display on octodash.

Using a 7" Raspberry Pi touchscreen with amazing quality. its Raspberry Pi brand if that helps

**Comment by jneilliii** [comment]
You can display in octodash. Check the release notes here.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/releases/tag/1.1.1
