### ISSUE TITLE
[BUG]: Type Error: undefined is not an object (evaluating 'data.points')

### ISSUE THREAD

**Issue by tafelberg** [jneilliii/OctoPrint-BedLevelVisualizer#577]
**Describe the bug**

**Expected behavior**

**Debug Log**

**Screenshots**
<img width="1326" alt="Bildschirmfoto 2022-12-06 um 10 23 08" src="https://user-images.githubusercontent.com/110171598/205873903-09c07121-2809-4a54-ae41-388830b838f1.png">
<img width="1410" alt="Bildschirmfoto 2022-12-06 um 10 24 02" src="https://user-images.githubusercontent.com/110171598/205873951-1597b03f-a6d2-4dc2-8507-4d0896903ae8.png">

**Firmware and Version**
4.4.0 Firmware for Original Prusa MINI/MINI+
OctoPrint 1.8.6
Bed Visualizer Settings Version 1.1.2rc3

**Comment by jneilliii** [comment]
It would be great if you could follow the directions in the issue template that you just completely ignored.
