### ISSUE TITLE
[BUG]: Bed Leveling not functioning

### ISSUE THREAD

**Issue by Bhavlovick** [jneilliii/OctoPrint-BedLevelVisualizer#585]
**Describe the bug**
I am not sure if this is a problem with BedLevelVisualizer or not but it isn't working for me.  It will run the routine and it provides me a visual view of my bed level but when printing the Z level isn't adjusting at all and my first layer performance is terrible.

In the gcode of my files, I include the following two lines at the beginning of my print:
G28
M420 S1

**Expected behavior**
Everything appears to work fine but I am expecting to be able to watch the Z axis stepper motors to be moving as it prints across the bed.  Also I would expect better first layer adhesion if it was working properly, on some portions of the bed surface adhesion is good but others there is no adhesion at all.  I would expect the Mesh to greatly improve what I am seeing.

**Debug Log**
[plugin_bedlevelvisualizer_debug.log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/10333853/plugin_bedlevelvisualizer_debug.log)

**Screenshots**
![Screenshot 2023-01-02 172501](https://user-images.githubusercontent.com/121835743/210287048-8c6bc452-6055-4ac9-82fa-aef4068cfd53.jpg)

**Firmware and Version**
I am using Marlin Version 1.1.4 on a Anet A8 printer with the version 1 control board.

I would appreciate it if you can help me with figuring out why this isn't working for me.
Regards
Bhavlovick

**Comment by jneilliii** [comment]
You are correct, what you expect to be happening should be, but that's not a bug with the plugin. Recommend you reach out on OctoPrint discord for assistance in the support-printer channel or on the community forum.
