### ISSUE TITLE
[Feature Request] Display Date of last Mesh-Update

### ISSUE THREAD

**Issue by AcHub** [jneilliii/OctoPrint-BedLevelVisualizer#59]
I don't refresh my mesh before every print as I noticed only marginal to no changes in bed level heights from print to print in the past. 
But still I want to update the mesh every now and then and it would be nice if somewhere below the graph it would show the Date & Time of the last mesh-update, so I can keep track of it and do an update if it was for example more than 7 days since the last time.

**Comment by jneilliii** [comment]
It should show the last time the level was taken if  you hover your mouse over the info icon on the update button.

**Comment by AcHub** [comment]
I don't get the hover text displayed with Firefox 60.

Independent of this bug(?), maybe the date/time could be displayed next to the button permanently. There is plenty of room and also you wouldn't have to hassle with hovering over a small icon.

**Comment by jneilliii** [comment]
I added this functionality in 0.1.2.  Displays the mesh timestamp status just above the Update button.
