### ISSUE TITLE
Clarifications on leveling adjustments

### ISSUE THREAD

**Issue by larrybud2004** [jneilliii/OctoPrint-BedLevelVisualizer#594]
It's not clear on the "Corrections" tab as to:

"Turn direction - clockwise (right) / anticlockwise (left)"

From which orientation are we to gather from these? Are we looking from the top of the bed, or from under the bed?

**Comment by jneilliii** [comment]
Good question, and technically the answer is either depending on if you set the reverse turn direction option as well.
