### ISSUE TITLE
[FR]: 

### ISSUE THREAD

**Issue by Jeguito** [jneilliii/OctoPrint-BedLevelVisualizer#595]
**Is your feature request related to a problem? Please describe.**

Hi, I have a Prusa i3 MK3S+ connect via Octoprint Raspberry Pi Zero 2 W.

I run your plugin "Bed Level Visualizer" but I don't understand If:

- the measurements I received take in consideration only the physical distances read from the pinda sensor;
or 
- the measurements together with the setting I place in the Printer firmware with the Bed Level Correction.

Thank you for the clarification.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jneilliii** [comment]
I don't have a Prusa so cannot answer this for you. The plugin graphs and calculates adjustment solely based on what the bed mesh report it is given from your firmware.
