### ISSUE TITLE
[BUG]: image problem

### ISSUE THREAD

**Issue by luco85** [jneilliii/OctoPrint-BedLevelVisualizer#599]
Hi i have a visualization problem from today. I not change any parameter on octoprint. only update octoklipper to the last version (2 days ago).
Octoprint v1.8.6

yesterday it work fine, I try to reboot but nothing change

<img width="740" alt="Screenshot 2023-03-01 alle 21 56 35" src="https://user-images.githubusercontent.com/68059403/222263287-34167c45-945f-4e7d-a11c-b7dd99983485.png">

**Comment by jneilliii** [comment]
this usually only happens with the data coming back in your mesh report is missing information, or not an equal sized probing dimensions in the x and y directions (ie doing a 4x8 grid instead of a 4x4 grid).

**Comment by luco85** [comment]
Oh damn! I change 4x4 to 5x3 point for a test. Sorry. Close the ticket
Thanks
