### ISSUE TITLE
Support for Linear / Bilinear ABL

### ISSUE THREAD

**Issue by token47** [jneilliii/OctoPrint-BedLevelVisualizer#6]
Can you support Bilinear Automatic Bed Leveling?

The output looks like this:

Recv: Bilinear Leveling Grid:
Recv:       0      1      2
Recv:  0 +0.027 -0.160 -0.450
Recv:  1 +0.210 -0.020 -0.305
Recv:  2 +0.335 +0.102 -0.197

Thanks!

**Comment by jneilliii** [comment]
Duplicate, already working on it.
