### ISSUE TITLE
[BUG]: Prusa mini example does not work

### ISSUE THREAD

**Issue by Yourigh** [jneilliii/OctoPrint-BedLevelVisualizer#601]
**Describe the bug**
When I copy paste the code from wiki/gcode-examples.md and run bed levelling, I get incomplete table. Also in terminal, I see the disruption. (see log)

**Expected behavior**
Complete bed levelling table. I am able to get complete table with following collection setting.

```
M104 S170		; set extruder temp for bed leveling
M140 S60		; set bed temp
M109 R120		; wait for bed leveling temp
M109 R170		; wait for bed leveling temp
M190 S60		; wait for bed temp
G28			; home all without mesh bed level
G29			; mesh bed leveling
M104 S0			; cool down head
M140 S0			; cooling down the bed
@BEDLEVELVISUALIZER	; instruct plugin to start recording responses from printer.
M420 V ;print result
```

**Debug Log**
Serial output log is below. I think that the output of the G28 command is interfering with the table data. 
```
Send: G28
[...]
Recv: X:176.40 Y:24.10 Z:2.00 E:0.00 Count X:17640 Y:2410 Z:800
Recv: ok
Send: G29
[...]
Recv:  T:169.74 /170.00 B:59.88 /60.00 A:-30.00 /0.00 @:27 B@:32
Recv: Bilinear Leveling Grid:
Recv:       0      1      2      3
Recv:  0 +0.153 +0.070 -0.089 -0.093
Recv:  1 +0.313 +0.243 +0.182 +0.184
Recv:  2+0.393
Recv:  3 +0.137 +0.340 +0.418 +0.468
Recv: 
Recv: X:178.00 Y:176.00 Z:2.00 E:0.00 Count X:17800 Y:17600 Z:1002
```

**Screenshots**

**Firmware and Version**
Prusa mini 4.4.1

EDIT: clarified the issue.

**Comment by jneilliii** [comment]
that's odd, never had anyone report a timing issue with G28/G29. other options might be using dwell (G4) command rather than the temp trick you figured out.

**Comment by Yourigh** [comment]
I edited the issue. 
In fact, when I run it manually it also did not work every time. 

I found a command that can report the last mesh bed levelling, and so fat that works well.  The config is in original post.

**Comment by Yourigh** [comment]
I suspect, there is some issue with my setup. I am running octoprint on Octo4a.
With the config above it works on one android device.
Closing for now.
