### ISSUE TITLE
[BUG]: save mesh deletes custom control buttons after restart

### ISSUE THREAD

**Issue by 2404037558** [jneilliii/OctoPrint-BedLevelVisualizer#608]
**Describe the bug**

create some custom buttons using the custom controls plugin, f5 reload the page, goto bedlevelvisualizer, check save mesh, reload mesh, and your custom controls button are gone!
**Expected behavior**

OF COURSE THE BUTTONS SHOULD STAY!
**Debug Log**

since the plugin itself works fine I don't think a log is needed
**Screenshots**

https://youtu.be/8TSV4hK8w2w
**Firmware and Version**

OctoPrint 1.8.7Python 3.9.2OctoPi 1.0.0 BedLevelVisualizer 1.1.1

**Comment by jneilliii** [comment]
This is not a bug with this plugin, but with how that plugin is loading/saving data. I recommend you set your custom controls the way you want them and then disable the custom controls plugin. The buttons will still be there and function as that is part of the core code of OctoPrint.
