### ISSUE TITLE
[FR]: Verify before running (after opening tab)

### ISSUE THREAD

**Issue by lucidnx** [jneilliii/OctoPrint-BedLevelVisualizer#613]
**Is your feature request related to a problem? Please describe.**
I have script configured to run bed mesh leveling, then trigger visualiser and report values. I had 2 headaches by accidentaly tapping on visualiser tab and print head crashed into printed parts after printing was done becasue it just always start right after opening visualiser tab.

**Describe the solution you'd like**
Simple button to start or Yes/No confirmation box before running script.

**Comment by jneilliii** [comment]
If you check the box to save mesh then the plugin will not try to run the commands when you switch to the tab like that. It doesn't save it to EEPROM, but internally to OctoPrint to avoid your exact situation.
