### ISSUE TITLE
installing Pillow failed due to "python setup.py bdist_wheel did not run successfully"

### ISSUE THREAD

**Issue by DreadednesS** [jneilliii/OctoPrint-BedLevelVisualizer#615]
I'm a newcomer.
I realized that the error was not contributed to pip file errors, after installing and upgrading everything I could, the program was still stuck. How to solve the problem or what I'm missing? (Note: I had tried using numpy but didn't work.)

**Comment by jneilliii** [comment]
really need to see the full error log, but pillow install failing makes me believe the dependency is failing to install. numpy is no longer a requirement for this plugin, so unrelated.

**Comment by jneilliii** [comment]
what's even stranger is that the plugin doesn't use pillow either, so are you filing your issue to the right plugin repo?
