### ISSUE TITLE
[FR]:  A delay time while it preheats the bed to measure the mesh

### ISSUE THREAD

**Issue by erikcsellers** [jneilliii/OctoPrint-BedLevelVisualizer#623]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by erikcsellers** [comment]
no problem, just would be nice if it was actually to temperature before it starts.

**Comment by jneilliii** [comment]
not sure I understand what you mean?

**Comment by erikcsellers** [comment]
Sorry never mind, I guess it already is preheating the bed. I was just impatient

**Comment by jneilliii** [comment]
Yeah, preheating the bed is just another gcode line you put in the settings (prior to `@BEDLEVELVISUALIZER`), so as long as you put the correct commands it should do that for you. If you want to sit on a specific temperature after reaching temp you could probably use a dwell command [G4](https://reprap.org/wiki/G-code#G4:_Dwell) to basically tell the printer to wait a period of time before running the next command.
