### ISSUE TITLE
Adjustment Angle Data

### ISSUE THREAD

**Issue by rightonthedot** [jneilliii/OctoPrint-BedLevelVisualizer#624]
**Is your feature request related to a problem? Please describe.**

The Mesh Z Height and Adjustment Angle data table shows values for every 10mm-15mm, or to some auto-fit function. The actual measured data is from a grid of points, so a bulk of that data is interpolated and not very helpful (which number is actually look at??)

**Describe the solution you'd like**

1 - Display values only at points where actual data was measured. The XY values should be the same as the points that are physically measured.... 

2 - Allow the user to define where their bed adjustments are located, and give interpolated dated for those specific points.

The first solution is great for determining the overall quality of the bed, the second solution is helpful to tramming operations. This is in context of an Ender3.

**Describe alternatives you've considered**

I try to find which value is closest to my actual adjustment points and go from there. 

**Additional context**

![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/139813037/5fca054f-adb9-4ffd-baea-ed78bec34261)

**Comment by jneilliii** [comment]
> The Mesh Z Height and Adjustment Angle data table shows values for every 10mm-15mm, or to some auto-fit function. The actual measured data is from a grid of points, so a bulk of that data is interpolated and not very helpful (which number is actually look at??)

This is what your printer's firmware is doing. The plugin doesn't interpolate this data, it's derived exactly from the information provided by the firmware.

I'm not 100% sure, but enabling the ignore correction matrix option on the collection tab of the plugin may actually get you the actually probed points and not the full interpolated grid. It's been a while since that option was added, and just can't remember if that was for this issue or not.

**Comment by rightonthedot** [comment]
ahhh that makes snese. The Ignore Correction Matrix didn't change the view, but that's ok. 

Could you use that data set to output Z-delta at four specific points? IE: x-y. 15-15, 205-15. 205-205. 15-205? These would give me the adjustments needed directly at each adjustment point...

**Comment by jneilliii** [comment]
IIRC the current RC version has a reference plane option that will calculate averages of the quadrants and display a 4 point plane in the graph. That is close to what your asking for.

**Comment by jneilliii** [comment]
Alternatively, you may want to check out the autobim plugin. It allows for adjusting specific points while probing over and over.

**Comment by rightonthedot** [comment]
I'll check it out! Thank you!
