### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Sandrock431** [jneilliii/OctoPrint-BedLevelVisualizer#628]
**Describe the bug**
Unable to load existing Klipper bed mesh into visualizer (instead of having to run the mesh calibration each time).

**Expected behavior**
Using only the configuration below should be enough to load an existing Klipper bed mesh into the visualizer:
```
@BEDLEVELVISUALIZER	; instruct plugin to start recording responses from printer.
BED_MESH_OUTPUT		; report the bed leveling mesh points.
```

**Debug Log**
[plugin_bedlevelvisualizer_debug.log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/12503313/plugin_bedlevelvisualizer_debug.log)

**Screenshots**
<img width="728" alt="image" src="https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/42790049/0d2e4758-4bbc-44cd-8737-0692f1ce59aa">
<img width="732" alt="image" src="https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/42790049/9abfe13d-039e-40c6-9cf6-4b2901f9bf0b">
<img width="732" alt="image" src="https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/42790049/5176bf1a-4631-499f-9736-8f5f84abb7ca">
<img width="725" alt="image" src="https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/42790049/2ce53e1d-df78-4c36-8b89-c6e6e71e64b6">
<img width="731" alt="image" src="https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/42790049/a398e40a-e1ef-44a4-a8b3-4f9ac4f6977d">
<img width="735" alt="image" src="https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/42790049/a8d7f2a7-8f59-467f-8cde-e76d5e3b3bd1">

**Firmware and Version**
FIRMWARE_VERSION:v0.10.0-913-g5f990f93 FIRMWARE_NAME:Klipper

**Comment by jneilliii** [comment]
so, I don't know anything about how klipper works and based on your debug log the plugin is not receiving any mesh data from klipper whatsoever. If you send the command `BED_MESH_OUTPUT` in the terminal tab what is returned?

**Comment by Sandrock431** [comment]
Hmm. It looks like the Klipper behavior changed while I was away. It used to load the mesh by default, but it doesn't now. I'm able to create the behavior I expected with the sample below. It might be useful to update the visualizer documentation to include a snippet about loading the already-probed mesh:
```
BED_MESH_PROFILE LOAD=default
@BEDLEVELVISUALIZER	; instruct plugin to start recording responses from printer.
BED_MESH_OUTPUT		; report the bed leveling mesh points.
```

Thanks for hearing me out. I'll close this thread. P.S. Love the plugin!
