### ISSUE TITLE
Today's update 6/10/18

### ISSUE THREAD

**Issue by bill-orange** [jneilliii/OctoPrint-BedLevelVisualizer#63]
I am running a PI B+ I loaded today's update to bed visualizer. It displayed the existing mesh okay but when I tried updating the mesh, Octopi hung.  The extruder did not move and the Updating mesh message was displayed forever.  The only way I found to recover was to reboot the PI.  I tried it twice with the same result just to be sure.  I have not tried uninstalling the App and reinstalling it.  I needed the machine this afternoon.

**Comment by jneilliii** [comment]
That would be odd, as the only change that was made was to the tab's ui, no processing changes were made at all.

**Comment by bill-orange** [comment]
I can try uninstalling and reinstalling when the machine is not busy. I can add that when I hit the update button gcodes are no longer sent to the printer.

**Comment by jneilliii** [comment]
Check the logs too to see if there are any other errors. Copy/paste the terminal tab wrapped with 3 back ticks on each side so the formatting stays in tact.

**Comment by bill-orange** [comment]
Will do. Current print job has a ways to go.

**Comment by bill-orange** [comment]
Where are the logs stored?

**Comment by jneilliii** [comment]
In the octoprint's settings there is a logging section where you can download octoprint.log.

**Comment by bill-orange** [comment]
Hopefully will check later today.  May be the same problem as reported by @roofg

**Comment by jneilliii** [comment]
If it's the same issue as @roofg then setting the gcode commands in the plugin settings to something like the following should fix it. The key point on the GCODE command is that the flag `@BEDLEVELVISUALIER` needs to be as close to the reporting command as possible to start the data collection process correctly. It stops collecting when it receives an ok response from the printer after that command.  So if you don't include that flag in your settings it will stop collecting after the first command in the settings was sent.  If that's not a bed leveling report then it never gets the data to render correctly.

```
G28
M155 S30
@BEDLEVELVISUALIZER
G29 T
M155 S3
```

**Comment by bill-orange** [comment]
I will try to test tomorrow.  Here's my current script now. Do I need the M420 V
G28
M155 S40
@BEDLEVELVISUALIZER
G29 T
M155 S3
M420 V

**Comment by jneilliii** [comment]
No, probably not.  also, make sure the `@BEDLEVELVISUALIZER` is all caps.

**Comment by aystoll** [comment]
Hi, 
i have the same issue since update to plugin version 0.12. After new installation of the plugin 0.12 the issue came up again. Now I'm back on version 0.11 and have six bedleveling processes displayed without issues.
No issues in any logs found for 0.12, but did only work one time after a reboot of the pi with version 0.12.

0.11 works without any issues on my side.

**Comment by jneilliii** [comment]
In order to debug your issue, I'll need more details. For example, what are your gcode commands setting used and what is returned in the terminal tab when those commands are run?
