### ISSUE TITLE
[BUG]: OctoDash web page needs authentication

### ISSUE THREAD

**Issue by jneilliii** [jneilliii/OctoPrint-BedLevelVisualizer#632]
**Describe the bug**
When using the `[!WEB]http://127.0.0.1/plugin/bedlevelvisualizer/bedlevelvisualizer` address for custom action in OctoDash the update mesh button no longer works. 

**Expected behavior**
To send the commands configured in plugin's settings

**Debug Log**
n/a

**Screenshots**
![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/5249455/0ba5aa43-7e27-42f9-b59d-7f49474aa40b)

![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/5249455/0d5cd32f-b403-4aed-90e6-d6b4e28552ec)

**Firmware and Version**
n/a

**Comment by jneilliii** [comment]
Actually related to missing api key. added key to update mesh request. Brought up in https://github.com/UnchartedBull/OctoDash/issues/2887. Added in above commit. releasing v1.1.2rc7 to address.

**Comment by atax112** [comment]
Thank you for the quick response. I am currently running a print, but will update ASAP

I just replace the files right? Never installed or updated anything outside of the UI or CLI
![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/67806137/806e8586-d2d4-478d-b47e-26ce80b828ed)

**Comment by jneilliii** [comment]
Easiest method is go into OctoPrint's software update settings and change the release channel for the plugin to release candidate. You will be pumped to upgrade.

**Comment by atax112** [comment]
Alright, I assume I cant see the plugins in the software update page since Im running a print and they are not manageable during jobs. Will check again after its done printing in a couple of hours.

![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/67806137/908db6e5-1cdf-4814-a223-d275ac01e5ff)

**Comment by jneilliii** [comment]
I'm not sure on that front, but if you don't see anything other than OctoPrint in that list after the print is complete then there's something else breaking the software update list. I've seen where on safari browsers you might not see the scroll bar, if that's the case for you. 

![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/5249455/2f86943b-247d-487e-8242-d5e19c596ce9)

**Comment by atax112** [comment]
Hmm, running on brave/chromium, will investigate after the print is done. 3.5h left but that will also be the middle of the night. I'll get back to you in the morning. Thanks a bunch.

**Comment by atax112** [comment]
Ok, so no plugins on the software update page...strange.

So can I replace the files as mentioned before for now? I'll figure out the update page issue later.

**Comment by atax112** [comment]
I actually forgot I can manually upload and install packages in the UI 😅

Installed rc7, updated mesh, tried the custom action.

It loads from the notification screen and the button works!

Would be great if I could directly trigger an update with a custom action but still good either way, I don't need to do it from PC or phone when I'm at the printer.

Thank you!

**Comment by atax112** [comment]
Any way to move the variance data back in its original place and make it visible again? For me it is obscure with a grey background on the left now, not readable in the  UI

![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/67806137/0a8891fc-1730-4be4-81b9-75eb8b3927e2)

**Comment by jneilliii** [comment]
Check settings, I think there's options for where to place it. If you can't find it please open separate issue for that.

**Comment by Bond-Addict** [comment]
Just tried to do this myself. OctoDash asks me if I want to execute the command, but then doesnt do anything.

**Comment by Bond-Addict** [comment]
![Image](https://github.com/user-attachments/assets/5f9fe9b7-514f-4ac7-920c-62b41bf56d20)

![Image](https://github.com/user-attachments/assets/a664245c-380e-472a-9906-ab093a924092)

**Comment by jneilliii** [comment]
There's a bug in OctoDash that webcam embedded iframes don't load if you open from the main panel. If you swipe the notification panel down and click the button from that view it should load.
