### ISSUE TITLE
[BUG]: Mesh statistics not readable since rc7 update

### ISSUE THREAD

**Issue by atax112** [jneilliii/OctoPrint-BedLevelVisualizer#633]
**Describe the bug**
After jumping from 1.1.1 to rc7 to fix #632 mesh statistics are not readable by default. Background of the page section is opaque and position is to the left. No option in settings to move or change style from what Ive checked, only to enable/disable statistics.

![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/67806137/19ead4d1-ed9f-456f-990e-e39697ea114f)

When inspecting the elements in the browser I was able to modify css to get a transparent background but that is not a permanent fix.
![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/67806137/8adbc6d4-7b86-4b22-896c-81485ebbb9a2)

**Expected behavior**
Data was shown without opaque background on right side of plotted data, expected the same after update.

**Firmware and Version**
1.1.2rc7

**Comment by jneilliii** [comment]
Which theming application and theme are you using?

**Comment by atax112** [comment]
UI customizer, Discoranged theme, tried different but didnt help
![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/67806137/102fcf30-a99b-4af8-94cd-698d99fc1e6b)

**Comment by jneilliii** [comment]
Ok, thanks. That's the same I use (I ported that theme to UI customizer) and don't remember seeing the same symptom. I'll investigate further.

**Comment by atax112** [comment]
Yeah I figured it wont be that, been using the theme with BLV 1.1.1 as well and it was ok...

**Comment by jneilliii** [comment]
Might need some more details. Please share your settings for both UI Customizer and BLV plugins. I just installed on my work machine and am not reproducing the same thing as you are seeing. 

![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/5249455/17f4d0ad-0c6b-4310-92bd-41f72862e3e2)

**Comment by atax112** [comment]
It had to get moved at some point because in 1.1.1 the data was on the right side.

I also thought that some theme setting might interfere with the rc version style, but I havent change anything nor see anything suspicious.

UI Customizer:
![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/67806137/429c3515-46fa-414d-9e7e-f9e66eeeaf53)
![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/67806137/e6d48901-ae59-497f-a160-1c5b3c90cc08)
![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/67806137/94defb82-f621-44f4-812a-be9162a13934)
![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/67806137/6fd8b938-8268-4620-81aa-efb4afc1f707)
![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/67806137/3f98b256-51c7-40ce-8340-ac5efef11016)


BLV:
![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/67806137/45ef645e-9864-491d-a7f7-8bd8bae2dead)
![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/67806137/3d3fb7f2-32ea-4d64-9cfd-e37d385205bc)
![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/67806137/af71911a-7389-4a4c-9400-2b4f6cc7708a)

**Comment by atax112** [comment]
Found it, its somehow browser related...
Chrome on the left is fine, although the readout is still on the left instead of right as before.

In brave on the right there has to be some dark theme, inverting whatever going on which isnt 100%
![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/67806137/cd4d20a3-3c0c-421e-86f5-f2ac5051f0c4)

**Comment by jneilliii** [comment]
> Chrome on the left is fine, although the readout is still on the left instead of right as before.

Yeah, I made that change for a reason, related to the addition of UBL data in 1.1.2rc1. With the block on the right it got too tall and was causing issues. This might be able to be overwritten with the new advanced section added in 1.1.2rc4. I'll test and see if I can provide a solution for that. 

It's odd that brave would work fine before, the rendering of the graph didn't change much outside of the positioning of those blocks.

**Comment by atax112** [comment]
Ok cool.

> It's odd that brave would work fine before, the rendering of the graph didn't change much outside of the positioning of those blocks.

yeah it has to do with this setting, it is odd, since with the 1.1.1 version there was no issue at all regardless. Probably some class, section, part of the page changed that the dark mode setting now involves that part as well, not like before.

![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/67806137/3bd7a4ce-0d21-44b5-8513-e592dff0379a)

**Comment by jneilliii** [comment]
Unfortunately, it doesn't look like the advanced settings are going to cut it for this because the annotation's text is being dynamically generated. I'll look into make the position configurable in the future.

**Comment by atax112** [comment]
Oh I see.

I think there are other, more important features to put effort into, I dont mind it on the left, just thought that also something broke the position.

up to you at this point if you find the time.

thank you for the help
