### ISSUE TITLE
[FR]:  change the font color in the gui,  red and blue are hard on the eyes

### ISSUE THREAD

**Issue by coreburner** [jneilliii/OctoPrint-BedLevelVisualizer#634]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jneilliii** [comment]
This can be adjusted with any of the various styling plugins. UI Customizer would be the one I would personally recommend. You can find the styles you can adjust in the wiki [here](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/blob/master/wiki/index.md#theme-support).
