### ISSUE TITLE
[BUG]: Rendering Mesh display error

### ISSUE THREAD

**Issue by Sleeepy2** [jneilliii/OctoPrint-BedLevelVisualizer#639]
While using RC 1.1.2rc7 switching to the BLV tab pops up and error in chrome and edge.
No issues running the level just switching to the tab.

Using OctoPrint 1.9.3 Python 3.9.2 OctoPi* 1.0.0cam (build 2023.07.20.144556)

[plugin_bedlevelvisualizer_debug.log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/13288992/plugin_bedlevelvisualizer_debug.log)

![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/1533684/4f695c30-ec34-4083-9886-0f3b64c02e92)

![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/1533684/427ccffd-ab8d-47cf-ab93-39892cc970ff)

![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/1533684/7bd2c10e-8114-4586-b232-1c6080471f70)

![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/1533684/be8fc698-dfd3-41ac-95dc-f1df5546c8f8)

**Comment by jneilliii** [comment]
I think I'll need one more bit of information @Sleeepy2 as I couldn't reproduce with just the points and got this result.

![image](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/5249455/8bc92ec3-6ed3-4fb3-8933-8b9ec983f924)

Could you enable serial logging for me and run through the process and then disable it and upload your serial.log please?

**Comment by jneilliii** [comment]
Oh, and another thing. Could you provide your octoprint.log too so I can get the full list of the plugins you have installed. It's possible there is a plotly version issue if that's bundled in another plugin (ie Tasmota, TPLink SmartPug, PlotlyTempGraph).

**Comment by Sleeepy2** [comment]
The Tasmota RC plugin fixed the issue. Looks like you were right and it's a plotly versions issue.
