### ISSUE TITLE
Plugin hangs if printer was not homed beforehand

### ISSUE THREAD

**Issue by roofg** [jneilliii/OctoPrint-BedLevelVisualizer#64]
I used the plugin for the first time today. Hit the button and the serial output told me i need to home xyz first. The plugin got stuck on the "Please wait, retrieving current mesh"-message had to restart the pi to be able to access the plugin again.

cheers and thanks for your work on this project

**Comment by jneilliii** [comment]
Change your gcode commands in the plugin settings to include the G28 if necessary.  So something like this.

```
G28
M155 S30
@BEDLEVELVISUALIZER
G29 T
M155 S3
```
