### ISSUE TITLE
[FR]: Update mesh display through start GCODE

### ISSUE THREAD

**Issue by AlfonsoDehesa** [jneilliii/OctoPrint-BedLevelVisualizer#641]
**Describe the solution you'd like**
Possibility to update bed mesh display outside of plugin's tab or plugin's routine. Be able to have the display updated by calling out `@BEDLEVELVISUALIZER` on either the slicer or octoprint's start GCODE.

**Comment by jneilliii** [comment]
You can, the plugin reacts to that command so if you add it to your start gcode in slicer prior to the g29 command it well pick it up.
