### ISSUE TITLE
[FR]: Selectable bed temperature without having to rewrite the gcode strings

### ISSUE THREAD

**Issue by cyberjak2k** [jneilliii/OctoPrint-BedLevelVisualizer#647]
**Is your feature request related to a problem? Please describe.**
If you aren't always using one material type then the ability to re make your mesh using the appropriate temperature is required

**Describe the solution you'd like**
A dropdown where you can select preset gcodes for each material profile you plan to use so it preheats the bed to that temp before starting a mesh. have a gcode section in settings for up to at least 4 profiles  that you can name
**Describe alternatives you've considered**
having to keep rewriting the gcode each time you have to change to a higher or lower bed temp which is time consuming 

**Additional context**

**Comment by jneilliii** [comment]
That's what the Commands were intended for. You can add an input that allows for setting temperature and sending the commands.
