### ISSUE TITLE
Does BedLevelVisualizer work with Repetier firmware? 

### ISSUE THREAD

**Issue by bumbalu** [jneilliii/OctoPrint-BedLevelVisualizer#65]
And if it does what would be the GCODE? G29 T produces different output in Repetier than in Marlin. 
Thank you.

**Comment by jneilliii** [comment]
I would have to see the output of the G29 T command from your printer to say for sure.

**Comment by bumbalu** [comment]
This is what is produced by G29 T command, it measures only 3 points (corners) of the table height:
Send: N18 G29 T*95
Recv: ok 18
Recv: Info:Autoleveling disabled
Recv: Z-probe:20.580 X:-0.01 Y:0.00
Recv: Z-probe:20.588 X:159.00 Y:0.00
Recv: Z-probe:20.560 X:-0.01 Y:144.00
Recv: Z-probe average height:20.58
Recv: Info:Autoleveling enabled

**Comment by jneilliii** [comment]
Unfortunately, that format will not work with this plugin.

**Comment by bumbalu** [comment]
Ok, thank you.

**Comment by jneilliii** [comment]
What does your printer report with `G33 L0`?

**Comment by bumbalu** [comment]
Thank you so much for nice & useful plugin! Now it supports Repetier firmware. I just want to report that my working gcode is as following: 
G28
M155 S30
G32
@BEDLEVELVISUALIZER
G1 X0 Y0
G33 
M155 S3
If there is no line "G1 X0 Y0" before G33 than at the end of G32 command firmware "thinks" that Z-probe is at the X0 Y0 position (but it is not) and executing G33 with move the Z-probe out of printing area. And here firmware reports an error. Because of this lets move the Z-probe to real X0 Y0 position before G33 and everything will be fine.
