### ISSUE TITLE
[FR]: An arrow to show which direction is "forward" (front of printer) on the graph

### ISSUE THREAD

**Issue by Aalexz** [jneilliii/OctoPrint-BedLevelVisualizer#651]
Title is self explanatory (hopefully!)

Thanks, sorry if this is a feature and I've just not looked hard enough.

**Comment by jneilliii** [comment]
Technically that's what the 0 number is on the X axis, which is colored red in the visualization. The trick is making sure the graph is aligned to real world. Typically the best way to do this is putting a business card in the front right corner while probing and then identify the position of the bump in the graph and adjust the flip options accordingly.

**Comment by Aalexz** [comment]
Thanks.

**Comment by Aalexz** [comment]
I don't think you should close this. It is a good feature request to help out beginners.
