### ISSUE TITLE
[FR]: output block in custom commands

### ISSUE THREAD

**Issue by Ingegneus** [jneilliii/OctoPrint-BedLevelVisualizer#655]
hi, I think it would be a useful addition to the custom commands that are currently supported, to also be able to capture the output of those commands. or more generally display the responses of the printer based on custom rules/regex. 
this comes straight from my usecase, where I am trying to accurately measure the z probe offset and I use buttons to lower the printhead and then checking if the z probe is triggered with the M119 command. right now I am doing this in the terminal, but it would be way more elegant and convenient to do this with buttons. 
thank you for this really useful plugin and your 10000 other plugins! you are a legend

**Comment by jneilliii** [comment]
duplicate #315
