### ISSUE TITLE
No visualization in the chart, but data is captured correctly

### ISSUE THREAD

**Issue by Vernnis** [jneilliii/OctoPrint-BedLevelVisualizer#660]
Hello,
my Printer is the Anycubic Kobra Max.
My problem is that I can't see anything displayed in the coordinate system. As far as I can see, the data is recorded correctly, right?
Thanks in advance and greetings from Germany!
![Bildschirmfoto 2024-03-28 um 22 11 14](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/assets/165330208/87f42f15-f762-44a3-8493-46e621c212da)
[plugin_bedlevelvisualizer_debug.log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/14795643/plugin_bedlevelvisualizer_debug.log)

**Comment by jneilliii** [comment]
all your points are outside the z limits. if you enable the option to use relative z offset and re-run the collect mesh process the graph will show for you.
