### ISSUE TITLE
[FR]: Probe offset

### ISSUE THREAD

**Issue by danielbaleanu** [jneilliii/OctoPrint-BedLevelVisualizer#662]
**Is your feature request related to a problem? Please describe.**
Actual bed probe points are shifted all the way across the bed surface within the visualiser mesh

**Describe the solution you'd like**
An option that would allow the user to enable the visualiser to keep account of the probe offsets

**Describe alternatives you've considered**
For the rest of the mesh could be used a function such as EXTRAPOLATE_BEYOND_GRID or simply maintain the height of the nearest edge (Marlin default)

**Additional context**
My bed size (firmware defined & octoprint defined is 215 x 215) & my CR Touch probe on the X axis is 45 mm to the left of the nozzle (-45); The visualiser is placing the right edge/margin points on 215 mm X coordinates instead of 170 mm X coordinates (215 - 45 = 170 mm)

**Comment by jneilliii** [comment]
Feature already in latest release candidate version.
