### ISSUE TITLE
[FR]: Bed Visualizer Select Temp

### ISSUE THREAD

**Issue by LaserPix** [jneilliii/OctoPrint-BedLevelVisualizer#664]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to be able to set, through checkboxes or fields, the temperature to set the bed to for probing / visualizing, rather than having to edit the GCode. Or, perhaps, let us create editable profiles that would set temps (TPU=low/none, PLA=60, ABS=100, etc...)

**Comment by LaserPix** [comment]
Upon further adjusting (as is) I see that this may be moot, as the G29 will still set the bed to whatever is configured in Marlin, so this may actually not be possible.

**Comment by jneilliii** [comment]
> G29 will still set the bed to whatever is configured in Marlin

That may be specific to your firmware, it doesn't do anything for me when I just send G29, bed remains off unless I set it to temp. 

You could achieve this using the Commands tab. I know some users use that for configuring multiple slots in UBL for different materials, and then in their slicer profile they use filament specific gcode commands to load the appropriate slot number. There are some examples documented on the wiki [here](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/blob/master/wiki/index.md#commands).
