### ISSUE TITLE
IDEA: Detect probe points that is "abnormal" and probe arround that point

### ISSUE THREAD

**Issue by boelle** [jneilliii/OctoPrint-BedLevelVisualizer#67]
Would it be possible for this plugin to have a feature where it can find false trigger points and probe maybe 1-2 mm away and calculate an avg value?

i found that on my MK42 bed if it probes on top of a screw it triggers different... or if it probes on one of the 9 probe points it triggers at another level, so i can risk up with 3 different levels

what i had in mind was a setting of how much probes can deviate from others... let pick an extreme number of 2mm... if a probe point sticks 2mm up above all the others that point would be "abnormal" , but if we move half way between that point and a good point we might be able to get another good probe point and we can calculate a good educated guess value

maybe this picture can explain it

![image](https://user-images.githubusercontent.com/3832239/41499803-003273a4-7187-11e8-99c1-9079b540f4dc.png)

the blacks are good probe points, the red if the bad one, the green is the extra points needed to make a guess on what the red should have been

**Comment by jneilliii** [comment]
That's more of a firmware related request, this plugin just pulls the data from the firmware to visualize it.
