### ISSUE TITLE
[FR]:  Improved Display of Correction Angles and Screw Adjustment Calculations in OctoPrint Bed Visualizer

### ISSUE THREAD

**Issue by obilger** [jneilliii/OctoPrint-BedLevelVisualizer#673]
**Is your feature request related to a problem? Please describe.**

Currently, the plugin provides a detailed visualization of the bed level and displays the correction angles in a table format with X=0 and Y=0 positioned at the top left, corresponding to the front-left corner of the bed. While this information is useful, I believe it would be much easier to interpret if these values were displayed directly on a top-down view of the bed, including the positions of the four leveling screws.

**Describe the solution you'd like**

Here are the specific features I am proposing:

Top-Down Bed View with Correction Angles: Display the correction angles on a visual representation of the bed as seen from above, with clear indications of the positions of the four leveling screws. This would provide a more intuitive understanding of the bed's tilt and necessary adjustments.
Screw Adjustment Calculations: In addition to displaying the correction angles, calculate and show the exact adjustments needed for each bed leveling screw. This would make the leveling process more straightforward and precise, helping users achieve a perfectly leveled bed more efficiently.

**Comment by jneilliii** [comment]
You can change the orientation of the data tables (including adjustments) using the options in the plugin, to make the 0,0 point to be bottom left. 

![image](https://github.com/user-attachments/assets/2145bebb-7cdb-4cba-9727-a96cf2b372bc)

You can also click on any point in the table to make that the "0" z height and the numbers will change. That being said, I've never really been happy with the adjustment table (was contributed by someone else) and never use it. I use my bed leveling wizard plugin or the autobim plugin for getting the adjustments done. In fact, in the current RC versions I was working on removing the adjustment table and putting those turn directions/amounts into the probe point hover details (still working on it as you can tell). 

![image](https://github.com/user-attachments/assets/8f14be6e-33a0-4f73-b7f7-b4894d38e1ab)

You'll notice that not just the angles are shown on the table. When you hover your mouse over the table cells or in the rc version, the points on the mesh, it shows the number of turns on the right, not just the angle.

**Comment by obilger** [comment]
thanks for your answer, is this screenshot from a newer version ? I don't see options like descending X/Y axis 
<img width="715" alt="Screenshot 2024-12-03 at 16 53 05" src="https://github.com/user-attachments/assets/8ac11fdd-2751-4e47-83cb-e0a6bb8ccb38">

**Comment by jneilliii** [comment]
It's on the data tab, not the corrections tab. That setting will effect both tables.
