### ISSUE TITLE
Is manually updating BedLevelVisualizer necessary?

### ISSUE THREAD

**Issue by Savage223** [jneilliii/OctoPrint-BedLevelVisualizer#69]
I'm brand new to 3d printing and I don't yet know enough to know what I don't know, if you get my drift.
My Tevo Black Widow with Marlin, BL Touch, and Octoprint works great, including the BedLevelVisualizer plug in because I'm good at blindly following instructions even if I don't fully understand them.

When send a print to my printer it first performs an auto home and then does a bed leveling procedure and then proceeds to print normally.  That's fine. 

However, the bed leveling graphic isn't updated.  It continues to show information from the last time I clicked the "UPDATE" icon.  It seems to me that there must be a simple G Code I can insert somewhere so that BedLevelVisualizer retrieves the data from the normal pre-print bed leveling routine which happens before every print and then will display that up-to-the-minute data as the current state of my bed.

Can anyone guide me?  Remember, I'm a complete novice.

**Comment by jneilliii** [comment]
If you update your auto leveling gcode in your slicer's start gcode setting to include `@BEDLEVELVISUALIZER` just prior to the G29 command it should update the mesh every time.

**Comment by Savage223** [comment]
Here's what the G-Code commands in the BedVisualizer plug-in associated with Octoprint looks like:

**m155 S30
@BEDLEVELVISUALIZER
G29 T
M155 S3**

Are you saying I should add @BEDVISUALIZER again in the G-Code produced by Cura when it slices the print and generates G-Code?

**Comment by jneilliii** [comment]
You need to add that gcode to cura start gcode in place of the current G29 command. Here's a video of where you can find that setting...assuming you're on the same version.

https://www.youtube.com/watch?v=5m5g-5iliwI
