### ISSUE TITLE
Todays Update 08062018 hangs ...

### ISSUE THREAD

**Issue by LachmannM** [jneilliii/OctoPrint-BedLevelVisualizer#75]
I tried updating the plugin from within octopis plugin manager but installation hangs with 
Running setup.py install for numpy: still running...

The same happened after removing the plugin and adding it again ... this time during the installation.

I've added the log file ...

Best regards,
  Michael
[plugin_pluginmanager_console.log](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/files/2262502/plugin_pluginmanager_console.log)

**Comment by akurz42** [comment]
Exactly the same issue here.

**Comment by c3r63ru5** [comment]
I checked and its cc1 running in the background that took approx 15mins on my raspi3. Just give it some time...

**Comment by jneilliii** [comment]
Agreed, it took quite some time for this to update for me as well as it has to pull in an additional library and compile it.  The additional library was for numpy. It will eventually complete the update.
