### ISSUE TITLE
Upgrade to 0.1.4 hangs

### ISSUE THREAD

**Issue by paulr4** [jneilliii/OctoPrint-BedLevelVisualizer#77]
This is on a Raspberry Pi Zero W, the upgrade process has been running half an hour or so; far longer than the initial install. The update window reads the following:

`
Updating, please wait.
Collecting https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.1.4.zip
Downloading https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.1.4.zip (1.0MB)
Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python2.7/site-packages (from Bed-Visualizer==0.1.4) (1.3.9)
Collecting numpy (from Bed-Visualizer==0.1.4)
Downloading https://files.pythonhosted.org/packages/3a/20/c81632328b1a4e1db65f45c0a1350a9c5341fd4bbb8ea66cdd98da56fe2e/numpy-1.15.0.zip (4.5MB)
Requirement already satisfied: flask<0.11,>=0.10.1 in /home/pi/oprint/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (0.10.1)
Requirement already satisfied: Jinja2<2.9,>=2.8.1 in /home/pi/oprint/lib/python2.7/site-packages/Jinja2-2.8.1-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (2.8.1)
Requirement already satisfied: werkzeug<0.9,>=0.8.3 in /home/pi/oprint/lib/python2.7/site-packages/Werkzeug-0.8.3-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (0.8.3)
Requirement already satisfied: tornado==4.5.3 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.4) (4.5.3)
Requirement already satisfied: PyYAML<3.11,>=3.10 in /home/pi/oprint/lib/python2.7/site-packages/PyYAML-3.10-py2.7-linux-armv6l.egg (from OctoPrint->Bed-Visualizer==0.1.4) (3.10)
Requirement already satisfied: Flask-Login<0.3,>=0.2.11 in /home/pi/oprint/lib/python2.7/site-packages/Flask_Login-0.2.11-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (0.2.11)
Requirement already satisfied: Flask-Principal<0.4,>=0.3.5 in /home/pi/oprint/lib/python2.7/site-packages/Flask_Principal-0.3.5-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (0.3.5)
Requirement already satisfied: Flask-Babel<0.10,>=0.9 in /home/pi/oprint/lib/python2.7/site-packages/Flask_Babel-0.9-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (0.9)
Requirement already satisfied: Flask-Assets<0.11,>=0.10 in /home/pi/oprint/lib/python2.7/site-packages/Flask_Assets-0.10-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (0.10)
Requirement already satisfied: markdown<2.7,>=2.6.9 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.4) (2.6.11)
Requirement already satisfied: pyserial<3.5,>=3.4 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.4) (3.4)
Requirement already satisfied: netaddr<0.8,>=0.7.19 in /home/pi/oprint/lib/python2.7/site-packages/netaddr-0.7.19-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (0.7.19)
Requirement already satisfied: watchdog<0.9,>=0.8.3 in /home/pi/oprint/lib/python2.7/site-packages/watchdog-0.8.3-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (0.8.3)
Requirement already satisfied: sarge==0.1.4 in /home/pi/oprint/lib/python2.7/site-packages/sarge-0.1.4-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (0.1.4)
Requirement already satisfied: netifaces<0.11,>=0.10.6 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.4) (0.10.7)
Requirement already satisfied: pylru<1.1,>=1.0.9 in /home/pi/oprint/lib/python2.7/site-packages/pylru-1.0.9-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (1.0.9)
Requirement already satisfied: rsa<3.3,>=3.2.3 in /home/pi/oprint/lib/python2.7/site-packages/rsa-3.2.3-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (3.2.3)
Requirement already satisfied: pkginfo<1.5,>=1.4.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.4) (1.4.2)
Requirement already satisfied: requests<3,>=2.18.4 in /home/pi/oprint/lib/python2.7/site-packages/requests-2.18.4-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (2.18.4)
Requirement already satisfied: semantic_version<2.5,>=2.4.2 in /home/pi/oprint/lib/python2.7/site-packages/semantic_version-2.4.2-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (2.4.2)
Requirement already satisfied: psutil<5.5,>=5.4.6 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.4) (5.4.6)
Requirement already satisfied: Click<6.3,>=6.2 in /home/pi/oprint/lib/python2.7/site-packages/click-6.2-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (6.2)
Requirement already satisfied: awesome-slugify<1.7,>=1.6.5 in /home/pi/oprint/lib/python2.7/site-packages/awesome_slugify-1.6.5-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (1.6.5)
Requirement already satisfied: feedparser<5.3,>=5.2.1 in /home/pi/oprint/lib/python2.7/site-packages/feedparser-5.2.1-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (5.2.1)
Requirement already satisfied: chainmap<1.1,>=1.0.2 in /home/pi/oprint/lib/python2.7/site-packages/chainmap-1.0.2-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (1.0.2)
Requirement already satisfied: future<0.16,>=0.15.2 in /home/pi/oprint/lib/python2.7/site-packages/future-0.15.2-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (0.15.2)
Requirement already satisfied: scandir<1.4,>=1.3 in /home/pi/oprint/lib/python2.7/site-packages/scandir-1.3-py2.7-linux-armv6l.egg (from OctoPrint->Bed-Visualizer==0.1.4) (1.3)
Requirement already satisfied: websocket-client<0.41,>=0.40.0 in /home/pi/oprint/lib/python2.7/site-packages/websocket_client-0.40.0-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (0.40.0)
Requirement already satisfied: python-dateutil<2.7,>=2.6.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.4) (2.6.1)
Requirement already satisfied: wrapt<1.11,>=1.10.11 in /home/pi/oprint/lib/python2.7/site-packages/wrapt-1.10.11-py2.7-linux-armv6l.egg (from OctoPrint->Bed-Visualizer==0.1.4) (1.10.11)
Requirement already satisfied: futures<3.2,>=3.1.1 in /home/pi/oprint/lib/python2.7/site-packages/futures-3.1.1-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (3.1.1)
Requirement already satisfied: emoji<0.5,>=0.4.5 in /home/pi/oprint/lib/python2.7/site-packages/emoji-0.4.5-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (0.4.5)
Requirement already satisfied: monotonic<1.4,>=1.3 in /home/pi/oprint/lib/python2.7/site-packages/monotonic-1.3-py2.7.egg (from OctoPrint->Bed-Visualizer==0.1.4) (1.3)
Requirement already satisfied: frozendict<1.3,>=1.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->Bed-Visualizer==0.1.4) (1.2)
Requirement already satisfied: itsdangerous>=0.21 in /home/pi/oprint/lib/python2.7/site-packages/itsdangerous-0.24-py2.7.egg (from flask<0.11,>=0.10.1->OctoPrint->Bed-Visualizer==0.1.4) (0.24)
Requirement already satisfied: MarkupSafe in /home/pi/oprint/lib/python2.7/site-packages/MarkupSafe-1.0-py2.7-linux-armv6l.egg (from Jinja2<2.9,>=2.8.1->OctoPrint->Bed-Visualizer==0.1.4) (1.0)
Requirement already satisfied: singledispatch in /home/pi/oprint/lib/python2.7/site-packages (from tornado==4.5.3->OctoPrint->Bed-Visualizer==0.1.4) (3.4.0.3)
Requirement already satisfied: certifi in /home/pi/oprint/lib/python2.7/site-packages/certifi-2017.11.05-py2.7.egg (from tornado==4.5.3->OctoPrint->Bed-Visualizer==0.1.4) (2017.11.5)
Requirement already satisfied: backports_abc>=0.4 in /home/pi/oprint/lib/python2.7/site-packages (from tornado==4.5.3->OctoPrint->Bed-Visualizer==0.1.4) (0.5)
Requirement already satisfied: blinker in /home/pi/oprint/lib/python2.7/site-packages/blinker-1.4-py2.7.egg (from Flask-Principal<0.4,>=0.3.5->OctoPrint->Bed-Visualizer==0.1.4) (1.4)
Requirement already satisfied: Babel>=1.0 in /home/pi/oprint/lib/python2.7/site-packages/Babel-2.3.4-py2.7.egg (from Flask-Babel<0.10,>=0.9->OctoPrint->Bed-Visualizer==0.1.4) (2.3.4)
Requirement already satisfied: speaklater>=1.2 in /home/pi/oprint/lib/python2.7/site-packages/speaklater-1.3-py2.7.egg (from Flask-Babel<0.10,>=0.9->OctoPrint->Bed-Visualizer==0.1.4) (1.3)
Requirement already satisfied: webassets>=0.10 in /home/pi/oprint/lib/python2.7/site-packages/webassets-0.12.1-py2.7.egg (from Flask-Assets<0.11,>=0.10->OctoPrint->Bed-Visualizer==0.1.4) (0.12.1)
Requirement already satisfied: argh>=0.24.1 in /home/pi/oprint/lib/python2.7/site-packages/argh-0.26.2-py2.7.egg (from watchdog<0.9,>=0.8.3->OctoPrint->Bed-Visualizer==0.1.4) (0.26.2)
Requirement already satisfied: pathtools>=0.1.1 in /home/pi/oprint/lib/python2.7/site-packages/pathtools-0.1.2-py2.7.egg (from watchdog<0.9,>=0.8.3->OctoPrint->Bed-Visualizer==0.1.4) (0.1.2)
Requirement already satisfied: pyasn1>=0.1.3 in /home/pi/oprint/lib/python2.7/site-packages/pyasn1-0.2.3-py2.7.egg (from rsa<3.3,>=3.2.3->OctoPrint->Bed-Visualizer==0.1.4) (0.2.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/pi/oprint/lib/python2.7/site-packages/chardet-3.0.4-py2.7.egg (from requests<3,>=2.18.4->OctoPrint->Bed-Visualizer==0.1.4) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /home/pi/oprint/lib/python2.7/site-packages/idna-2.6-py2.7.egg (from requests<3,>=2.18.4->OctoPrint->Bed-Visualizer==0.1.4) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/pi/oprint/lib/python2.7/site-packages/urllib3-1.22-py2.7.egg (from requests<3,>=2.18.4->OctoPrint->Bed-Visualizer==0.1.4) (1.22)
Requirement already satisfied: regex in /home/pi/oprint/lib/python2.7/site-packages/regex-2017.02.08-py2.7-linux-armv6l.egg (from awesome-slugify<1.7,>=1.6.5->OctoPrint->Bed-Visualizer==0.1.4) (2017.2.8)
Requirement already satisfied: Unidecode<0.05,>=0.04.14 in /home/pi/oprint/lib/python2.7/site-packages/Unidecode-0.04.20-py2.7.egg (from awesome-slugify<1.7,>=1.6.5->OctoPrint->Bed-Visualizer==0.1.4) (0.4.20)
Requirement already satisfied: six in /home/pi/oprint/lib/python2.7/site-packages/six-1.10.0-py2.7.egg (from websocket-client<0.41,>=0.40.0->OctoPrint->Bed-Visualizer==0.1.4) (1.10.0)
Requirement already satisfied: backports.ssl_match_hostname in /home/pi/oprint/lib/python2.7/site-packages/backports.ssl_match_hostname-3.5.0.1-py2.7.egg (from websocket-client<0.41,>=0.40.0->OctoPrint->Bed-Visualizer==0.1.4) (3.5.0.1)
Requirement already satisfied: pytz>=0a in /home/pi/oprint/lib/python2.7/site-packages/pytz-2016.10-py2.7.egg (from Babel>=1.0->Flask-Babel<0.10,>=0.9->OctoPrint->Bed-Visualizer==0.1.4) (2016.10)
Installing collected packages: numpy, Bed-Visualizer
Running setup.py install for numpy: started
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...
Running setup.py install for numpy: still running...`

**Comment by jneilliii** [comment]
Mentioned in the release notes, let it continue to run and eventually it will finish.
