### ISSUE TITLE
Don't see result on CR-10S Marlin 1.1.8 BLtouch

### ISSUE THREAD

**Issue by ShagoY** [jneilliii/OctoPrint-BedLevelVisualizer#8]
Hi :)
After a lot of try (G29/G29 T1/etc..) , i don't see result on bedvisualizer tab.

Here screenshot : 
![settings](https://user-images.githubusercontent.com/25367500/38870318-c13fb7f0-424d-11e8-852a-fc4041550cb6.jpg)
![onglet](https://user-images.githubusercontent.com/25367500/38870322-c2897eac-424d-11e8-8f0a-712eeb11ea15.jpg)

**Comment by jneilliii** [comment]
Looks like the data is getting extra information. Cam you send the terminal tab results of the command G29. Also did you try swapping the G29 command with G29 T?

**Comment by ShagoY** [comment]
Same with cmd G9 T

Here my Marlin configuration : 
#define AUTO_BED_LEVELING_BILINEAR
And i use subdivision : 
// Experimental Subdivision of the grid by Catmull-Rom method.
#define ABL_BILINEAR_SUBDIVISION

Send: G29 T
[...]
Recv: Bilinear Leveling Grid:
Recv:       0      1      2      3      4
Recv:  0 -0.132 -0.053 +0.045 +0.133 +0.180
Recv:  1 -0.132 -0.055 +0.015 +0.077 +0.145
Recv:  2 -0.137 -0.082 -0.025 +0.053 +0.080
Recv:  3 -0.120 -0.102 -0.065 -0.005 -0.020
Recv:  4 -0.150 -0.142 -0.132 -0.085 -0.055
Recv: 
Recv: Subdivided with CATMULL ROM Leveling Grid:
Recv:         0        1        2        3        4        5        6        7        8        9       10       11       12
Recv:  0 -0.13250 -0.10648 -0.08046 -0.05250 -0.02093 +0.01259 +0.04500 +0.07639 +0.10667 +0.13250 +0.15130 +0.16565 +0.18000
Recv:  1 -0.13231 -0.10597 -0.07963 -0.05241 -0.02336 +0.00657 +0.03537 +0.06280 +0.08911 +0.11306 +0.13343 +0.15144 +0.16944
Recv:  2 -0.13213 -0.10546 -0.07879 -0.05231 -0.02579 +0.00054 +0.02574 +0.04921 +0.07156 +0.09361 +0.11556 +0.13723 +0.15889
Recv:  3 -0.13250 -0.10639 -0.08028 -0.05500 -0.03083 -0.00750 +0.01500 +0.03620 +0.05657 +0.07750 +0.09963 +0.12231 +0.14500
Recv:  4 -0.13463 -0.11036 -0.08608 -0.06259 -0.04043 -0.01905 +0.00241 +0.02453 +0.04673 +0.06815 +0.08824 +0.10754 +0.12685
Recv:  5 -0.13731 -0.11576 -0.09421 -0.07296 -0.05264 -0.03262 -0.01130 +0.01343 +0.03945 +0.06213 +0.07878 +0.09207 +0.10537
Recv:  6 -0.13750 -0.11926 -0.10102 -0.08250 -0.06426 -0.04574 -0.02500 +0.00120 +0.02963 +0.05250 +0.06537 +0.07269 +0.08000
Recv:  7 -0.13157 -0.11771 -0.10385 -0.08898 -0.07325 -0.05652 -0.03731 -0.01198 +0.01583 +0.03657 +0.04471 +0.04578 +0.04685
Recv:  8 -0.12315 -0.11425 -0.10536 -0.09463 -0.08165 -0.06684 -0.04963 -0.02628 -0.00051 +0.01704 +0.02010 +0.01496 +0.00981
Recv:  9 -0.12000 -0.11491 -0.10981 -0.10250 -0.09231 -0.07991 -0.06500 -0.04389 -0.02028 -0.00500 -0.00444 -0.01222 -0.02000
Recv: 10 -0.12648 -0.12306 -0.11964 -0.11435 -0.10695 -0.09768 -0.08546 -0.06665 -0.04488 -0.03000 -0.02757 -0.03203 -0.03648
Recv: 11 -0.13824 -0.13533 -0.13241 -0.12843 -0.12384 -0.11819 -0.10898 -0.09272 -0.07290 -0.05750 -0.05064 -0.04819 -0.04574
Recv: 12 -0.15000 -0.14759 -0.14519 -0.14250 -0.14074 -0.13870 -0.13250 -0.11880 -0.10093 -0.08500 -0.07370 -0.06435 -0.05500
Recv: 
Recv: X:292.00 Y:255.00 Z:11.47 E:0.00 Count X:23360 Y:20400 Z:4580

**Comment by Desterly** [comment]
@ShagoY do you have any other plugins that utilize plotly installed?  I just ran across a conflict with the Tempsgraph plugin that results in the same issues you are seeing.   If you open your browser debugger, see if you are getting any errors on the console when selecting the bedlevelvisualizer tab.  

#9

**Comment by ShagoY** [comment]
Yep i use Tempsgraph but i can't test.. Print in progress :-|

**Comment by jneilliii** [comment]
Outside of the tempsgraph conflict, I just released a new version that will allow you to enter your own text. @ShagoY, you would use the text `Subdivided with CATMULL ROM Leveling Grid:` in that field, but until the conflict is resolved, I don't think we're going to get anywhere for you guys.
