### ISSUE TITLE
0.1.6 intallation never ends.

### ISSUE THREAD

**Issue by Thisismydigitalself** [jneilliii/OctoPrint-BedLevelVisualizer#85]
OctoPrint ver 1.3.9

Requirement already satisfied: pytz>=0a in /home/pi/oprint/lib/python2.7/site-packages (from Babel>=1.0->Flask-Babel<0.10,>=0.9->OctoPrint->Bed-Visualizer==0.1.6) (2018.4)Installing collected packages: numpy, Bed-VisualizerRunning setup.py install for numpy: startedRunning setup.py install for numpy: 
still running...Running setup.py install for numpy: 
still running...Running setup.py install for numpy: 
still running...Running setup.py install for numpy: 
still running...Running setup.py install for numpy: 
still running...Running setup.py install for numpy: 
still running...Running setup.py install for numpy: 
still running...

![ice_screenshot_20180907-204958](https://user-images.githubusercontent.com/30949968/45234862-a9bd3280-b2df-11e8-9397-c9e73d8a5e38.png)

Can't even cancel installation.

Please advice steps for fixing this.
TY.

**Comment by Thisismydigitalself** [comment]
UPDATE: Installation finished after 5 min or so.
![ice_screenshot_20180907-205631](https://user-images.githubusercontent.com/30949968/45235129-8fd01f80-b2e0-11e8-8e62-5dc7e608ca03.png)

**Comment by jneilliii** [comment]
Yeah, the numpy requirement incorporated since version 0.1.3 introduced this slowness.  As documented in the [Known Issues](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer#known-issues). Some have reported it takes over 30 minutes depending on the Raspberry model.

**Comment by Thisismydigitalself** [comment]
If possible let the installation prompt the user things are progressing. for a noob like myself and I guess others like me it was not clear what goes on under the hood and no way to cancel.

**Comment by jneilliii** [comment]
Yeah, unfortunately I have no control over that part of the process. The discussion has been raised with Gina, but fairly low hanging fruit on the priority list I fear for all she's doing already.
