### ISSUE TITLE
Does BLV make changes to parm files?

### ISSUE THREAD

**Issue by skypuppy** [jneilliii/OctoPrint-BedLevelVisualizer#86]
Or only show what it finds?  My bed prints differently after trying BLV is why I'm asking.  If so, how do I undo those changes?
BLV did not work at all for the visualization.  Is some sensor required?

**Comment by jneilliii** [comment]
No, it shouldn't make any changes to your parameters at all, but depends on what you put into the GCODE setting for the plugin.  Typically you would use a mesh reporting command like `G29 T` which shouldn't do the bed leveling process just list the Z offsets into a form that is read by the plugin.
