### ISSUE TITLE
Tevo Tornado

### ISSUE THREAD

**Issue by debil1** [jneilliii/OctoPrint-BedLevelVisualizer#87]
Hi,

I installed this plugin but don't know how to use it.

I manually inserted commands into Terminal:  G29 T and received back:

Recv: Bilinear Leveling Grid:
Recv:       0      1      2      3      4
Recv:  0 -0.015 +0.011 +0.048 +0.017 -0.054
Recv:  1 -0.040 -0.066 +0.010 -0.039 -0.043
Recv:  2 -0.008 +0.045 +0.051 +0.034 -0.057
Recv:  3 +0.026 +0.033 +0.050 -0.005 -0.033
Recv:  4 +0.074 +0.051 +0.087 +0.053 -0.096

But where can I see visualization of that ?
At Bed visualizer I have only to insert:  " GCODE Commands" no pictures. At settings I have same + stored data.

**Comment by jneilliii** [comment]
What do you have configured in your settings?  Please upload screenshots so I can see it. What browser are you using?

**Comment by debil1** [comment]
Chrome, I just tried to put into terminal

G28
@BEDLEVELVISUALIZER
G29 T

BUt I receive only values; no graphic view (like this: http://lokspace.eu/3d-printer-auto-bed-leveling-mesh-visualizer/)

**Comment by debil1** [comment]
Or is this not correct method to try it ?

**Comment by jneilliii** [comment]
That should work. Are you saying the bed visualizer tab isn't showing anything at all? The tab could be hidden in the far right pull down, maybe that's what you're missing.

**Comment by MimbaMonkeyHouse** [comment]
This works fine for me on a Tevo Tornado with Octoprint 1.3.9:
G28
@BEDLEVELVISUALIZER
G29 T
The Save Mesh option is enabled.
