### ISSUE TITLE
Plugin Conflict with Tempsgraph

### ISSUE THREAD

**Issue by Desterly** [jneilliii/OctoPrint-BedLevelVisualizer#9]
There is currently a conflict between BedLevelVisualizer and Tempsgraph (https://github.com/1r0b1n0/OctoPrint-Tempsgraph). 

Tempsgraph is currently utilizing Plotly 1.33.1 which either the version of the distribution of it does not contain the "react" function causing the graph to not load.

Based on plugin load order and optimization, the resulting version of plotly loaded is the 1.33.1 version not the 1.35.2 needed for BedLevelVisualizer

Not sure if the two versions can be isolated by aliasing plotly or simply be brought into sync with version numbers.

Corresponding ticket for the other plugin (https://github.com/1r0b1n0/OctoPrint-Tempsgraph/issues/15)

**Comment by GhostlyCrowd** [comment]
Ah so this is why I don't get the graph either. Was just coming to report this.

**Comment by jneilliii** [comment]
Thanks for the detailed report. Hopefully TempsGraph can upgrade without issue. Not sure I can downgrade or not.

**Comment by Desterly** [comment]
Seems to be fine with the upgrade.  I created a pull request.

**Comment by jneilliii** [comment]
Awesome, thanks for doing all the leg work @Desterly.  Hopefully @1r0b1n0 will merge.

**Comment by jneilliii** [comment]
Closing in preference for keeping the react function of Plotly for improved performance, hopefully the pull request is merged.

**Comment by TheLion** [comment]
On my iPad there still is a conflict between these plugins. When I remove Tempsgraph plugin, the error disappears and the BedLevelVisualizer is displayed.
