### ISSUE TITLE
I'm getting what looks like a Javascript error when running the plugin on an MK3 (TypeError: undefined is not an object (evaluating 't._fullLayout._defs.selectAll'))

### ISSUE THREAD

**Issue by edgarschmidt** [jneilliii/OctoPrint-BedLevelVisualizer#91]
I'm getting the following error while upon running the plugin on my Prusa MK3:

`**TypeError:** undefined is not an object (evaluating 't._fullLayout._defs.selectAll')**`

Can anyone help me? These are the commands I entered for this printer:

`G80
@BEDLEVELVISUALIZER
G81`

**Comment by jneilliii** [comment]
Are the commands each on their own line like this?

```
G80
@BEDLEVELVISUALIZER
G81
```

**Comment by edgarschmidt** [comment]
Yes

- Edgar
________________________________

**Comment by jneilliii** [comment]
I know others have used this plugin on a MK3 so I'll need some additional information to better assist.  What browser are you using? Does your machine's video card support OpenGL?  If you go to the link below, does the surface area load?

https://plot.ly/javascript/3d-surface-plots/

Are there any errors in your ocotprint.log file?

**Comment by edgarschmidt** [comment]
Alright, the browser and the error log didn't show anything unusual (I'm running this on my MBP 13 Tocuhbar), however I ran updates again and rebooted Octopi and now everything works! I have no idea why I was seeing that error before.

**Comment by edgarschmidt** [comment]
Will this plugin report back changes made through the manual tuning option in the MK3 controller?

**Comment by jneilliii** [comment]
I'm not really sure how the prusa firmware works, but assuming it stores the leveling data in eeprom the command G81 would just report the current data so making the plugin's settings the following it should show. 

```
@BEDLEVELVISUALIZER
G81
```
