### ISSUE TITLE
Configurable plot height for the Bed visualizer plot area

### ISSUE THREAD

**Issue by ikout** [jneilliii/OctoPrint-BedLevelVisualizer#93]
Hello,

I like the plugin and it's useful, can I ask for a small enchantment if possible?
Can we add an option or where we can change that at the plugin manually to increase the height of the plot?

I have a relative large screen and I use the "Themify" plugin as well and even with or without it when I am at the BedLevelVisualizer tab the plot area is quite small especially at the vertical/height dimension if that could be adjusted it would be great!

Also the default plot area is "cropping" a bit of the graph as you can see at the screenshot below.
If this has been mentioned before and I missed it sorry.

Thanks!

<img width="1064" alt="bedlevelvisualizer_default" src="https://user-images.githubusercontent.com/9326582/47107004-c2125c80-d250-11e8-91c7-2f8266ed68a3.png">

<img width="1841" alt="bedlevelvisualizer_with_themify" src="https://user-images.githubusercontent.com/9326582/47107015-c8083d80-d250-11e8-9842-f06c01fe1e59.png">

**Comment by jneilliii** [comment]
You could adjust your themeify to set whatever height you want. Without knowing your current config it's hard to say, but for me just swapping the tab elements width properties made the graph fill my screen. Something like this.

![image](https://user-images.githubusercontent.com/5249455/47260446-ab0a7f00-d489-11e8-8773-1874f038610c.png)

Produced the following.

![image](https://user-images.githubusercontent.com/5249455/47260464-03418100-d48a-11e8-8828-94c042f0e7e3.png)

The side effect is that all tabs get stretched and may cause other UI issues.  You could just adjust the size of the plot container and let it overflow by adding the following in Themeify (selector is #bedlevelvisualizergraph).

![image](https://user-images.githubusercontent.com/5249455/47260482-88c53100-d48a-11e8-8733-a99a211b73c5.png)

Produces the following.

![image](https://user-images.githubusercontent.com/5249455/47260494-b5794880-d48a-11e8-9ed1-b92365878c4e.png)

**Comment by ikout** [comment]
Thanks!
I was looking at a Themify way but I didn't had any luck finding the proper selector...

"#bedlevelvisualizergraph" and only changing the "height" value works for this change just fine.
