### ISSUE TITLE
What is the recommended workflow with plugin?

### ISSUE THREAD

**Issue by bumbalu** [jneilliii/OctoPrint-BedLevelVisualizer#94]
Hi. 
Thank you for nice plugin and thank you for making it compatible with Repetier firmware. 
My question is what would be the recommended workflow if I mostly print on same glass and very rarely remove it from heatbed. Is it like this: 
1. In the plugin I enable "Save mash" option. 
2. In Repetier firmware I enable "store correction data in EEPROM". 
3. Before print I warm up enclosure and heatbed and manually run "G33 R0" to reset the distortion matrix and manually update stored in EEPROM mash by pushing the button "update mash" on plugin tab. 
4. I run the slicer with G28 and G32 commands (without G33) in its prefix. No need to run G33 before each print as the distortion values are stored in EEPROM (and yaml?)
5. If someday I'm going to print at different heatbed temperature (and the table/glass distortion will change) or change the glass than I need to manually run "G33 R0" to reset the distortion matrix and manually update the mash once. 
If you think the workflow should be different could you please give details?

**Comment by jneilliii** [comment]
That workflow seems equivalent to what I do with Marlin and Unified Bed Leveling.
