### ISSUE TITLE
It only probes the middle.

### ISSUE THREAD

**Issue by bugilt** [jneilliii/OctoPrint-BedLevelVisualizer#95]
When I update the mesh it only probes the center. 

G28
@BEDLEVELVISUALIZER
G29 T

**Comment by bugilt** [comment]
I found this in the marlin firmware. These were deactivated.

#if ENABLED(AUTO_BED_LEVELING_3POINT) || ENABLED(AUTO_BED_LEVELING_UBL)
  #define PROBE_PT_1_X 15
  #define PROBE_PT_1_Y 180
  #define PROBE_PT_2_X 15
  #define PROBE_PT_2_Y 20
  #define PROBE_PT_3_X 170
  #define PROBE_PT_3_Y 20

**Comment by jneilliii** [comment]
The plugin assumes that you have some form of autoleveling enabled that utilizes a probe.

**Comment by bugilt** [comment]
I figured it out. I got a bit ahead of myself with modding my printer.
